// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_tokens.sql

package store

import (
	"context"
	"database/sql"
)

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO access_tokens (
    id, user_id, name, token_prefix, token_hash, expires_at, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP
) RETURNING id, user_id, name, token_prefix, token_hash, expires_at, last_used_at, created_at, revoked_at
`

type CreateAccessTokenParams struct {
	ID          string       `json:"id"`
	UserID      string       `json:"user_id"`
	Name        string       `json:"name"`
	TokenPrefix string       `json:"token_prefix"`
	TokenHash   string       `json:"token_hash"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error) {
	row := q.db.QueryRowContext(ctx, createAccessToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAccessTokenByHash = `-- name: GetAccessTokenByHash :one
SELECT id, user_id, name, token_prefix, token_hash, expires_at, last_used_at, created_at, revoked_at
FROM access_tokens
WHERE token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetAccessTokenByHash(ctx context.Context, tokenHash string) (AccessToken, error) {
	row := q.db.QueryRowContext(ctx, getAccessTokenByHash, tokenHash)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const latestAccessTokenUse = `-- name: LatestAccessTokenUse :one
SELECT id, token_id, used_at, ip, user_agent
FROM access_token_uses
WHERE token_id = ?
ORDER BY used_at DESC
LIMIT 1
`

func (q *Queries) LatestAccessTokenUse(ctx context.Context, tokenID string) (AccessTokenUse, error) {
	row := q.db.QueryRowContext(ctx, latestAccessTokenUse, tokenID)
	var i AccessTokenUse
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.UsedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const listAccessTokenUses = `-- name: ListAccessTokenUses :many
SELECT u.id, u.token_id, u.used_at, u.ip, u.user_agent
FROM access_token_uses u
JOIN access_tokens t ON t.id = u.token_id
WHERE u.token_id = ? AND t.user_id = ?
ORDER BY u.used_at DESC
LIMIT ?
`

type ListAccessTokenUsesParams struct {
	TokenID string `json:"token_id"`
	UserID  string `json:"user_id"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) ListAccessTokenUses(ctx context.Context, arg ListAccessTokenUsesParams) ([]AccessTokenUse, error) {
	rows, err := q.db.QueryContext(ctx, listAccessTokenUses, arg.TokenID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessTokenUse
	for rows.Next() {
		var i AccessTokenUse
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.UsedAt,
			&i.Ip,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessTokensByUser = `-- name: ListAccessTokensByUser :many
SELECT id, user_id, name, token_prefix, token_hash, expires_at, last_used_at, created_at, revoked_at
FROM access_tokens
WHERE user_id = ? AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAccessTokensByUser(ctx context.Context, userID string) ([]AccessToken, error) {
	rows, err := q.db.QueryContext(ctx, listAccessTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessToken
	for rows.Next() {
		var i AccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenPrefix,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAccessTokenUses = `-- name: PruneAccessTokenUses :exec
DELETE FROM access_token_uses
WHERE access_token_uses.token_id = ?
  AND access_token_uses.id NOT IN (
      SELECT keep.id FROM access_token_uses keep
      WHERE keep.token_id = ?
      ORDER BY keep.used_at DESC
      LIMIT ?
  )
`

type PruneAccessTokenUsesParams struct {
	TokenID   string `json:"token_id"`
	TokenID_2 string `json:"token_id_2"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) PruneAccessTokenUses(ctx context.Context, arg PruneAccessTokenUsesParams) error {
	_, err := q.db.ExecContext(ctx, pruneAccessTokenUses, arg.TokenID, arg.TokenID_2, arg.Limit)
	return err
}

const recordAccessTokenUse = `-- name: RecordAccessTokenUse :exec
INSERT INTO access_token_uses (id, token_id, ip, user_agent)
VALUES (?, ?, ?, ?)
`

type RecordAccessTokenUseParams struct {
	ID        string `json:"id"`
	TokenID   string `json:"token_id"`
	Ip        string `json:"ip"`
	UserAgent string `json:"user_agent"`
}

func (q *Queries) RecordAccessTokenUse(ctx context.Context, arg RecordAccessTokenUseParams) error {
	_, err := q.db.ExecContext(ctx, recordAccessTokenUse,
		arg.ID,
		arg.TokenID,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const revokeAccessToken = `-- name: RevokeAccessToken :execrows
UPDATE access_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ? AND revoked_at IS NULL
`

type RevokeAccessTokenParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAccessToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAccessTokenLastUsed = `-- name: TouchAccessTokenLastUsed :exec
UPDATE access_tokens
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) TouchAccessTokenLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchAccessTokenLastUsed, id)
	return err
}
