// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package store

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, user_id, name, broker, account_type, base_currency, starting_balance)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, user_id, name, broker, account_type, base_currency, starting_balance, created_at
`

type CreateAccountParams struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	Name            string  `json:"name"`
	Broker          string  `json:"broker"`
	AccountType     string  `json:"account_type"`
	BaseCurrency    string  `json:"base_currency"`
	StartingBalance float64 `json:"starting_balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Broker,
		arg.AccountType,
		arg.BaseCurrency,
		arg.StartingBalance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Broker,
		&i.AccountType,
		&i.BaseCurrency,
		&i.StartingBalance,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ? AND user_id = ?
`

type DeleteAccountParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, arg.ID, arg.UserID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, name, broker, account_type, base_currency, starting_balance, created_at FROM accounts WHERE id = ? AND user_id = ?
`

type GetAccountParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Broker,
		&i.AccountType,
		&i.BaseCurrency,
		&i.StartingBalance,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, user_id, name, broker, account_type, base_currency, starting_balance, created_at FROM accounts WHERE user_id = ? ORDER BY created_at
`

func (q *Queries) ListAccounts(ctx context.Context, userID string) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Broker,
			&i.AccountType,
			&i.BaseCurrency,
			&i.StartingBalance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
