// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package store

import (
	"context"
	"database/sql"
)

const deleteAlertChannel = `-- name: DeleteAlertChannel :execrows
DELETE FROM alert_channels WHERE id = ? AND user_id = ?
`

type DeleteAlertChannelParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAlertChannel(ctx context.Context, arg DeleteAlertChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAlertChannel, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAlertChannelByTarget = `-- name: DeleteAlertChannelByTarget :execrows
DELETE FROM alert_channels WHERE user_id = ? AND kind = ? AND target = ?
`

type DeleteAlertChannelByTargetParams struct {
	UserID string `json:"user_id"`
	Kind   string `json:"kind"`
	Target string `json:"target"`
}

func (q *Queries) DeleteAlertChannelByTarget(ctx context.Context, arg DeleteAlertChannelByTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAlertChannelByTarget, arg.UserID, arg.Kind, arg.Target)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const disableAlertChannel = `-- name: DisableAlertChannel :exec
UPDATE alert_channels SET enabled = 0, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) DisableAlertChannel(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, disableAlertChannel, id)
	return err
}

const getAlertChannel = `-- name: GetAlertChannel :one
SELECT id, user_id, kind, target, label, enabled, last_sent_at, last_status, last_error, created_at, updated_at FROM alert_channels WHERE id = ? AND user_id = ?
`

type GetAlertChannelParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAlertChannel(ctx context.Context, arg GetAlertChannelParams) (AlertChannel, error) {
	row := q.db.QueryRowContext(ctx, getAlertChannel, arg.ID, arg.UserID)
	var i AlertChannel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Target,
		&i.Label,
		&i.Enabled,
		&i.LastSentAt,
		&i.LastStatus,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertSettings = `-- name: GetAlertSettings :one
SELECT user_id, enabled, timezone, rule_risk, rule_daily_loss, rule_loss_streak, loss_streak_n, rule_prop_drawdown, prop_warn_pct, rule_unreviewed, unreviewed_days, updated_at FROM alert_settings WHERE user_id = ?
`

func (q *Queries) GetAlertSettings(ctx context.Context, userID string) (AlertSetting, error) {
	row := q.db.QueryRowContext(ctx, getAlertSettings, userID)
	var i AlertSetting
	err := row.Scan(
		&i.UserID,
		&i.Enabled,
		&i.Timezone,
		&i.RuleRisk,
		&i.RuleDailyLoss,
		&i.RuleLossStreak,
		&i.LossStreakN,
		&i.RulePropDrawdown,
		&i.PropWarnPct,
		&i.RuleUnreviewed,
		&i.UnreviewedDays,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAlertEvent = `-- name: InsertAlertEvent :execrows
INSERT INTO alert_events (id, user_id, rule, dedupe_key, title, body, fired_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id, rule, dedupe_key) DO NOTHING
`

type InsertAlertEventParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Rule      string `json:"rule"`
	DedupeKey string `json:"dedupe_key"`
	Title     string `json:"title"`
	Body      string `json:"body"`
}

func (q *Queries) InsertAlertEvent(ctx context.Context, arg InsertAlertEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAlertEvent,
		arg.ID,
		arg.UserID,
		arg.Rule,
		arg.DedupeKey,
		arg.Title,
		arg.Body,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAlertChannels = `-- name: ListAlertChannels :many
SELECT id, user_id, kind, target, label, enabled, last_sent_at, last_status, last_error, created_at, updated_at FROM alert_channels WHERE user_id = ? ORDER BY created_at
`

func (q *Queries) ListAlertChannels(ctx context.Context, userID string) ([]AlertChannel, error) {
	rows, err := q.db.QueryContext(ctx, listAlertChannels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertChannel
	for rows.Next() {
		var i AlertChannel
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Target,
			&i.Label,
			&i.Enabled,
			&i.LastSentAt,
			&i.LastStatus,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertEvents = `-- name: ListAlertEvents :many
SELECT id, user_id, rule, dedupe_key, title, body, fired_at FROM alert_events WHERE user_id = ? ORDER BY fired_at DESC LIMIT ?
`

type ListAlertEventsParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListAlertEvents(ctx context.Context, arg ListAlertEventsParams) ([]AlertEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAlertEvents, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertEvent
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Rule,
			&i.DedupeKey,
			&i.Title,
			&i.Body,
			&i.FiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertChannels = `-- name: ListEnabledAlertChannels :many
SELECT id, user_id, kind, target, label, enabled, last_sent_at, last_status, last_error, created_at, updated_at FROM alert_channels WHERE user_id = ? AND enabled = 1 ORDER BY created_at
`

func (q *Queries) ListEnabledAlertChannels(ctx context.Context, userID string) ([]AlertChannel, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledAlertChannels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertChannel
	for rows.Next() {
		var i AlertChannel
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Target,
			&i.Label,
			&i.Enabled,
			&i.LastSentAt,
			&i.LastStatus,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertSettings = `-- name: ListEnabledAlertSettings :many
SELECT user_id, enabled, timezone, rule_risk, rule_daily_loss, rule_loss_streak, loss_streak_n, rule_prop_drawdown, prop_warn_pct, rule_unreviewed, unreviewed_days, updated_at FROM alert_settings WHERE enabled = 1 ORDER BY user_id
`

func (q *Queries) ListEnabledAlertSettings(ctx context.Context) ([]AlertSetting, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledAlertSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertSetting
	for rows.Next() {
		var i AlertSetting
		if err := rows.Scan(
			&i.UserID,
			&i.Enabled,
			&i.Timezone,
			&i.RuleRisk,
			&i.RuleDailyLoss,
			&i.RuleLossStreak,
			&i.LossStreakN,
			&i.RulePropDrawdown,
			&i.PropWarnPct,
			&i.RuleUnreviewed,
			&i.UnreviewedDays,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAlertChannelEnabled = `-- name: SetAlertChannelEnabled :one
UPDATE alert_channels SET enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, kind, target, label, enabled, last_sent_at, last_status, last_error, created_at, updated_at
`

type SetAlertChannelEnabledParams struct {
	Enabled int64  `json:"enabled"`
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) SetAlertChannelEnabled(ctx context.Context, arg SetAlertChannelEnabledParams) (AlertChannel, error) {
	row := q.db.QueryRowContext(ctx, setAlertChannelEnabled, arg.Enabled, arg.ID, arg.UserID)
	var i AlertChannel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Target,
		&i.Label,
		&i.Enabled,
		&i.LastSentAt,
		&i.LastStatus,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlertChannelStatus = `-- name: UpdateAlertChannelStatus :exec
UPDATE alert_channels SET last_sent_at = ?, last_status = ?, last_error = ?
WHERE id = ?
`

type UpdateAlertChannelStatusParams struct {
	LastSentAt sql.NullTime `json:"last_sent_at"`
	LastStatus string       `json:"last_status"`
	LastError  string       `json:"last_error"`
	ID         string       `json:"id"`
}

func (q *Queries) UpdateAlertChannelStatus(ctx context.Context, arg UpdateAlertChannelStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAlertChannelStatus,
		arg.LastSentAt,
		arg.LastStatus,
		arg.LastError,
		arg.ID,
	)
	return err
}

const upsertAlertChannel = `-- name: UpsertAlertChannel :one
INSERT INTO alert_channels (id, user_id, kind, target, label, enabled)
VALUES (?, ?, ?, ?, ?, 1)
ON CONFLICT(user_id, kind, target) DO UPDATE SET
    label = excluded.label,
    enabled = 1,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, kind, target, label, enabled, last_sent_at, last_status, last_error, created_at, updated_at
`

type UpsertAlertChannelParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Kind   string `json:"kind"`
	Target string `json:"target"`
	Label  string `json:"label"`
}

func (q *Queries) UpsertAlertChannel(ctx context.Context, arg UpsertAlertChannelParams) (AlertChannel, error) {
	row := q.db.QueryRowContext(ctx, upsertAlertChannel,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Target,
		arg.Label,
	)
	var i AlertChannel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Target,
		&i.Label,
		&i.Enabled,
		&i.LastSentAt,
		&i.LastStatus,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAlertSettings = `-- name: UpsertAlertSettings :one
INSERT INTO alert_settings (
    user_id, enabled, timezone,
    rule_risk, rule_daily_loss, rule_loss_streak, loss_streak_n,
    rule_prop_drawdown, prop_warn_pct, rule_unreviewed, unreviewed_days,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
    enabled = excluded.enabled,
    timezone = excluded.timezone,
    rule_risk = excluded.rule_risk,
    rule_daily_loss = excluded.rule_daily_loss,
    rule_loss_streak = excluded.rule_loss_streak,
    loss_streak_n = excluded.loss_streak_n,
    rule_prop_drawdown = excluded.rule_prop_drawdown,
    prop_warn_pct = excluded.prop_warn_pct,
    rule_unreviewed = excluded.rule_unreviewed,
    unreviewed_days = excluded.unreviewed_days,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, enabled, timezone, rule_risk, rule_daily_loss, rule_loss_streak, loss_streak_n, rule_prop_drawdown, prop_warn_pct, rule_unreviewed, unreviewed_days, updated_at
`

type UpsertAlertSettingsParams struct {
	UserID           string  `json:"user_id"`
	Enabled          int64   `json:"enabled"`
	Timezone         string  `json:"timezone"`
	RuleRisk         int64   `json:"rule_risk"`
	RuleDailyLoss    int64   `json:"rule_daily_loss"`
	RuleLossStreak   int64   `json:"rule_loss_streak"`
	LossStreakN      int64   `json:"loss_streak_n"`
	RulePropDrawdown int64   `json:"rule_prop_drawdown"`
	PropWarnPct      float64 `json:"prop_warn_pct"`
	RuleUnreviewed   int64   `json:"rule_unreviewed"`
	UnreviewedDays   int64   `json:"unreviewed_days"`
}

func (q *Queries) UpsertAlertSettings(ctx context.Context, arg UpsertAlertSettingsParams) (AlertSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertAlertSettings,
		arg.UserID,
		arg.Enabled,
		arg.Timezone,
		arg.RuleRisk,
		arg.RuleDailyLoss,
		arg.RuleLossStreak,
		arg.LossStreakN,
		arg.RulePropDrawdown,
		arg.PropWarnPct,
		arg.RuleUnreviewed,
		arg.UnreviewedDays,
	)
	var i AlertSetting
	err := row.Scan(
		&i.UserID,
		&i.Enabled,
		&i.Timezone,
		&i.RuleRisk,
		&i.RuleDailyLoss,
		&i.RuleLossStreak,
		&i.LossStreakN,
		&i.RulePropDrawdown,
		&i.PropWarnPct,
		&i.RuleUnreviewed,
		&i.UnreviewedDays,
		&i.UpdatedAt,
	)
	return i, err
}
