// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annual_goals.sql

package store

import (
	"context"
)

const deleteAnnualGoal = `-- name: DeleteAnnualGoal :execrows
DELETE FROM annual_goals
WHERE user_id = ? AND year = ?
`

type DeleteAnnualGoalParams struct {
	UserID string `json:"user_id"`
	Year   int64  `json:"year"`
}

func (q *Queries) DeleteAnnualGoal(ctx context.Context, arg DeleteAnnualGoalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAnnualGoal, arg.UserID, arg.Year)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAnnualGoal = `-- name: GetAnnualGoal :one
SELECT user_id, year, amount, updated_at
FROM annual_goals
WHERE user_id = ? AND year = ?
`

type GetAnnualGoalParams struct {
	UserID string `json:"user_id"`
	Year   int64  `json:"year"`
}

func (q *Queries) GetAnnualGoal(ctx context.Context, arg GetAnnualGoalParams) (AnnualGoal, error) {
	row := q.db.QueryRowContext(ctx, getAnnualGoal, arg.UserID, arg.Year)
	var i AnnualGoal
	err := row.Scan(
		&i.UserID,
		&i.Year,
		&i.Amount,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAnnualGoal = `-- name: UpsertAnnualGoal :one
INSERT INTO annual_goals (user_id, year, amount, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id, year) DO UPDATE SET
    amount = excluded.amount,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, year, amount, updated_at
`

type UpsertAnnualGoalParams struct {
	UserID string  `json:"user_id"`
	Year   int64   `json:"year"`
	Amount float64 `json:"amount"`
}

func (q *Queries) UpsertAnnualGoal(ctx context.Context, arg UpsertAnnualGoalParams) (AnnualGoal, error) {
	row := q.db.QueryRowContext(ctx, upsertAnnualGoal, arg.UserID, arg.Year, arg.Amount)
	var i AnnualGoal
	err := row.Scan(
		&i.UserID,
		&i.Year,
		&i.Amount,
		&i.UpdatedAt,
	)
	return i, err
}
