// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package store

import (
	"context"
)

const deleteAttachment = `-- name: DeleteAttachment :execrows
DELETE FROM trade_attachments WHERE id = ? AND user_id = ?
`

type DeleteAttachmentParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAttachment, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, user_id, trade_id, filename, content_type, size_bytes, storage_key, created_at FROM trade_attachments WHERE id = ? AND user_id = ?
`

type GetAttachmentParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (TradeAttachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachment, arg.ID, arg.UserID)
	var i TradeAttachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TradeID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO trade_attachments (id, user_id, trade_id, filename, content_type, size_bytes, storage_key)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, user_id, trade_id, filename, content_type, size_bytes, storage_key, created_at
`

type InsertAttachmentParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	TradeID     string `json:"trade_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
	StorageKey  string `json:"storage_key"`
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (TradeAttachment, error) {
	row := q.db.QueryRowContext(ctx, insertAttachment,
		arg.ID,
		arg.UserID,
		arg.TradeID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i TradeAttachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TradeID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsForTrade = `-- name: ListAttachmentsForTrade :many
SELECT id, user_id, trade_id, filename, content_type, size_bytes, storage_key, created_at FROM trade_attachments WHERE trade_id = ? AND user_id = ? ORDER BY created_at
`

type ListAttachmentsForTradeParams struct {
	TradeID string `json:"trade_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) ListAttachmentsForTrade(ctx context.Context, arg ListAttachmentsForTradeParams) ([]TradeAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsForTrade, arg.TradeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradeAttachment
	for rows.Next() {
		var i TradeAttachment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TradeID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
