// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cash.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const deleteCashTransaction = `-- name: DeleteCashTransaction :execrows
DELETE FROM cash_transactions WHERE id = ? AND user_id = ?
`

type DeleteCashTransactionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteCashTransaction(ctx context.Context, arg DeleteCashTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCashTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertCashTransaction = `-- name: InsertCashTransaction :one
INSERT INTO cash_transactions (id, user_id, account_id, type, amount, currency, occurred_at, note, import_batch_id, trade_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, user_id, account_id, type, amount, currency, occurred_at, note, import_batch_id, created_at, trade_id
`

type InsertCashTransactionParams struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	AccountID     string         `json:"account_id"`
	Type          string         `json:"type"`
	Amount        float64        `json:"amount"`
	Currency      string         `json:"currency"`
	OccurredAt    time.Time      `json:"occurred_at"`
	Note          string         `json:"note"`
	ImportBatchID sql.NullString `json:"import_batch_id"`
	TradeID       sql.NullString `json:"trade_id"`
}

func (q *Queries) InsertCashTransaction(ctx context.Context, arg InsertCashTransactionParams) (CashTransaction, error) {
	row := q.db.QueryRowContext(ctx, insertCashTransaction,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.OccurredAt,
		arg.Note,
		arg.ImportBatchID,
		arg.TradeID,
	)
	var i CashTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.OccurredAt,
		&i.Note,
		&i.ImportBatchID,
		&i.CreatedAt,
		&i.TradeID,
	)
	return i, err
}

const listCashForTrade = `-- name: ListCashForTrade :many
SELECT id, user_id, account_id, type, amount, currency, occurred_at, note, import_batch_id, created_at, trade_id FROM cash_transactions
WHERE user_id = ? AND trade_id = ?
ORDER BY occurred_at
`

type ListCashForTradeParams struct {
	UserID  string         `json:"user_id"`
	TradeID sql.NullString `json:"trade_id"`
}

func (q *Queries) ListCashForTrade(ctx context.Context, arg ListCashForTradeParams) ([]CashTransaction, error) {
	rows, err := q.db.QueryContext(ctx, listCashForTrade, arg.UserID, arg.TradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashTransaction
	for rows.Next() {
		var i CashTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.OccurredAt,
			&i.Note,
			&i.ImportBatchID,
			&i.CreatedAt,
			&i.TradeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashTransactions = `-- name: ListCashTransactions :many
SELECT id, user_id, account_id, type, amount, currency, occurred_at, note, import_batch_id, created_at, trade_id FROM cash_transactions
WHERE user_id = ? AND (?2 IS NULL OR account_id = ?2)
ORDER BY occurred_at
`

type ListCashTransactionsParams struct {
	UserID    string      `json:"user_id"`
	AccountID interface{} `json:"account_id"`
}

func (q *Queries) ListCashTransactions(ctx context.Context, arg ListCashTransactionsParams) ([]CashTransaction, error) {
	rows, err := q.db.QueryContext(ctx, listCashTransactions, arg.UserID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashTransaction
	for rows.Next() {
		var i CashTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.OccurredAt,
			&i.Note,
			&i.ImportBatchID,
			&i.CreatedAt,
			&i.TradeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
