// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coach_settings.sql

package store

import (
	"context"
)

const getCoachSettings = `-- name: GetCoachSettings :one
SELECT id, enabled, base_url, api_key, model, custom_prompt, updated_at
FROM coach_settings
WHERE id = 1
`

func (q *Queries) GetCoachSettings(ctx context.Context) (CoachSetting, error) {
	row := q.db.QueryRowContext(ctx, getCoachSettings)
	var i CoachSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Model,
		&i.CustomPrompt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCoachSettings = `-- name: UpsertCoachSettings :one
INSERT INTO coach_settings (id, enabled, base_url, api_key, model, custom_prompt, updated_at)
VALUES (1, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    enabled = excluded.enabled,
    base_url = excluded.base_url,
    api_key = excluded.api_key,
    model = excluded.model,
    custom_prompt = excluded.custom_prompt,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, enabled, base_url, api_key, model, custom_prompt, updated_at
`

type UpsertCoachSettingsParams struct {
	Enabled      int64  `json:"enabled"`
	BaseUrl      string `json:"base_url"`
	ApiKey       string `json:"api_key"`
	Model        string `json:"model"`
	CustomPrompt string `json:"custom_prompt"`
}

func (q *Queries) UpsertCoachSettings(ctx context.Context, arg UpsertCoachSettingsParams) (CoachSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertCoachSettings,
		arg.Enabled,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Model,
		arg.CustomPrompt,
	)
	var i CoachSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Model,
		&i.CustomPrompt,
		&i.UpdatedAt,
	)
	return i, err
}
