// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cooldowns.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createCooldownSession = `-- name: CreateCooldownSession :one
INSERT INTO cooldown_sessions (id, user_id, started_at, ends_at, trigger, impulse)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, started_at, ends_at, "trigger", impulse, released_at, released_early, setup_id, return_rule, reflection, created_at, updated_at
`

type CreateCooldownSessionParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	StartedAt time.Time `json:"started_at"`
	EndsAt    time.Time `json:"ends_at"`
	Trigger   string    `json:"trigger"`
	Impulse   string    `json:"impulse"`
}

func (q *Queries) CreateCooldownSession(ctx context.Context, arg CreateCooldownSessionParams) (CooldownSession, error) {
	row := q.db.QueryRowContext(ctx, createCooldownSession,
		arg.ID,
		arg.UserID,
		arg.StartedAt,
		arg.EndsAt,
		arg.Trigger,
		arg.Impulse,
	)
	var i CooldownSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndsAt,
		&i.Trigger,
		&i.Impulse,
		&i.ReleasedAt,
		&i.ReleasedEarly,
		&i.SetupID,
		&i.ReturnRule,
		&i.Reflection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCooldownSession = `-- name: DeleteCooldownSession :execrows
DELETE FROM cooldown_sessions WHERE id = ? AND user_id = ?
`

type DeleteCooldownSessionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteCooldownSession(ctx context.Context, arg DeleteCooldownSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCooldownSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const extendCooldownSession = `-- name: ExtendCooldownSession :one
UPDATE cooldown_sessions SET ends_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, started_at, ends_at, "trigger", impulse, released_at, released_early, setup_id, return_rule, reflection, created_at, updated_at
`

type ExtendCooldownSessionParams struct {
	EndsAt time.Time `json:"ends_at"`
	ID     string    `json:"id"`
	UserID string    `json:"user_id"`
}

func (q *Queries) ExtendCooldownSession(ctx context.Context, arg ExtendCooldownSessionParams) (CooldownSession, error) {
	row := q.db.QueryRowContext(ctx, extendCooldownSession, arg.EndsAt, arg.ID, arg.UserID)
	var i CooldownSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndsAt,
		&i.Trigger,
		&i.Impulse,
		&i.ReleasedAt,
		&i.ReleasedEarly,
		&i.SetupID,
		&i.ReturnRule,
		&i.Reflection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCooldownSession = `-- name: GetCooldownSession :one
SELECT id, user_id, started_at, ends_at, "trigger", impulse, released_at, released_early, setup_id, return_rule, reflection, created_at, updated_at FROM cooldown_sessions WHERE id = ? AND user_id = ?
`

type GetCooldownSessionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetCooldownSession(ctx context.Context, arg GetCooldownSessionParams) (CooldownSession, error) {
	row := q.db.QueryRowContext(ctx, getCooldownSession, arg.ID, arg.UserID)
	var i CooldownSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndsAt,
		&i.Trigger,
		&i.Impulse,
		&i.ReleasedAt,
		&i.ReleasedEarly,
		&i.SetupID,
		&i.ReturnRule,
		&i.Reflection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenCooldownSession = `-- name: GetOpenCooldownSession :one
SELECT id, user_id, started_at, ends_at, "trigger", impulse, released_at, released_early, setup_id, return_rule, reflection, created_at, updated_at FROM cooldown_sessions
WHERE user_id = ? AND released_at IS NULL
ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) GetOpenCooldownSession(ctx context.Context, userID string) (CooldownSession, error) {
	row := q.db.QueryRowContext(ctx, getOpenCooldownSession, userID)
	var i CooldownSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndsAt,
		&i.Trigger,
		&i.Impulse,
		&i.ReleasedAt,
		&i.ReleasedEarly,
		&i.SetupID,
		&i.ReturnRule,
		&i.Reflection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCooldownSessions = `-- name: ListCooldownSessions :many
SELECT id, user_id, started_at, ends_at, "trigger", impulse, released_at, released_early, setup_id, return_rule, reflection, created_at, updated_at FROM cooldown_sessions WHERE user_id = ? ORDER BY started_at DESC
`

func (q *Queries) ListCooldownSessions(ctx context.Context, userID string) ([]CooldownSession, error) {
	rows, err := q.db.QueryContext(ctx, listCooldownSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CooldownSession
	for rows.Next() {
		var i CooldownSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartedAt,
			&i.EndsAt,
			&i.Trigger,
			&i.Impulse,
			&i.ReleasedAt,
			&i.ReleasedEarly,
			&i.SetupID,
			&i.ReturnRule,
			&i.Reflection,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseCooldownSession = `-- name: ReleaseCooldownSession :one
UPDATE cooldown_sessions SET
    released_at = ?,
    released_early = ?,
    impulse = ?,
    setup_id = ?,
    return_rule = ?,
    reflection = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, started_at, ends_at, "trigger", impulse, released_at, released_early, setup_id, return_rule, reflection, created_at, updated_at
`

type ReleaseCooldownSessionParams struct {
	ReleasedAt    sql.NullTime   `json:"released_at"`
	ReleasedEarly int64          `json:"released_early"`
	Impulse       string         `json:"impulse"`
	SetupID       sql.NullString `json:"setup_id"`
	ReturnRule    string         `json:"return_rule"`
	Reflection    string         `json:"reflection"`
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
}

func (q *Queries) ReleaseCooldownSession(ctx context.Context, arg ReleaseCooldownSessionParams) (CooldownSession, error) {
	row := q.db.QueryRowContext(ctx, releaseCooldownSession,
		arg.ReleasedAt,
		arg.ReleasedEarly,
		arg.Impulse,
		arg.SetupID,
		arg.ReturnRule,
		arg.Reflection,
		arg.ID,
		arg.UserID,
	)
	var i CooldownSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndsAt,
		&i.Trigger,
		&i.Impulse,
		&i.ReleasedAt,
		&i.ReleasedEarly,
		&i.SetupID,
		&i.ReturnRule,
		&i.Reflection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
