// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: economic_events.sql

package store

import (
	"context"
)

const deleteFutureEconomicEvents = `-- name: DeleteFutureEconomicEvents :exec
DELETE FROM economic_events
WHERE provider = ?1 AND event_ts >= ?2
`

type DeleteFutureEconomicEventsParams struct {
	Provider string `json:"provider"`
	EventTs  string `json:"event_ts"`
}

func (q *Queries) DeleteFutureEconomicEvents(ctx context.Context, arg DeleteFutureEconomicEventsParams) error {
	_, err := q.db.ExecContext(ctx, deleteFutureEconomicEvents, arg.Provider, arg.EventTs)
	return err
}

const getEconomicEventsLastFetch = `-- name: GetEconomicEventsLastFetch :one
SELECT fetched_at
FROM economic_events
WHERE provider = ?1
ORDER BY fetched_at DESC
LIMIT 1
`

func (q *Queries) GetEconomicEventsLastFetch(ctx context.Context, provider string) (string, error) {
	row := q.db.QueryRowContext(ctx, getEconomicEventsLastFetch, provider)
	var fetched_at string
	err := row.Scan(&fetched_at)
	return fetched_at, err
}

const listEconomicEvents = `-- name: ListEconomicEvents :many
SELECT id, provider, title, country, impact, event_ts, forecast, previous, actual, fetched_at
FROM economic_events
WHERE event_ts >= ?1 AND event_ts < ?2
ORDER BY event_ts, country, title
`

type ListEconomicEventsParams struct {
	EventTs   string `json:"event_ts"`
	EventTs_2 string `json:"event_ts_2"`
}

func (q *Queries) ListEconomicEvents(ctx context.Context, arg ListEconomicEventsParams) ([]EconomicEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEconomicEvents, arg.EventTs, arg.EventTs_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EconomicEvent
	for rows.Next() {
		var i EconomicEvent
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Title,
			&i.Country,
			&i.Impact,
			&i.EventTs,
			&i.Forecast,
			&i.Previous,
			&i.Actual,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEconomicEvent = `-- name: UpsertEconomicEvent :exec
INSERT INTO economic_events (
    provider, title, country, impact, event_ts, forecast, previous, actual, fetched_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(provider, country, title, event_ts) DO UPDATE SET
    impact = excluded.impact,
    forecast = excluded.forecast,
    previous = excluded.previous,
    actual = excluded.actual,
    fetched_at = excluded.fetched_at
`

type UpsertEconomicEventParams struct {
	Provider  string `json:"provider"`
	Title     string `json:"title"`
	Country   string `json:"country"`
	Impact    string `json:"impact"`
	EventTs   string `json:"event_ts"`
	Forecast  string `json:"forecast"`
	Previous  string `json:"previous"`
	Actual    string `json:"actual"`
	FetchedAt string `json:"fetched_at"`
}

func (q *Queries) UpsertEconomicEvent(ctx context.Context, arg UpsertEconomicEventParams) error {
	_, err := q.db.ExecContext(ctx, upsertEconomicEvent,
		arg.Provider,
		arg.Title,
		arg.Country,
		arg.Impact,
		arg.EventTs,
		arg.Forecast,
		arg.Previous,
		arg.Actual,
		arg.FetchedAt,
	)
	return err
}
