// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: executions.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const deleteExecutionsForAccount = `-- name: DeleteExecutionsForAccount :exec
DELETE FROM executions WHERE account_id = ? AND user_id = ?
`

type DeleteExecutionsForAccountParams struct {
	AccountID string `json:"account_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) DeleteExecutionsForAccount(ctx context.Context, arg DeleteExecutionsForAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteExecutionsForAccount, arg.AccountID, arg.UserID)
	return err
}

const deleteExecutionsForBatch = `-- name: DeleteExecutionsForBatch :exec
DELETE FROM executions WHERE import_batch_id = ? AND user_id = ?
`

type DeleteExecutionsForBatchParams struct {
	ImportBatchID sql.NullString `json:"import_batch_id"`
	UserID        string         `json:"user_id"`
}

func (q *Queries) DeleteExecutionsForBatch(ctx context.Context, arg DeleteExecutionsForBatchParams) error {
	_, err := q.db.ExecContext(ctx, deleteExecutionsForBatch, arg.ImportBatchID, arg.UserID)
	return err
}

const executionExists = `-- name: ExecutionExists :one
SELECT EXISTS(SELECT 1 FROM executions WHERE account_id = ? AND dedup_hash = ?)
`

type ExecutionExistsParams struct {
	AccountID string `json:"account_id"`
	DedupHash string `json:"dedup_hash"`
}

func (q *Queries) ExecutionExists(ctx context.Context, arg ExecutionExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, executionExists, arg.AccountID, arg.DedupHash)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertExecution = `-- name: InsertExecution :one
INSERT INTO executions (id, user_id, account_id, external_id, symbol, instrument_type, side,
    quantity, price, fees, commission, executed_at, multiplier, details, import_batch_id, dedup_hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, user_id, account_id, external_id, symbol, instrument_type, side, quantity, price, fees, commission, executed_at, multiplier, details, import_batch_id, dedup_hash, created_at
`

type InsertExecutionParams struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	AccountID      string         `json:"account_id"`
	ExternalID     sql.NullString `json:"external_id"`
	Symbol         string         `json:"symbol"`
	InstrumentType string         `json:"instrument_type"`
	Side           string         `json:"side"`
	Quantity       float64        `json:"quantity"`
	Price          float64        `json:"price"`
	Fees           float64        `json:"fees"`
	Commission     float64        `json:"commission"`
	ExecutedAt     time.Time      `json:"executed_at"`
	Multiplier     float64        `json:"multiplier"`
	Details        sql.NullString `json:"details"`
	ImportBatchID  sql.NullString `json:"import_batch_id"`
	DedupHash      string         `json:"dedup_hash"`
}

func (q *Queries) InsertExecution(ctx context.Context, arg InsertExecutionParams) (Execution, error) {
	row := q.db.QueryRowContext(ctx, insertExecution,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.ExternalID,
		arg.Symbol,
		arg.InstrumentType,
		arg.Side,
		arg.Quantity,
		arg.Price,
		arg.Fees,
		arg.Commission,
		arg.ExecutedAt,
		arg.Multiplier,
		arg.Details,
		arg.ImportBatchID,
		arg.DedupHash,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ExternalID,
		&i.Symbol,
		&i.InstrumentType,
		&i.Side,
		&i.Quantity,
		&i.Price,
		&i.Fees,
		&i.Commission,
		&i.ExecutedAt,
		&i.Multiplier,
		&i.Details,
		&i.ImportBatchID,
		&i.DedupHash,
		&i.CreatedAt,
	)
	return i, err
}

const listExecutionsForAccount = `-- name: ListExecutionsForAccount :many
SELECT id, user_id, account_id, external_id, symbol, instrument_type, side, quantity, price, fees, commission, executed_at, multiplier, details, import_batch_id, dedup_hash, created_at FROM executions WHERE user_id = ? AND account_id = ? ORDER BY executed_at, id
`

type ListExecutionsForAccountParams struct {
	UserID    string `json:"user_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) ListExecutionsForAccount(ctx context.Context, arg ListExecutionsForAccountParams) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionsForAccount, arg.UserID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.ExternalID,
			&i.Symbol,
			&i.InstrumentType,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.Fees,
			&i.Commission,
			&i.ExecutedAt,
			&i.Multiplier,
			&i.Details,
			&i.ImportBatchID,
			&i.DedupHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
