// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flex_sync.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const deleteFlexSyncSettings = `-- name: DeleteFlexSyncSettings :execrows
DELETE FROM flex_sync_settings WHERE account_id = ? AND user_id = ?
`

type DeleteFlexSyncSettingsParams struct {
	AccountID string `json:"account_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) DeleteFlexSyncSettings(ctx context.Context, arg DeleteFlexSyncSettingsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFlexSyncSettings, arg.AccountID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFlexSyncSettings = `-- name: GetFlexSyncSettings :one
SELECT account_id, user_id, token, query_id, enabled, last_synced_at, last_status, last_error, updated_at FROM flex_sync_settings WHERE account_id = ? AND user_id = ?
`

type GetFlexSyncSettingsParams struct {
	AccountID string `json:"account_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetFlexSyncSettings(ctx context.Context, arg GetFlexSyncSettingsParams) (FlexSyncSetting, error) {
	row := q.db.QueryRowContext(ctx, getFlexSyncSettings, arg.AccountID, arg.UserID)
	var i FlexSyncSetting
	err := row.Scan(
		&i.AccountID,
		&i.UserID,
		&i.Token,
		&i.QueryID,
		&i.Enabled,
		&i.LastSyncedAt,
		&i.LastStatus,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledFlexSyncSettings = `-- name: ListEnabledFlexSyncSettings :many
SELECT account_id, user_id, token, query_id, enabled, last_synced_at, last_status, last_error, updated_at FROM flex_sync_settings WHERE enabled = 1 ORDER BY account_id
`

func (q *Queries) ListEnabledFlexSyncSettings(ctx context.Context) ([]FlexSyncSetting, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledFlexSyncSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlexSyncSetting
	for rows.Next() {
		var i FlexSyncSetting
		if err := rows.Scan(
			&i.AccountID,
			&i.UserID,
			&i.Token,
			&i.QueryID,
			&i.Enabled,
			&i.LastSyncedAt,
			&i.LastStatus,
			&i.LastError,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlexSyncSettingsForUser = `-- name: ListFlexSyncSettingsForUser :many
SELECT f.account_id, f.user_id, f.token, f.query_id, f.enabled, f.last_synced_at, f.last_status, f.last_error, f.updated_at, a.name AS account_name
FROM flex_sync_settings f
JOIN accounts a ON a.id = f.account_id
WHERE f.user_id = ?
ORDER BY a.name
`

type ListFlexSyncSettingsForUserRow struct {
	AccountID    string       `json:"account_id"`
	UserID       string       `json:"user_id"`
	Token        string       `json:"token"`
	QueryID      string       `json:"query_id"`
	Enabled      int64        `json:"enabled"`
	LastSyncedAt sql.NullTime `json:"last_synced_at"`
	LastStatus   string       `json:"last_status"`
	LastError    string       `json:"last_error"`
	UpdatedAt    time.Time    `json:"updated_at"`
	AccountName  string       `json:"account_name"`
}

func (q *Queries) ListFlexSyncSettingsForUser(ctx context.Context, userID string) ([]ListFlexSyncSettingsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listFlexSyncSettingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlexSyncSettingsForUserRow
	for rows.Next() {
		var i ListFlexSyncSettingsForUserRow
		if err := rows.Scan(
			&i.AccountID,
			&i.UserID,
			&i.Token,
			&i.QueryID,
			&i.Enabled,
			&i.LastSyncedAt,
			&i.LastStatus,
			&i.LastError,
			&i.UpdatedAt,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlexSyncStatus = `-- name: UpdateFlexSyncStatus :exec
UPDATE flex_sync_settings
SET last_synced_at = ?, last_status = ?, last_error = ?
WHERE account_id = ? AND user_id = ?
`

type UpdateFlexSyncStatusParams struct {
	LastSyncedAt sql.NullTime `json:"last_synced_at"`
	LastStatus   string       `json:"last_status"`
	LastError    string       `json:"last_error"`
	AccountID    string       `json:"account_id"`
	UserID       string       `json:"user_id"`
}

func (q *Queries) UpdateFlexSyncStatus(ctx context.Context, arg UpdateFlexSyncStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFlexSyncStatus,
		arg.LastSyncedAt,
		arg.LastStatus,
		arg.LastError,
		arg.AccountID,
		arg.UserID,
	)
	return err
}

const upsertFlexSyncSettings = `-- name: UpsertFlexSyncSettings :one
INSERT INTO flex_sync_settings (account_id, user_id, token, query_id, enabled, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(account_id) DO UPDATE SET
    token = excluded.token,
    query_id = excluded.query_id,
    enabled = excluded.enabled,
    updated_at = CURRENT_TIMESTAMP
RETURNING account_id, user_id, token, query_id, enabled, last_synced_at, last_status, last_error, updated_at
`

type UpsertFlexSyncSettingsParams struct {
	AccountID string `json:"account_id"`
	UserID    string `json:"user_id"`
	Token     string `json:"token"`
	QueryID   string `json:"query_id"`
	Enabled   int64  `json:"enabled"`
}

func (q *Queries) UpsertFlexSyncSettings(ctx context.Context, arg UpsertFlexSyncSettingsParams) (FlexSyncSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertFlexSyncSettings,
		arg.AccountID,
		arg.UserID,
		arg.Token,
		arg.QueryID,
		arg.Enabled,
	)
	var i FlexSyncSetting
	err := row.Scan(
		&i.AccountID,
		&i.UserID,
		&i.Token,
		&i.QueryID,
		&i.Enabled,
		&i.LastSyncedAt,
		&i.LastStatus,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}
