// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instrument_specs.sql

package store

import (
	"context"
)

const getInstrumentSpec = `-- name: GetInstrumentSpec :one
SELECT id, symbol_root, instrument_type, tick_size, tick_value, multiplier, currency FROM instrument_specs WHERE symbol_root = ? AND instrument_type = ?
`

type GetInstrumentSpecParams struct {
	SymbolRoot     string `json:"symbol_root"`
	InstrumentType string `json:"instrument_type"`
}

func (q *Queries) GetInstrumentSpec(ctx context.Context, arg GetInstrumentSpecParams) (InstrumentSpec, error) {
	row := q.db.QueryRowContext(ctx, getInstrumentSpec, arg.SymbolRoot, arg.InstrumentType)
	var i InstrumentSpec
	err := row.Scan(
		&i.ID,
		&i.SymbolRoot,
		&i.InstrumentType,
		&i.TickSize,
		&i.TickValue,
		&i.Multiplier,
		&i.Currency,
	)
	return i, err
}

const upsertInstrumentSpec = `-- name: UpsertInstrumentSpec :exec
INSERT INTO instrument_specs (id, symbol_root, instrument_type, tick_size, tick_value, multiplier, currency)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(symbol_root, instrument_type) DO UPDATE SET
    tick_size = excluded.tick_size, tick_value = excluded.tick_value,
    multiplier = excluded.multiplier, currency = excluded.currency
`

type UpsertInstrumentSpecParams struct {
	ID             string  `json:"id"`
	SymbolRoot     string  `json:"symbol_root"`
	InstrumentType string  `json:"instrument_type"`
	TickSize       float64 `json:"tick_size"`
	TickValue      float64 `json:"tick_value"`
	Multiplier     float64 `json:"multiplier"`
	Currency       string  `json:"currency"`
}

func (q *Queries) UpsertInstrumentSpec(ctx context.Context, arg UpsertInstrumentSpecParams) error {
	_, err := q.db.ExecContext(ctx, upsertInstrumentSpec,
		arg.ID,
		arg.SymbolRoot,
		arg.InstrumentType,
		arg.TickSize,
		arg.TickValue,
		arg.Multiplier,
		arg.Currency,
	)
	return err
}
