// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_notes.sql

package store

import (
	"context"
)

const createJournalNote = `-- name: CreateJournalNote :one
INSERT INTO journal_notes (id, user_id, occurred_at, title, body, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, occurred_at, title, body, created_at, updated_at
`

type CreateJournalNoteParams struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	OccurredAt string `json:"occurred_at"`
	Title      string `json:"title"`
	Body       string `json:"body"`
}

func (q *Queries) CreateJournalNote(ctx context.Context, arg CreateJournalNoteParams) (JournalNote, error) {
	row := q.db.QueryRowContext(ctx, createJournalNote,
		arg.ID,
		arg.UserID,
		arg.OccurredAt,
		arg.Title,
		arg.Body,
	)
	var i JournalNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OccurredAt,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJournalNote = `-- name: DeleteJournalNote :execrows
DELETE FROM journal_notes WHERE id = ? AND user_id = ?
`

type DeleteJournalNoteParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteJournalNote(ctx context.Context, arg DeleteJournalNoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteJournalNote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChecklistTemplate = `-- name: GetChecklistTemplate :one
SELECT user_id, items, updated_at FROM checklist_templates WHERE user_id = ?
`

func (q *Queries) GetChecklistTemplate(ctx context.Context, userID string) (ChecklistTemplate, error) {
	row := q.db.QueryRowContext(ctx, getChecklistTemplate, userID)
	var i ChecklistTemplate
	err := row.Scan(&i.UserID, &i.Items, &i.UpdatedAt)
	return i, err
}

const getJournalNote = `-- name: GetJournalNote :one
SELECT id, user_id, occurred_at, title, body, created_at, updated_at FROM journal_notes WHERE id = ? AND user_id = ?
`

type GetJournalNoteParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetJournalNote(ctx context.Context, arg GetJournalNoteParams) (JournalNote, error) {
	row := q.db.QueryRowContext(ctx, getJournalNote, arg.ID, arg.UserID)
	var i JournalNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OccurredAt,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJournalNotes = `-- name: ListJournalNotes :many
SELECT id, user_id, occurred_at, title, body, created_at, updated_at FROM journal_notes
WHERE user_id = ?
  AND (?2 IS NULL OR occurred_at >= ?2)
  AND (?3 IS NULL OR occurred_at <= ?3)
ORDER BY occurred_at DESC, created_at DESC
`

type ListJournalNotesParams struct {
	UserID   string      `json:"user_id"`
	FromDate interface{} `json:"from_date"`
	ToDate   interface{} `json:"to_date"`
}

func (q *Queries) ListJournalNotes(ctx context.Context, arg ListJournalNotesParams) ([]JournalNote, error) {
	rows, err := q.db.QueryContext(ctx, listJournalNotes, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalNote
	for rows.Next() {
		var i JournalNote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OccurredAt,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJournalNote = `-- name: UpdateJournalNote :one
UPDATE journal_notes
SET occurred_at = ?, title = ?, body = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, occurred_at, title, body, created_at, updated_at
`

type UpdateJournalNoteParams struct {
	OccurredAt string `json:"occurred_at"`
	Title      string `json:"title"`
	Body       string `json:"body"`
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) UpdateJournalNote(ctx context.Context, arg UpdateJournalNoteParams) (JournalNote, error) {
	row := q.db.QueryRowContext(ctx, updateJournalNote,
		arg.OccurredAt,
		arg.Title,
		arg.Body,
		arg.ID,
		arg.UserID,
	)
	var i JournalNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OccurredAt,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChecklistTemplate = `-- name: UpsertChecklistTemplate :one
INSERT INTO checklist_templates (user_id, items, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
    items = excluded.items,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, items, updated_at
`

type UpsertChecklistTemplateParams struct {
	UserID string `json:"user_id"`
	Items  string `json:"items"`
}

func (q *Queries) UpsertChecklistTemplate(ctx context.Context, arg UpsertChecklistTemplateParams) (ChecklistTemplate, error) {
	row := q.db.QueryRowContext(ctx, upsertChecklistTemplate, arg.UserID, arg.Items)
	var i ChecklistTemplate
	err := row.Scan(&i.UserID, &i.Items, &i.UpdatedAt)
	return i, err
}
