// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type Account struct {
	ID              string    `json:"id"`
	UserID          string    `json:"user_id"`
	Name            string    `json:"name"`
	Broker          string    `json:"broker"`
	AccountType     string    `json:"account_type"`
	BaseCurrency    string    `json:"base_currency"`
	StartingBalance float64   `json:"starting_balance"`
	CreatedAt       time.Time `json:"created_at"`
}

type CashTransaction struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	AccountID     string         `json:"account_id"`
	Type          string         `json:"type"`
	Amount        float64        `json:"amount"`
	Currency      string         `json:"currency"`
	OccurredAt    time.Time      `json:"occurred_at"`
	Note          string         `json:"note"`
	ImportBatchID sql.NullString `json:"import_batch_id"`
	CreatedAt     time.Time      `json:"created_at"`
	TradeID       sql.NullString `json:"trade_id"`
}

type ChecklistTemplate struct {
	UserID    string    `json:"user_id"`
	Items     string    `json:"items"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Execution struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	AccountID      string         `json:"account_id"`
	ExternalID     sql.NullString `json:"external_id"`
	Symbol         string         `json:"symbol"`
	InstrumentType string         `json:"instrument_type"`
	Side           string         `json:"side"`
	Quantity       float64        `json:"quantity"`
	Price          float64        `json:"price"`
	Fees           float64        `json:"fees"`
	Commission     float64        `json:"commission"`
	ExecutedAt     time.Time      `json:"executed_at"`
	Multiplier     float64        `json:"multiplier"`
	Details        sql.NullString `json:"details"`
	ImportBatchID  sql.NullString `json:"import_batch_id"`
	DedupHash      string         `json:"dedup_hash"`
	CreatedAt      time.Time      `json:"created_at"`
}

type ImportBatch struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	AccountID     string         `json:"account_id"`
	Source        string         `json:"source"`
	Filename      sql.NullString `json:"filename"`
	ColumnMapping sql.NullString `json:"column_mapping"`
	RowCount      int64          `json:"row_count"`
	Status        string         `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
}

type InstrumentSpec struct {
	ID             string  `json:"id"`
	SymbolRoot     string  `json:"symbol_root"`
	InstrumentType string  `json:"instrument_type"`
	TickSize       float64 `json:"tick_size"`
	TickValue      float64 `json:"tick_value"`
	Multiplier     float64 `json:"multiplier"`
	Currency       string  `json:"currency"`
}

type JournalNote struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	OccurredAt string    `json:"occurred_at"`
	Title      string    `json:"title"`
	Body       string    `json:"body"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type RiskRule struct {
	UserID                string          `json:"user_id"`
	MaxRiskPerTrade       sql.NullFloat64 `json:"max_risk_per_trade"`
	MaxDailyLoss          sql.NullFloat64 `json:"max_daily_loss"`
	MaxOpenRisk           sql.NullFloat64 `json:"max_open_risk"`
	DefaultAccountRiskPct sql.NullFloat64 `json:"default_account_risk_pct"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

type Setup struct {
	ID          string          `json:"id"`
	UserID      string          `json:"user_id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	CreatedAt   time.Time       `json:"created_at"`
	Thesis      string          `json:"thesis"`
	Symbol      string          `json:"symbol"`
	Direction   string          `json:"direction"`
	TargetPrice sql.NullFloat64 `json:"target_price"`
	StopPrice   sql.NullFloat64 `json:"stop_price"`
	Checklist   string          `json:"checklist"`
}

type Tag struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	Name        string `json:"name"`
	Color       string `json:"color"`
	Description string `json:"description"`
	Kind        string `json:"kind"`
}

type Trade struct {
	ID              string          `json:"id"`
	UserID          string          `json:"user_id"`
	AccountID       string          `json:"account_id"`
	Symbol          string          `json:"symbol"`
	InstrumentType  string          `json:"instrument_type"`
	Direction       string          `json:"direction"`
	Status          string          `json:"status"`
	OpenedAt        time.Time       `json:"opened_at"`
	ClosedAt        sql.NullTime    `json:"closed_at"`
	QtyOpened       float64         `json:"qty_opened"`
	AvgEntryPrice   float64         `json:"avg_entry_price"`
	AvgExitPrice    sql.NullFloat64 `json:"avg_exit_price"`
	GrossPnl        sql.NullFloat64 `json:"gross_pnl"`
	FeesTotal       float64         `json:"fees_total"`
	NetPnl          sql.NullFloat64 `json:"net_pnl"`
	PnlCurrency     string          `json:"pnl_currency"`
	ReturnPct       sql.NullFloat64 `json:"return_pct"`
	RMultiple       sql.NullFloat64 `json:"r_multiple"`
	TimeInTradeSecs sql.NullInt64   `json:"time_in_trade_secs"`
	Notes           string          `json:"notes"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	QtyRemaining    float64         `json:"qty_remaining"`
}

type TradeAttachment struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	TradeID     string    `json:"trade_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageKey  string    `json:"storage_key"`
	CreatedAt   time.Time `json:"created_at"`
}

type TradeExecution struct {
	TradeID     string `json:"trade_id"`
	ExecutionID string `json:"execution_id"`
}

type TradeJournal struct {
	TradeID        string          `json:"trade_id"`
	UserID         string          `json:"user_id"`
	Notes          string          `json:"notes"`
	SetupID        sql.NullString  `json:"setup_id"`
	InitialRisk    sql.NullFloat64 `json:"initial_risk"`
	UpdatedAt      time.Time       `json:"updated_at"`
	TargetPrice    sql.NullFloat64 `json:"target_price"`
	StopPrice      sql.NullFloat64 `json:"stop_price"`
	EmotionalState string          `json:"emotional_state"`
	Confidence     sql.NullInt64   `json:"confidence"`
	TradeQuality   sql.NullInt64   `json:"trade_quality"`
	Mae            sql.NullFloat64 `json:"mae"`
	Mfe            sql.NullFloat64 `json:"mfe"`
}

type TradeTag struct {
	TradeID string `json:"trade_id"`
	TagID   string `json:"tag_id"`
}

type User struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	TotpSecret   sql.NullString `json:"totp_secret"`
	CreatedAt    time.Time      `json:"created_at"`
}
