// Code generated by scripts/gen_pg_adapter.py; DO NOT EDIT.
package store

import (
	"context"
	"database/sql"

	"github.com/tradermemos/api/internal/storepg"
)

// PG adapts storepg.Queries to the store.Querier interface.
// db is the same handle storepg holds, kept for the hand-written set-at-a-time
// statements in bulk.go that sqlc cannot express.
type PG struct {
	q  *storepg.Queries
	db DBTX
}

// NewPG wraps a Postgres sqlc Queries as store.Querier.
func NewPG(conn *sql.DB) *PG {
	return NewPGFromDBTX(conn)
}

// NewPGFromDBTX wraps any Postgres handle — a *sql.DB or an open *sql.Tx.
func NewPGFromDBTX(db DBTX) *PG {
	return &PG{q: storepg.New(db), db: db}
}

var _ Querier = (*PG)(nil)

func (p *PG) ClearTradeExecutions(ctx context.Context, tradeID string) error {
	return p.q.ClearTradeExecutions(ctx, tradeID)
}

func (p *PG) ClearTradeSetups(ctx context.Context, tradeID string) error {
	return p.q.ClearTradeSetups(ctx, tradeID)
}

func (p *PG) ClearTradeTags(ctx context.Context, tradeID string) error {
	return p.q.ClearTradeTags(ctx, tradeID)
}

func (p *PG) CountAdmins(ctx context.Context) (int64, error) {
	return p.q.CountAdmins(ctx)
}

func (p *PG) CountUsers(ctx context.Context) (int64, error) {
	return p.q.CountUsers(ctx)
}

func (p *PG) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error) {
	v, err := p.q.CreateAccessToken(ctx, storepg.CreateAccessTokenParams(arg))
	if err != nil {
		return AccessToken{}, err
	}
	return AccessToken(v), nil
}

func (p *PG) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	v, err := p.q.CreateAccount(ctx, storepg.CreateAccountParams(arg))
	if err != nil {
		return Account{}, err
	}
	return Account(v), nil
}

func (p *PG) CreateCoachReview(ctx context.Context, arg CreateCoachReviewParams) (CoachReview, error) {
	v, err := p.q.CreateCoachReview(ctx, storepg.CreateCoachReviewParams(arg))
	if err != nil {
		return CoachReview{}, err
	}
	return CoachReview(v), nil
}

func (p *PG) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	v, err := p.q.CreateImportBatch(ctx, storepg.CreateImportBatchParams(arg))
	if err != nil {
		return ImportBatch{}, err
	}
	return ImportBatch(v), nil
}

func (p *PG) CreateJournalNote(ctx context.Context, arg CreateJournalNoteParams) (JournalNote, error) {
	v, err := p.q.CreateJournalNote(ctx, storepg.CreateJournalNoteParams(arg))
	if err != nil {
		return JournalNote{}, err
	}
	return JournalNote(v), nil
}

func (p *PG) CreateSetup(ctx context.Context, arg CreateSetupParams) (Setup, error) {
	v, err := p.q.CreateSetup(ctx, storepg.CreateSetupParams(arg))
	if err != nil {
		return Setup{}, err
	}
	return Setup(v), nil
}

func (p *PG) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error) {
	v, err := p.q.CreateShareLink(ctx, storepg.CreateShareLinkParams(arg))
	if err != nil {
		return ShareLink{}, err
	}
	return ShareLink(v), nil
}

func (p *PG) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	v, err := p.q.CreateTag(ctx, storepg.CreateTagParams(arg))
	if err != nil {
		return Tag{}, err
	}
	return Tag(v), nil
}

func (p *PG) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	v, err := p.q.CreateUser(ctx, storepg.CreateUserParams(arg))
	if err != nil {
		return User{}, err
	}
	return User(v), nil
}

func (p *PG) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	return p.q.DeleteAccount(ctx, storepg.DeleteAccountParams(arg))
}

func (p *PG) DeleteAlertChannel(ctx context.Context, arg DeleteAlertChannelParams) (int64, error) {
	return p.q.DeleteAlertChannel(ctx, storepg.DeleteAlertChannelParams(arg))
}

func (p *PG) DeleteAlertChannelByTarget(ctx context.Context, arg DeleteAlertChannelByTargetParams) (int64, error) {
	return p.q.DeleteAlertChannelByTarget(ctx, storepg.DeleteAlertChannelByTargetParams(arg))
}

func (p *PG) DeleteAnnualGoal(ctx context.Context, arg DeleteAnnualGoalParams) (int64, error) {
	return p.q.DeleteAnnualGoal(ctx, storepg.DeleteAnnualGoalParams(arg))
}

func (p *PG) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (int64, error) {
	return p.q.DeleteAttachment(ctx, storepg.DeleteAttachmentParams(arg))
}

func (p *PG) DeleteCashTransaction(ctx context.Context, arg DeleteCashTransactionParams) (int64, error) {
	return p.q.DeleteCashTransaction(ctx, storepg.DeleteCashTransactionParams(arg))
}

func (p *PG) DeleteCoachReview(ctx context.Context, arg DeleteCoachReviewParams) (int64, error) {
	return p.q.DeleteCoachReview(ctx, storepg.DeleteCoachReviewParams(arg))
}

func (p *PG) DeleteExecution(ctx context.Context, arg DeleteExecutionParams) (int64, error) {
	return p.q.DeleteExecution(ctx, storepg.DeleteExecutionParams(arg))
}

func (p *PG) DeleteExecutionsForAccount(ctx context.Context, arg DeleteExecutionsForAccountParams) error {
	return p.q.DeleteExecutionsForAccount(ctx, storepg.DeleteExecutionsForAccountParams(arg))
}

func (p *PG) DeleteExecutionsForBatch(ctx context.Context, arg DeleteExecutionsForBatchParams) error {
	return p.q.DeleteExecutionsForBatch(ctx, storepg.DeleteExecutionsForBatchParams(arg))
}

func (p *PG) DeleteExecutionsForTrade(ctx context.Context, arg DeleteExecutionsForTradeParams) error {
	return p.q.DeleteExecutionsForTrade(ctx, storepg.DeleteExecutionsForTradeParams(arg))
}

func (p *PG) DeleteFlexSyncSettings(ctx context.Context, arg DeleteFlexSyncSettingsParams) (int64, error) {
	return p.q.DeleteFlexSyncSettings(ctx, storepg.DeleteFlexSyncSettingsParams(arg))
}

func (p *PG) DeleteFutureEconomicEvents(ctx context.Context, arg DeleteFutureEconomicEventsParams) error {
	return p.q.DeleteFutureEconomicEvents(ctx, storepg.DeleteFutureEconomicEventsParams(arg))
}

func (p *PG) DeleteJournalNote(ctx context.Context, arg DeleteJournalNoteParams) (int64, error) {
	return p.q.DeleteJournalNote(ctx, storepg.DeleteJournalNoteParams(arg))
}

func (p *PG) DeleteMediaFile(ctx context.Context, arg DeleteMediaFileParams) (int64, error) {
	return p.q.DeleteMediaFile(ctx, storepg.DeleteMediaFileParams(arg))
}

func (p *PG) DeletePropSettings(ctx context.Context, arg DeletePropSettingsParams) error {
	return p.q.DeletePropSettings(ctx, storepg.DeletePropSettingsParams(arg))
}

func (p *PG) DeleteSetup(ctx context.Context, arg DeleteSetupParams) (int64, error) {
	return p.q.DeleteSetup(ctx, storepg.DeleteSetupParams(arg))
}

func (p *PG) DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error) {
	return p.q.DeleteTag(ctx, storepg.DeleteTagParams(arg))
}

func (p *PG) DeleteTrade(ctx context.Context, arg DeleteTradeParams) (int64, error) {
	return p.q.DeleteTrade(ctx, storepg.DeleteTradeParams(arg))
}

func (p *PG) DeleteTradesForAccount(ctx context.Context, arg DeleteTradesForAccountParams) error {
	return p.q.DeleteTradesForAccount(ctx, storepg.DeleteTradesForAccountParams(arg))
}

func (p *PG) DeleteTradesNotInAccount(ctx context.Context, arg DeleteTradesNotInAccountParams) error {
	return p.q.DeleteTradesNotInAccount(ctx, storepg.DeleteTradesNotInAccountParams(arg))
}

func (p *PG) DeleteUser(ctx context.Context, id string) (int64, error) {
	return p.q.DeleteUser(ctx, id)
}

func (p *PG) DisableAlertChannel(ctx context.Context, id string) error {
	return p.q.DisableAlertChannel(ctx, id)
}

func (p *PG) ExecutionExists(ctx context.Context, arg ExecutionExistsParams) (int64, error) {
	return p.q.ExecutionExists(ctx, storepg.ExecutionExistsParams(arg))
}

func (p *PG) GetAccessTokenByHash(ctx context.Context, tokenHash string) (AccessToken, error) {
	v, err := p.q.GetAccessTokenByHash(ctx, tokenHash)
	if err != nil {
		return AccessToken{}, err
	}
	return AccessToken(v), nil
}

func (p *PG) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	v, err := p.q.GetAccount(ctx, storepg.GetAccountParams(arg))
	if err != nil {
		return Account{}, err
	}
	return Account(v), nil
}

func (p *PG) GetAccountByIDAny(ctx context.Context, id string) (Account, error) {
	v, err := p.q.GetAccountByIDAny(ctx, id)
	if err != nil {
		return Account{}, err
	}
	return Account(v), nil
}

func (p *PG) GetAlertChannel(ctx context.Context, arg GetAlertChannelParams) (AlertChannel, error) {
	v, err := p.q.GetAlertChannel(ctx, storepg.GetAlertChannelParams(arg))
	if err != nil {
		return AlertChannel{}, err
	}
	return AlertChannel(v), nil
}

func (p *PG) GetAlertSettings(ctx context.Context, userID string) (AlertSetting, error) {
	v, err := p.q.GetAlertSettings(ctx, userID)
	if err != nil {
		return AlertSetting{}, err
	}
	return AlertSetting(v), nil
}

func (p *PG) GetAnnualGoal(ctx context.Context, arg GetAnnualGoalParams) (AnnualGoal, error) {
	v, err := p.q.GetAnnualGoal(ctx, storepg.GetAnnualGoalParams(arg))
	if err != nil {
		return AnnualGoal{}, err
	}
	return AnnualGoal(v), nil
}

func (p *PG) GetAttachment(ctx context.Context, arg GetAttachmentParams) (TradeAttachment, error) {
	v, err := p.q.GetAttachment(ctx, storepg.GetAttachmentParams(arg))
	if err != nil {
		return TradeAttachment{}, err
	}
	return TradeAttachment(v), nil
}

func (p *PG) GetChecklistTemplate(ctx context.Context, userID string) (ChecklistTemplate, error) {
	v, err := p.q.GetChecklistTemplate(ctx, userID)
	if err != nil {
		return ChecklistTemplate{}, err
	}
	return ChecklistTemplate(v), nil
}

func (p *PG) GetCoachSettings(ctx context.Context) (CoachSetting, error) {
	v, err := p.q.GetCoachSettings(ctx)
	if err != nil {
		return CoachSetting{}, err
	}
	return CoachSetting(v), nil
}

func (p *PG) GetEconomicEventsLastFetch(ctx context.Context, provider string) (string, error) {
	return p.q.GetEconomicEventsLastFetch(ctx, provider)
}

func (p *PG) GetExecution(ctx context.Context, arg GetExecutionParams) (Execution, error) {
	v, err := p.q.GetExecution(ctx, storepg.GetExecutionParams(arg))
	if err != nil {
		return Execution{}, err
	}
	return Execution(v), nil
}

func (p *PG) GetExecutionByDedup(ctx context.Context, arg GetExecutionByDedupParams) (Execution, error) {
	v, err := p.q.GetExecutionByDedup(ctx, storepg.GetExecutionByDedupParams(arg))
	if err != nil {
		return Execution{}, err
	}
	return Execution(v), nil
}

func (p *PG) GetFlexSyncSettings(ctx context.Context, arg GetFlexSyncSettingsParams) (FlexSyncSetting, error) {
	v, err := p.q.GetFlexSyncSettings(ctx, storepg.GetFlexSyncSettingsParams(arg))
	if err != nil {
		return FlexSyncSetting{}, err
	}
	return FlexSyncSetting(v), nil
}

func (p *PG) GetImportBatch(ctx context.Context, arg GetImportBatchParams) (ImportBatch, error) {
	v, err := p.q.GetImportBatch(ctx, storepg.GetImportBatchParams(arg))
	if err != nil {
		return ImportBatch{}, err
	}
	return ImportBatch(v), nil
}

func (p *PG) GetInstrumentSpec(ctx context.Context, arg GetInstrumentSpecParams) (InstrumentSpec, error) {
	v, err := p.q.GetInstrumentSpec(ctx, storepg.GetInstrumentSpecParams(arg))
	if err != nil {
		return InstrumentSpec{}, err
	}
	return InstrumentSpec(v), nil
}

func (p *PG) GetJournalNote(ctx context.Context, arg GetJournalNoteParams) (JournalNote, error) {
	v, err := p.q.GetJournalNote(ctx, storepg.GetJournalNoteParams(arg))
	if err != nil {
		return JournalNote{}, err
	}
	return JournalNote(v), nil
}

func (p *PG) GetMarketBarsCache(ctx context.Context, cacheKey string) (MarketBarsCache, error) {
	v, err := p.q.GetMarketBarsCache(ctx, cacheKey)
	if err != nil {
		return MarketBarsCache{}, err
	}
	return MarketBarsCache(v), nil
}

func (p *PG) GetMediaFile(ctx context.Context, arg GetMediaFileParams) (MediaFile, error) {
	v, err := p.q.GetMediaFile(ctx, storepg.GetMediaFileParams(arg))
	if err != nil {
		return MediaFile{}, err
	}
	return MediaFile(v), nil
}

func (p *PG) GetOcrSettings(ctx context.Context) (GetOcrSettingsRow, error) {
	v, err := p.q.GetOcrSettings(ctx)
	if err != nil {
		return GetOcrSettingsRow{}, err
	}
	return GetOcrSettingsRow(v), nil
}

func (p *PG) GetPropSettings(ctx context.Context, arg GetPropSettingsParams) (PropSetting, error) {
	v, err := p.q.GetPropSettings(ctx, storepg.GetPropSettingsParams(arg))
	if err != nil {
		return PropSetting{}, err
	}
	return PropSetting(v), nil
}

func (p *PG) GetRiskRules(ctx context.Context, userID string) (RiskRule, error) {
	v, err := p.q.GetRiskRules(ctx, userID)
	if err != nil {
		return RiskRule{}, err
	}
	return RiskRule(v), nil
}

func (p *PG) GetSetup(ctx context.Context, arg GetSetupParams) (Setup, error) {
	v, err := p.q.GetSetup(ctx, storepg.GetSetupParams(arg))
	if err != nil {
		return Setup{}, err
	}
	return Setup(v), nil
}

func (p *PG) GetShareLinkByToken(ctx context.Context, token string) (ShareLink, error) {
	v, err := p.q.GetShareLinkByToken(ctx, token)
	if err != nil {
		return ShareLink{}, err
	}
	return ShareLink(v), nil
}

func (p *PG) GetTrade(ctx context.Context, arg GetTradeParams) (Trade, error) {
	v, err := p.q.GetTrade(ctx, storepg.GetTradeParams(arg))
	if err != nil {
		return Trade{}, err
	}
	return Trade(v), nil
}

func (p *PG) GetTradeIDForExecution(ctx context.Context, executionID string) (string, error) {
	return p.q.GetTradeIDForExecution(ctx, executionID)
}

func (p *PG) GetTradeJournal(ctx context.Context, arg GetTradeJournalParams) (TradeJournal, error) {
	v, err := p.q.GetTradeJournal(ctx, storepg.GetTradeJournalParams(arg))
	if err != nil {
		return TradeJournal{}, err
	}
	return TradeJournal(v), nil
}

func (p *PG) GetUserByEmail(ctx context.Context, email string) (User, error) {
	v, err := p.q.GetUserByEmail(ctx, email)
	if err != nil {
		return User{}, err
	}
	return User(v), nil
}

func (p *PG) GetUserByID(ctx context.Context, id string) (User, error) {
	v, err := p.q.GetUserByID(ctx, id)
	if err != nil {
		return User{}, err
	}
	return User(v), nil
}

func (p *PG) GetUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	v, err := p.q.GetUserPreferences(ctx, userID)
	if err != nil {
		return UserPreference{}, err
	}
	return UserPreference(v), nil
}

func (p *PG) IncrementShareLinkViews(ctx context.Context, id string) error {
	return p.q.IncrementShareLinkViews(ctx, id)
}

func (p *PG) InsertAlertEvent(ctx context.Context, arg InsertAlertEventParams) (int64, error) {
	return p.q.InsertAlertEvent(ctx, storepg.InsertAlertEventParams(arg))
}

func (p *PG) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (TradeAttachment, error) {
	v, err := p.q.InsertAttachment(ctx, storepg.InsertAttachmentParams(arg))
	if err != nil {
		return TradeAttachment{}, err
	}
	return TradeAttachment(v), nil
}

func (p *PG) InsertCashTransaction(ctx context.Context, arg InsertCashTransactionParams) (CashTransaction, error) {
	v, err := p.q.InsertCashTransaction(ctx, storepg.InsertCashTransactionParams(arg))
	if err != nil {
		return CashTransaction{}, err
	}
	return CashTransaction(v), nil
}

func (p *PG) InsertExecution(ctx context.Context, arg InsertExecutionParams) (Execution, error) {
	v, err := p.q.InsertExecution(ctx, storepg.InsertExecutionParams(arg))
	if err != nil {
		return Execution{}, err
	}
	return Execution(v), nil
}

func (p *PG) InsertMediaFile(ctx context.Context, arg InsertMediaFileParams) (MediaFile, error) {
	v, err := p.q.InsertMediaFile(ctx, storepg.InsertMediaFileParams(arg))
	if err != nil {
		return MediaFile{}, err
	}
	return MediaFile(v), nil
}

func (p *PG) InsertTrade(ctx context.Context, arg InsertTradeParams) (Trade, error) {
	v, err := p.q.InsertTrade(ctx, storepg.InsertTradeParams(arg))
	if err != nil {
		return Trade{}, err
	}
	return Trade(v), nil
}

func (p *PG) LatestAccessTokenUse(ctx context.Context, tokenID string) (AccessTokenUse, error) {
	v, err := p.q.LatestAccessTokenUse(ctx, tokenID)
	if err != nil {
		return AccessTokenUse{}, err
	}
	return AccessTokenUse(v), nil
}

func (p *PG) LinkTradeExecution(ctx context.Context, arg LinkTradeExecutionParams) error {
	return p.q.LinkTradeExecution(ctx, storepg.LinkTradeExecutionParams(arg))
}

func (p *PG) ListAccessTokenUses(ctx context.Context, arg ListAccessTokenUsesParams) ([]AccessTokenUse, error) {
	v, err := p.q.ListAccessTokenUses(ctx, storepg.ListAccessTokenUsesParams{
		TokenID: arg.TokenID,
		UserID: arg.UserID,
		Limit: int32(arg.Limit),
	})
	if err != nil {
		return nil, err
	}
	return func() []AccessTokenUse { in := v; out := make([]AccessTokenUse, len(in)); for i := range in { out[i] = AccessTokenUse(in[i]) }; return out }(), nil
}

func (p *PG) ListAccessTokensByUser(ctx context.Context, userID string) ([]AccessToken, error) {
	v, err := p.q.ListAccessTokensByUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []AccessToken { in := v; out := make([]AccessToken, len(in)); for i := range in { out[i] = AccessToken(in[i]) }; return out }(), nil
}

func (p *PG) ListAccounts(ctx context.Context, userID string) ([]Account, error) {
	v, err := p.q.ListAccounts(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []Account { in := v; out := make([]Account, len(in)); for i := range in { out[i] = Account(in[i]) }; return out }(), nil
}

func (p *PG) ListAlertChannels(ctx context.Context, userID string) ([]AlertChannel, error) {
	v, err := p.q.ListAlertChannels(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []AlertChannel { in := v; out := make([]AlertChannel, len(in)); for i := range in { out[i] = AlertChannel(in[i]) }; return out }(), nil
}

func (p *PG) ListAlertEvents(ctx context.Context, arg ListAlertEventsParams) ([]AlertEvent, error) {
	v, err := p.q.ListAlertEvents(ctx, storepg.ListAlertEventsParams{
		UserID: arg.UserID,
		Limit: int32(arg.Limit),
	})
	if err != nil {
		return nil, err
	}
	return func() []AlertEvent { in := v; out := make([]AlertEvent, len(in)); for i := range in { out[i] = AlertEvent(in[i]) }; return out }(), nil
}

func (p *PG) ListAttachmentsForAccount(ctx context.Context, arg ListAttachmentsForAccountParams) ([]TradeAttachment, error) {
	v, err := p.q.ListAttachmentsForAccount(ctx, storepg.ListAttachmentsForAccountParams(arg))
	if err != nil {
		return nil, err
	}
	return func() []TradeAttachment { in := v; out := make([]TradeAttachment, len(in)); for i := range in { out[i] = TradeAttachment(in[i]) }; return out }(), nil
}

func (p *PG) ListAttachmentsForTrade(ctx context.Context, arg ListAttachmentsForTradeParams) ([]TradeAttachment, error) {
	v, err := p.q.ListAttachmentsForTrade(ctx, storepg.ListAttachmentsForTradeParams(arg))
	if err != nil {
		return nil, err
	}
	return func() []TradeAttachment { in := v; out := make([]TradeAttachment, len(in)); for i := range in { out[i] = TradeAttachment(in[i]) }; return out }(), nil
}

func (p *PG) ListCashForTrade(ctx context.Context, arg ListCashForTradeParams) ([]CashTransaction, error) {
	v, err := p.q.ListCashForTrade(ctx, storepg.ListCashForTradeParams(arg))
	if err != nil {
		return nil, err
	}
	return func() []CashTransaction { in := v; out := make([]CashTransaction, len(in)); for i := range in { out[i] = CashTransaction(in[i]) }; return out }(), nil
}

func (p *PG) ListCashTransactions(ctx context.Context, arg ListCashTransactionsParams) ([]CashTransaction, error) {
	v, err := p.q.ListCashTransactions(ctx, storepg.ListCashTransactionsParams{
		UserID: arg.UserID,
		AccountID: ifaceToNullString(arg.AccountID),
	})
	if err != nil {
		return nil, err
	}
	return func() []CashTransaction { in := v; out := make([]CashTransaction, len(in)); for i := range in { out[i] = CashTransaction(in[i]) }; return out }(), nil
}

func (p *PG) ListClosedTrades(ctx context.Context, arg ListClosedTradesParams) ([]Trade, error) {
	v, err := p.q.ListClosedTrades(ctx, storepg.ListClosedTradesParams{
		UserID: arg.UserID,
		AccountID: ifaceToNullString(arg.AccountID),
		From: ifaceToNullTime(arg.From),
		To: ifaceToNullTime(arg.To),
	})
	if err != nil {
		return nil, err
	}
	return func() []Trade { in := v; out := make([]Trade, len(in)); for i := range in { out[i] = Trade(in[i]) }; return out }(), nil
}

func (p *PG) ListCoachReviews(ctx context.Context, arg ListCoachReviewsParams) ([]CoachReview, error) {
	v, err := p.q.ListCoachReviews(ctx, storepg.ListCoachReviewsParams{
		UserID: arg.UserID,
		TradeID: arg.TradeID,
		Limit: int32(arg.Limit),
	})
	if err != nil {
		return nil, err
	}
	return func() []CoachReview { in := v; out := make([]CoachReview, len(in)); for i := range in { out[i] = CoachReview(in[i]) }; return out }(), nil
}

func (p *PG) ListEconomicEvents(ctx context.Context, arg ListEconomicEventsParams) ([]EconomicEvent, error) {
	v, err := p.q.ListEconomicEvents(ctx, storepg.ListEconomicEventsParams(arg))
	if err != nil {
		return nil, err
	}
	return func() []EconomicEvent { in := v; out := make([]EconomicEvent, len(in)); for i := range in { out[i] = EconomicEvent(in[i]) }; return out }(), nil
}

func (p *PG) ListEnabledAlertChannels(ctx context.Context, userID string) ([]AlertChannel, error) {
	v, err := p.q.ListEnabledAlertChannels(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []AlertChannel { in := v; out := make([]AlertChannel, len(in)); for i := range in { out[i] = AlertChannel(in[i]) }; return out }(), nil
}

func (p *PG) ListEnabledAlertSettings(ctx context.Context) ([]AlertSetting, error) {
	v, err := p.q.ListEnabledAlertSettings(ctx)
	if err != nil {
		return nil, err
	}
	return func() []AlertSetting { in := v; out := make([]AlertSetting, len(in)); for i := range in { out[i] = AlertSetting(in[i]) }; return out }(), nil
}

func (p *PG) ListEnabledFlexSyncSettings(ctx context.Context) ([]FlexSyncSetting, error) {
	v, err := p.q.ListEnabledFlexSyncSettings(ctx)
	if err != nil {
		return nil, err
	}
	return func() []FlexSyncSetting { in := v; out := make([]FlexSyncSetting, len(in)); for i := range in { out[i] = FlexSyncSetting(in[i]) }; return out }(), nil
}

func (p *PG) ListExecutionsForAccount(ctx context.Context, arg ListExecutionsForAccountParams) ([]Execution, error) {
	v, err := p.q.ListExecutionsForAccount(ctx, storepg.ListExecutionsForAccountParams(arg))
	if err != nil {
		return nil, err
	}
	return func() []Execution { in := v; out := make([]Execution, len(in)); for i := range in { out[i] = Execution(in[i]) }; return out }(), nil
}

func (p *PG) ListExecutionsForTrade(ctx context.Context, tradeID string) ([]Execution, error) {
	v, err := p.q.ListExecutionsForTrade(ctx, tradeID)
	if err != nil {
		return nil, err
	}
	return func() []Execution { in := v; out := make([]Execution, len(in)); for i := range in { out[i] = Execution(in[i]) }; return out }(), nil
}

func (p *PG) ListImportBatches(ctx context.Context, userID string) ([]ImportBatch, error) {
	v, err := p.q.ListImportBatches(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []ImportBatch { in := v; out := make([]ImportBatch, len(in)); for i := range in { out[i] = ImportBatch(in[i]) }; return out }(), nil
}

func (p *PG) ListJournalNotes(ctx context.Context, arg ListJournalNotesParams) ([]JournalNote, error) {
	v, err := p.q.ListJournalNotes(ctx, storepg.ListJournalNotesParams{
		UserID: arg.UserID,
		FromDate: ifaceToNullString(arg.FromDate),
		ToDate: ifaceToNullString(arg.ToDate),
	})
	if err != nil {
		return nil, err
	}
	return func() []JournalNote { in := v; out := make([]JournalNote, len(in)); for i := range in { out[i] = JournalNote(in[i]) }; return out }(), nil
}

func (p *PG) ListJournalRisks(ctx context.Context, userID string) ([]ListJournalRisksRow, error) {
	v, err := p.q.ListJournalRisks(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []ListJournalRisksRow { in := v; out := make([]ListJournalRisksRow, len(in)); for i := range in { out[i] = ListJournalRisksRow(in[i]) }; return out }(), nil
}

func (p *PG) ListMediaFilesForUser(ctx context.Context, userID string) ([]MediaFile, error) {
	v, err := p.q.ListMediaFilesForUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []MediaFile { in := v; out := make([]MediaFile, len(in)); for i := range in { out[i] = MediaFile(in[i]) }; return out }(), nil
}

func (p *PG) ListOptionExecutionDetailsForUser(ctx context.Context, userID string) ([]ListOptionExecutionDetailsForUserRow, error) {
	v, err := p.q.ListOptionExecutionDetailsForUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []ListOptionExecutionDetailsForUserRow { in := v; out := make([]ListOptionExecutionDetailsForUserRow, len(in)); for i := range in { out[i] = ListOptionExecutionDetailsForUserRow(in[i]) }; return out }(), nil
}

func (p *PG) ListPropSettingsForUser(ctx context.Context, userID string) ([]PropSetting, error) {
	v, err := p.q.ListPropSettingsForUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []PropSetting { in := v; out := make([]PropSetting, len(in)); for i := range in { out[i] = PropSetting(in[i]) }; return out }(), nil
}

func (p *PG) ListSetups(ctx context.Context, userID string) ([]Setup, error) {
	v, err := p.q.ListSetups(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []Setup { in := v; out := make([]Setup, len(in)); for i := range in { out[i] = Setup(in[i]) }; return out }(), nil
}

func (p *PG) ListSetupsForTrade(ctx context.Context, tradeID string) ([]Setup, error) {
	v, err := p.q.ListSetupsForTrade(ctx, tradeID)
	if err != nil {
		return nil, err
	}
	return func() []Setup { in := v; out := make([]Setup, len(in)); for i := range in { out[i] = Setup(in[i]) }; return out }(), nil
}

func (p *PG) ListShareLinksByUser(ctx context.Context, userID string) ([]ShareLink, error) {
	v, err := p.q.ListShareLinksByUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []ShareLink { in := v; out := make([]ShareLink, len(in)); for i := range in { out[i] = ShareLink(in[i]) }; return out }(), nil
}

func (p *PG) ListTags(ctx context.Context, userID string) ([]Tag, error) {
	v, err := p.q.ListTags(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []Tag { in := v; out := make([]Tag, len(in)); for i := range in { out[i] = Tag(in[i]) }; return out }(), nil
}

func (p *PG) ListTagsForTrade(ctx context.Context, tradeID string) ([]Tag, error) {
	v, err := p.q.ListTagsForTrade(ctx, tradeID)
	if err != nil {
		return nil, err
	}
	return func() []Tag { in := v; out := make([]Tag, len(in)); for i := range in { out[i] = Tag(in[i]) }; return out }(), nil
}

func (p *PG) ListTradeJournalsForUser(ctx context.Context, userID string) ([]TradeJournal, error) {
	v, err := p.q.ListTradeJournalsForUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []TradeJournal { in := v; out := make([]TradeJournal, len(in)); for i := range in { out[i] = TradeJournal(in[i]) }; return out }(), nil
}

func (p *PG) ListTradeTagsForUser(ctx context.Context, userID string) ([]ListTradeTagsForUserRow, error) {
	v, err := p.q.ListTradeTagsForUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	return func() []ListTradeTagsForUserRow { in := v; out := make([]ListTradeTagsForUserRow, len(in)); for i := range in { out[i] = ListTradeTagsForUserRow(in[i]) }; return out }(), nil
}

func (p *PG) ListTrades(ctx context.Context, arg ListTradesParams) ([]Trade, error) {
	v, err := p.q.ListTrades(ctx, storepg.ListTradesParams{
		UserID: arg.UserID,
		AccountID: ifaceToNullString(arg.AccountID),
		Status: ifaceToNullString(arg.Status),
	})
	if err != nil {
		return nil, err
	}
	return func() []Trade { in := v; out := make([]Trade, len(in)); for i := range in { out[i] = Trade(in[i]) }; return out }(), nil
}

func (p *PG) ListTradesMissingExcursion(ctx context.Context, arg ListTradesMissingExcursionParams) ([]Trade, error) {
	v, err := p.q.ListTradesMissingExcursion(ctx, storepg.ListTradesMissingExcursionParams{
		PostCutoff: arg.PostCutoff,
		PostFloor: arg.PostFloor,
		RowLimit: int32(arg.RowLimit),
	})
	if err != nil {
		return nil, err
	}
	return func() []Trade { in := v; out := make([]Trade, len(in)); for i := range in { out[i] = Trade(in[i]) }; return out }(), nil
}

func (p *PG) ListUsers(ctx context.Context) ([]User, error) {
	v, err := p.q.ListUsers(ctx)
	if err != nil {
		return nil, err
	}
	return func() []User { in := v; out := make([]User, len(in)); for i := range in { out[i] = User(in[i]) }; return out }(), nil
}

func (p *PG) PruneAccessTokenUses(ctx context.Context, arg PruneAccessTokenUsesParams) error {
	return p.q.PruneAccessTokenUses(ctx, storepg.PruneAccessTokenUsesParams{
		TokenID: arg.TokenID,
		TokenID_2: arg.TokenID_2,
		Limit: int32(arg.Limit),
	})
}

func (p *PG) RecordAccessTokenUse(ctx context.Context, arg RecordAccessTokenUseParams) error {
	return p.q.RecordAccessTokenUse(ctx, storepg.RecordAccessTokenUseParams(arg))
}

func (p *PG) RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) (int64, error) {
	return p.q.RevokeAccessToken(ctx, storepg.RevokeAccessTokenParams(arg))
}

func (p *PG) RevokeShareLink(ctx context.Context, arg RevokeShareLinkParams) (int64, error) {
	return p.q.RevokeShareLink(ctx, storepg.RevokeShareLinkParams(arg))
}

func (p *PG) SetAlertChannelEnabled(ctx context.Context, arg SetAlertChannelEnabledParams) (AlertChannel, error) {
	v, err := p.q.SetAlertChannelEnabled(ctx, storepg.SetAlertChannelEnabledParams(arg))
	if err != nil {
		return AlertChannel{}, err
	}
	return AlertChannel(v), nil
}

func (p *PG) SetImportBatchStatus(ctx context.Context, arg SetImportBatchStatusParams) error {
	return p.q.SetImportBatchStatus(ctx, storepg.SetImportBatchStatusParams(arg))
}

func (p *PG) SetTradeSetup(ctx context.Context, arg SetTradeSetupParams) error {
	return p.q.SetTradeSetup(ctx, storepg.SetTradeSetupParams(arg))
}

func (p *PG) SetTradeTags(ctx context.Context, arg SetTradeTagsParams) error {
	return p.q.SetTradeTags(ctx, storepg.SetTradeTagsParams(arg))
}

func (p *PG) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) (User, error) {
	v, err := p.q.SetUserAdmin(ctx, storepg.SetUserAdminParams(arg))
	if err != nil {
		return User{}, err
	}
	return User(v), nil
}

func (p *PG) TouchAccessTokenLastUsed(ctx context.Context, id string) error {
	return p.q.TouchAccessTokenLastUsed(ctx, id)
}

func (p *PG) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	v, err := p.q.UpdateAccount(ctx, storepg.UpdateAccountParams(arg))
	if err != nil {
		return Account{}, err
	}
	return Account(v), nil
}

func (p *PG) UpdateAlertChannelStatus(ctx context.Context, arg UpdateAlertChannelStatusParams) error {
	return p.q.UpdateAlertChannelStatus(ctx, storepg.UpdateAlertChannelStatusParams(arg))
}

func (p *PG) UpdateCashTransaction(ctx context.Context, arg UpdateCashTransactionParams) (CashTransaction, error) {
	v, err := p.q.UpdateCashTransaction(ctx, storepg.UpdateCashTransactionParams(arg))
	if err != nil {
		return CashTransaction{}, err
	}
	return CashTransaction(v), nil
}

func (p *PG) UpdateExecution(ctx context.Context, arg UpdateExecutionParams) (int64, error) {
	return p.q.UpdateExecution(ctx, storepg.UpdateExecutionParams(arg))
}

func (p *PG) UpdateFlexSyncStatus(ctx context.Context, arg UpdateFlexSyncStatusParams) error {
	return p.q.UpdateFlexSyncStatus(ctx, storepg.UpdateFlexSyncStatusParams(arg))
}

func (p *PG) UpdateJournalNote(ctx context.Context, arg UpdateJournalNoteParams) (JournalNote, error) {
	v, err := p.q.UpdateJournalNote(ctx, storepg.UpdateJournalNoteParams(arg))
	if err != nil {
		return JournalNote{}, err
	}
	return JournalNote(v), nil
}

func (p *PG) UpdateSetup(ctx context.Context, arg UpdateSetupParams) error {
	return p.q.UpdateSetup(ctx, storepg.UpdateSetupParams(arg))
}

func (p *PG) UpdateTag(ctx context.Context, arg UpdateTagParams) (int64, error) {
	return p.q.UpdateTag(ctx, storepg.UpdateTagParams(arg))
}

func (p *PG) UpdateTradeNotes(ctx context.Context, arg UpdateTradeNotesParams) error {
	return p.q.UpdateTradeNotes(ctx, storepg.UpdateTradeNotesParams(arg))
}

func (p *PG) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	v, err := p.q.UpdateUserPassword(ctx, storepg.UpdateUserPasswordParams(arg))
	if err != nil {
		return User{}, err
	}
	return User(v), nil
}

func (p *PG) UpdateUserTotpSecret(ctx context.Context, arg UpdateUserTotpSecretParams) (User, error) {
	v, err := p.q.UpdateUserTotpSecret(ctx, storepg.UpdateUserTotpSecretParams(arg))
	if err != nil {
		return User{}, err
	}
	return User(v), nil
}

func (p *PG) UpsertAlertChannel(ctx context.Context, arg UpsertAlertChannelParams) (AlertChannel, error) {
	v, err := p.q.UpsertAlertChannel(ctx, storepg.UpsertAlertChannelParams(arg))
	if err != nil {
		return AlertChannel{}, err
	}
	return AlertChannel(v), nil
}

func (p *PG) UpsertAlertSettings(ctx context.Context, arg UpsertAlertSettingsParams) (AlertSetting, error) {
	v, err := p.q.UpsertAlertSettings(ctx, storepg.UpsertAlertSettingsParams(arg))
	if err != nil {
		return AlertSetting{}, err
	}
	return AlertSetting(v), nil
}

func (p *PG) UpsertAnnualGoal(ctx context.Context, arg UpsertAnnualGoalParams) (AnnualGoal, error) {
	v, err := p.q.UpsertAnnualGoal(ctx, storepg.UpsertAnnualGoalParams(arg))
	if err != nil {
		return AnnualGoal{}, err
	}
	return AnnualGoal(v), nil
}

func (p *PG) UpsertChecklistTemplate(ctx context.Context, arg UpsertChecklistTemplateParams) (ChecklistTemplate, error) {
	v, err := p.q.UpsertChecklistTemplate(ctx, storepg.UpsertChecklistTemplateParams(arg))
	if err != nil {
		return ChecklistTemplate{}, err
	}
	return ChecklistTemplate(v), nil
}

func (p *PG) UpsertCoachSettings(ctx context.Context, arg UpsertCoachSettingsParams) (CoachSetting, error) {
	v, err := p.q.UpsertCoachSettings(ctx, storepg.UpsertCoachSettingsParams(arg))
	if err != nil {
		return CoachSetting{}, err
	}
	return CoachSetting(v), nil
}

func (p *PG) UpsertEconomicEvent(ctx context.Context, arg UpsertEconomicEventParams) error {
	return p.q.UpsertEconomicEvent(ctx, storepg.UpsertEconomicEventParams(arg))
}

func (p *PG) UpsertFlexSyncSettings(ctx context.Context, arg UpsertFlexSyncSettingsParams) (FlexSyncSetting, error) {
	v, err := p.q.UpsertFlexSyncSettings(ctx, storepg.UpsertFlexSyncSettingsParams(arg))
	if err != nil {
		return FlexSyncSetting{}, err
	}
	return FlexSyncSetting(v), nil
}

func (p *PG) UpsertInstrumentSpec(ctx context.Context, arg UpsertInstrumentSpecParams) error {
	return p.q.UpsertInstrumentSpec(ctx, storepg.UpsertInstrumentSpecParams(arg))
}

func (p *PG) UpsertMarketBarsCache(ctx context.Context, arg UpsertMarketBarsCacheParams) error {
	return p.q.UpsertMarketBarsCache(ctx, storepg.UpsertMarketBarsCacheParams(arg))
}

func (p *PG) UpsertOcrSettings(ctx context.Context, arg UpsertOcrSettingsParams) (OcrSetting, error) {
	v, err := p.q.UpsertOcrSettings(ctx, storepg.UpsertOcrSettingsParams(arg))
	if err != nil {
		return OcrSetting{}, err
	}
	return OcrSetting(v), nil
}

func (p *PG) UpsertPropSettings(ctx context.Context, arg UpsertPropSettingsParams) (PropSetting, error) {
	v, err := p.q.UpsertPropSettings(ctx, storepg.UpsertPropSettingsParams(arg))
	if err != nil {
		return PropSetting{}, err
	}
	return PropSetting(v), nil
}

func (p *PG) UpsertRiskRules(ctx context.Context, arg UpsertRiskRulesParams) (RiskRule, error) {
	v, err := p.q.UpsertRiskRules(ctx, storepg.UpsertRiskRulesParams(arg))
	if err != nil {
		return RiskRule{}, err
	}
	return RiskRule(v), nil
}

func (p *PG) UpsertTrade(ctx context.Context, arg UpsertTradeParams) error {
	return p.q.UpsertTrade(ctx, storepg.UpsertTradeParams(arg))
}

func (p *PG) UpsertTradeJournal(ctx context.Context, arg UpsertTradeJournalParams) error {
	return p.q.UpsertTradeJournal(ctx, storepg.UpsertTradeJournalParams(arg))
}

func (p *PG) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error) {
	v, err := p.q.UpsertUserPreferences(ctx, storepg.UpsertUserPreferencesParams(arg))
	if err != nil {
		return UserPreference{}, err
	}
	return UserPreference(v), nil
}
