// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	ClearTradeExecutions(ctx context.Context, tradeID string) error
	ClearTradeSetups(ctx context.Context, tradeID string) error
	ClearTradeTags(ctx context.Context, tradeID string) error
	CountAdmins(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCoachReview(ctx context.Context, arg CreateCoachReviewParams) (CoachReview, error)
	CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error)
	CreateJournalNote(ctx context.Context, arg CreateJournalNoteParams) (JournalNote, error)
	CreateSetup(ctx context.Context, arg CreateSetupParams) (Setup, error)
	CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error)
	DeleteAlertChannel(ctx context.Context, arg DeleteAlertChannelParams) (int64, error)
	DeleteAlertChannelByTarget(ctx context.Context, arg DeleteAlertChannelByTargetParams) (int64, error)
	DeleteAnnualGoal(ctx context.Context, arg DeleteAnnualGoalParams) (int64, error)
	DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (int64, error)
	DeleteCashTransaction(ctx context.Context, arg DeleteCashTransactionParams) (int64, error)
	DeleteCoachReview(ctx context.Context, arg DeleteCoachReviewParams) (int64, error)
	DeleteExecution(ctx context.Context, arg DeleteExecutionParams) (int64, error)
	DeleteExecutionsForAccount(ctx context.Context, arg DeleteExecutionsForAccountParams) error
	DeleteExecutionsForBatch(ctx context.Context, arg DeleteExecutionsForBatchParams) error
	DeleteExecutionsForTrade(ctx context.Context, arg DeleteExecutionsForTradeParams) error
	DeleteFlexSyncSettings(ctx context.Context, arg DeleteFlexSyncSettingsParams) (int64, error)
	DeleteFutureEconomicEvents(ctx context.Context, arg DeleteFutureEconomicEventsParams) error
	DeleteJournalNote(ctx context.Context, arg DeleteJournalNoteParams) (int64, error)
	DeleteMediaFile(ctx context.Context, arg DeleteMediaFileParams) (int64, error)
	DeletePropSettings(ctx context.Context, arg DeletePropSettingsParams) error
	DeleteSetup(ctx context.Context, arg DeleteSetupParams) (int64, error)
	DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error)
	DeleteTrade(ctx context.Context, arg DeleteTradeParams) (int64, error)
	DeleteTradesForAccount(ctx context.Context, arg DeleteTradesForAccountParams) error
	DeleteTradesNotInAccount(ctx context.Context, arg DeleteTradesNotInAccountParams) error
	DeleteUser(ctx context.Context, id string) (int64, error)
	DisableAlertChannel(ctx context.Context, id string) error
	ExecutionExists(ctx context.Context, arg ExecutionExistsParams) (int64, error)
	GetAccessTokenByHash(ctx context.Context, tokenHash string) (AccessToken, error)
	GetAccount(ctx context.Context, arg GetAccountParams) (Account, error)
	GetAccountByIDAny(ctx context.Context, id string) (Account, error)
	GetAlertChannel(ctx context.Context, arg GetAlertChannelParams) (AlertChannel, error)
	GetAlertSettings(ctx context.Context, userID string) (AlertSetting, error)
	GetAnnualGoal(ctx context.Context, arg GetAnnualGoalParams) (AnnualGoal, error)
	GetAttachment(ctx context.Context, arg GetAttachmentParams) (TradeAttachment, error)
	GetChecklistTemplate(ctx context.Context, userID string) (ChecklistTemplate, error)
	GetCoachSettings(ctx context.Context) (CoachSetting, error)
	GetEconomicEventsLastFetch(ctx context.Context, provider string) (string, error)
	GetExecution(ctx context.Context, arg GetExecutionParams) (Execution, error)
	GetExecutionByDedup(ctx context.Context, arg GetExecutionByDedupParams) (Execution, error)
	GetFlexSyncSettings(ctx context.Context, arg GetFlexSyncSettingsParams) (FlexSyncSetting, error)
	GetImportBatch(ctx context.Context, arg GetImportBatchParams) (ImportBatch, error)
	GetInstrumentSpec(ctx context.Context, arg GetInstrumentSpecParams) (InstrumentSpec, error)
	GetJournalNote(ctx context.Context, arg GetJournalNoteParams) (JournalNote, error)
	GetMarketBarsCache(ctx context.Context, cacheKey string) (MarketBarsCache, error)
	GetMediaFile(ctx context.Context, arg GetMediaFileParams) (MediaFile, error)
	GetOcrSettings(ctx context.Context) (GetOcrSettingsRow, error)
	GetPropSettings(ctx context.Context, arg GetPropSettingsParams) (PropSetting, error)
	GetRiskRules(ctx context.Context, userID string) (RiskRule, error)
	GetSetup(ctx context.Context, arg GetSetupParams) (Setup, error)
	GetShareLinkByToken(ctx context.Context, token string) (ShareLink, error)
	GetTrade(ctx context.Context, arg GetTradeParams) (Trade, error)
	GetTradeIDForExecution(ctx context.Context, executionID string) (string, error)
	GetTradeJournal(ctx context.Context, arg GetTradeJournalParams) (TradeJournal, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserPreferences(ctx context.Context, userID string) (UserPreference, error)
	IncrementShareLinkViews(ctx context.Context, id string) error
	InsertAlertEvent(ctx context.Context, arg InsertAlertEventParams) (int64, error)
	InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (TradeAttachment, error)
	InsertCashTransaction(ctx context.Context, arg InsertCashTransactionParams) (CashTransaction, error)
	InsertExecution(ctx context.Context, arg InsertExecutionParams) (Execution, error)
	InsertMediaFile(ctx context.Context, arg InsertMediaFileParams) (MediaFile, error)
	InsertTrade(ctx context.Context, arg InsertTradeParams) (Trade, error)
	LatestAccessTokenUse(ctx context.Context, tokenID string) (AccessTokenUse, error)
	LinkTradeExecution(ctx context.Context, arg LinkTradeExecutionParams) error
	ListAccessTokenUses(ctx context.Context, arg ListAccessTokenUsesParams) ([]AccessTokenUse, error)
	ListAccessTokensByUser(ctx context.Context, userID string) ([]AccessToken, error)
	ListAccounts(ctx context.Context, userID string) ([]Account, error)
	ListAlertChannels(ctx context.Context, userID string) ([]AlertChannel, error)
	ListAlertEvents(ctx context.Context, arg ListAlertEventsParams) ([]AlertEvent, error)
	ListAttachmentsForAccount(ctx context.Context, arg ListAttachmentsForAccountParams) ([]TradeAttachment, error)
	ListAttachmentsForTrade(ctx context.Context, arg ListAttachmentsForTradeParams) ([]TradeAttachment, error)
	ListCashForTrade(ctx context.Context, arg ListCashForTradeParams) ([]CashTransaction, error)
	ListCashTransactions(ctx context.Context, arg ListCashTransactionsParams) ([]CashTransaction, error)
	ListClosedTrades(ctx context.Context, arg ListClosedTradesParams) ([]Trade, error)
	ListCoachReviews(ctx context.Context, arg ListCoachReviewsParams) ([]CoachReview, error)
	ListEconomicEvents(ctx context.Context, arg ListEconomicEventsParams) ([]EconomicEvent, error)
	ListEnabledAlertChannels(ctx context.Context, userID string) ([]AlertChannel, error)
	ListEnabledAlertSettings(ctx context.Context) ([]AlertSetting, error)
	ListEnabledFlexSyncSettings(ctx context.Context) ([]FlexSyncSetting, error)
	ListExecutionsForAccount(ctx context.Context, arg ListExecutionsForAccountParams) ([]Execution, error)
	ListExecutionsForTrade(ctx context.Context, tradeID string) ([]Execution, error)
	ListImportBatches(ctx context.Context, userID string) ([]ImportBatch, error)
	ListJournalNotes(ctx context.Context, arg ListJournalNotesParams) ([]JournalNote, error)
	ListJournalRisks(ctx context.Context, userID string) ([]ListJournalRisksRow, error)
	ListMediaFilesForUser(ctx context.Context, userID string) ([]MediaFile, error)
	ListOptionExecutionDetailsForUser(ctx context.Context, userID string) ([]ListOptionExecutionDetailsForUserRow, error)
	ListPropSettingsForUser(ctx context.Context, userID string) ([]PropSetting, error)
	ListSetups(ctx context.Context, userID string) ([]Setup, error)
	ListSetupsForTrade(ctx context.Context, tradeID string) ([]Setup, error)
	ListShareLinksByUser(ctx context.Context, userID string) ([]ShareLink, error)
	ListTags(ctx context.Context, userID string) ([]Tag, error)
	ListTagsForTrade(ctx context.Context, tradeID string) ([]Tag, error)
	ListTradeJournalsForUser(ctx context.Context, userID string) ([]TradeJournal, error)
	ListTradeTagsForUser(ctx context.Context, userID string) ([]ListTradeTagsForUserRow, error)
	ListTrades(ctx context.Context, arg ListTradesParams) ([]Trade, error)
	// Closed, chart-eligible trades with no recorded MFE -- or with MFE but no
	// post-exit excursion yet -- newest first. Options are excluded up front: bars
	// for OCC symbols chart the underlying, so auto excursion would mislead (same
	// rule as the excursion endpoint). The post-exit arm waits until the window
	// has plausibly traded (post_cutoff ~= now-1h) and gives up on trades older
	// than post_floor, so the queue converges instead of retrying bar-less
	// symbols forever.
	ListTradesMissingExcursion(ctx context.Context, arg ListTradesMissingExcursionParams) ([]Trade, error)
	ListUsers(ctx context.Context) ([]User, error)
	PruneAccessTokenUses(ctx context.Context, arg PruneAccessTokenUsesParams) error
	RecordAccessTokenUse(ctx context.Context, arg RecordAccessTokenUseParams) error
	RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) (int64, error)
	RevokeShareLink(ctx context.Context, arg RevokeShareLinkParams) (int64, error)
	SetAlertChannelEnabled(ctx context.Context, arg SetAlertChannelEnabledParams) (AlertChannel, error)
	SetImportBatchStatus(ctx context.Context, arg SetImportBatchStatusParams) error
	SetTradeSetup(ctx context.Context, arg SetTradeSetupParams) error
	SetTradeTags(ctx context.Context, arg SetTradeTagsParams) error
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) (User, error)
	TouchAccessTokenLastUsed(ctx context.Context, id string) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAlertChannelStatus(ctx context.Context, arg UpdateAlertChannelStatusParams) error
	UpdateCashTransaction(ctx context.Context, arg UpdateCashTransactionParams) (CashTransaction, error)
	UpdateExecution(ctx context.Context, arg UpdateExecutionParams) (int64, error)
	UpdateFlexSyncStatus(ctx context.Context, arg UpdateFlexSyncStatusParams) error
	UpdateJournalNote(ctx context.Context, arg UpdateJournalNoteParams) (JournalNote, error)
	UpdateSetup(ctx context.Context, arg UpdateSetupParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) (int64, error)
	UpdateTradeNotes(ctx context.Context, arg UpdateTradeNotesParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserTotpSecret(ctx context.Context, arg UpdateUserTotpSecretParams) (User, error)
	UpsertAlertChannel(ctx context.Context, arg UpsertAlertChannelParams) (AlertChannel, error)
	UpsertAlertSettings(ctx context.Context, arg UpsertAlertSettingsParams) (AlertSetting, error)
	UpsertAnnualGoal(ctx context.Context, arg UpsertAnnualGoalParams) (AnnualGoal, error)
	UpsertChecklistTemplate(ctx context.Context, arg UpsertChecklistTemplateParams) (ChecklistTemplate, error)
	UpsertCoachSettings(ctx context.Context, arg UpsertCoachSettingsParams) (CoachSetting, error)
	UpsertEconomicEvent(ctx context.Context, arg UpsertEconomicEventParams) error
	UpsertFlexSyncSettings(ctx context.Context, arg UpsertFlexSyncSettingsParams) (FlexSyncSetting, error)
	UpsertInstrumentSpec(ctx context.Context, arg UpsertInstrumentSpecParams) error
	UpsertMarketBarsCache(ctx context.Context, arg UpsertMarketBarsCacheParams) error
	UpsertOcrSettings(ctx context.Context, arg UpsertOcrSettingsParams) (OcrSetting, error)
	UpsertPropSettings(ctx context.Context, arg UpsertPropSettingsParams) (PropSetting, error)
	UpsertRiskRules(ctx context.Context, arg UpsertRiskRulesParams) (RiskRule, error)
	UpsertTrade(ctx context.Context, arg UpsertTradeParams) error
	UpsertTradeJournal(ctx context.Context, arg UpsertTradeJournalParams) error
	UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error)
}

var _ Querier = (*Queries)(nil)
