// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	ClearTradeTags(ctx context.Context, tradeID string) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) error
	DeleteCashTransaction(ctx context.Context, arg DeleteCashTransactionParams) error
	DeleteExecutionsForBatch(ctx context.Context, arg DeleteExecutionsForBatchParams) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) error
	DeleteTradesForAccount(ctx context.Context, arg DeleteTradesForAccountParams) error
	ExecutionExists(ctx context.Context, arg ExecutionExistsParams) (int64, error)
	GetAccount(ctx context.Context, arg GetAccountParams) (Account, error)
	GetImportBatch(ctx context.Context, arg GetImportBatchParams) (ImportBatch, error)
	GetInstrumentSpec(ctx context.Context, arg GetInstrumentSpecParams) (InstrumentSpec, error)
	GetTrade(ctx context.Context, arg GetTradeParams) (Trade, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	InsertCashTransaction(ctx context.Context, arg InsertCashTransactionParams) (CashTransaction, error)
	InsertExecution(ctx context.Context, arg InsertExecutionParams) (Execution, error)
	InsertTrade(ctx context.Context, arg InsertTradeParams) (Trade, error)
	LinkTradeExecution(ctx context.Context, arg LinkTradeExecutionParams) error
	ListAccounts(ctx context.Context, userID string) ([]Account, error)
	ListCashTransactions(ctx context.Context, arg ListCashTransactionsParams) ([]CashTransaction, error)
	ListClosedTrades(ctx context.Context, arg ListClosedTradesParams) ([]Trade, error)
	ListExecutionsForAccount(ctx context.Context, arg ListExecutionsForAccountParams) ([]Execution, error)
	ListImportBatches(ctx context.Context, userID string) ([]ImportBatch, error)
	ListTags(ctx context.Context, userID string) ([]Tag, error)
	ListTagsForTrade(ctx context.Context, tradeID string) ([]Tag, error)
	SetImportBatchStatus(ctx context.Context, arg SetImportBatchStatusParams) error
	SetTradeTags(ctx context.Context, arg SetTradeTagsParams) error
	UpdateTradeNotes(ctx context.Context, arg UpdateTradeNotesParams) error
	UpsertInstrumentSpec(ctx context.Context, arg UpsertInstrumentSpecParams) error
}

var _ Querier = (*Queries)(nil)
