// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	ClearTradeExecutions(ctx context.Context, tradeID string) error
	ClearTradeSetups(ctx context.Context, tradeID string) error
	ClearTradeTags(ctx context.Context, tradeID string) error
	CountUsers(ctx context.Context) (int64, error)
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error)
	CreateJournalNote(ctx context.Context, arg CreateJournalNoteParams) (JournalNote, error)
	CreateSetup(ctx context.Context, arg CreateSetupParams) (Setup, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error)
	DeleteAnnualGoal(ctx context.Context, arg DeleteAnnualGoalParams) (int64, error)
	DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (int64, error)
	DeleteCashTransaction(ctx context.Context, arg DeleteCashTransactionParams) (int64, error)
	DeleteExecution(ctx context.Context, arg DeleteExecutionParams) (int64, error)
	DeleteExecutionsForAccount(ctx context.Context, arg DeleteExecutionsForAccountParams) error
	DeleteExecutionsForBatch(ctx context.Context, arg DeleteExecutionsForBatchParams) error
	DeleteExecutionsForTrade(ctx context.Context, arg DeleteExecutionsForTradeParams) error
	DeleteJournalNote(ctx context.Context, arg DeleteJournalNoteParams) (int64, error)
	DeleteMediaFile(ctx context.Context, arg DeleteMediaFileParams) (int64, error)
	DeleteSetup(ctx context.Context, arg DeleteSetupParams) (int64, error)
	DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error)
	DeleteTrade(ctx context.Context, arg DeleteTradeParams) (int64, error)
	DeleteTradesForAccount(ctx context.Context, arg DeleteTradesForAccountParams) error
	DeleteTradesNotInAccount(ctx context.Context, arg DeleteTradesNotInAccountParams) error
	ExecutionExists(ctx context.Context, arg ExecutionExistsParams) (int64, error)
	GetAccessTokenByHash(ctx context.Context, tokenHash string) (AccessToken, error)
	GetAccount(ctx context.Context, arg GetAccountParams) (Account, error)
	GetAccountByIDAny(ctx context.Context, id string) (Account, error)
	GetAnnualGoal(ctx context.Context, arg GetAnnualGoalParams) (AnnualGoal, error)
	GetAttachment(ctx context.Context, arg GetAttachmentParams) (TradeAttachment, error)
	GetChecklistTemplate(ctx context.Context, userID string) (ChecklistTemplate, error)
	GetCoachSettings(ctx context.Context) (CoachSetting, error)
	GetExecution(ctx context.Context, arg GetExecutionParams) (Execution, error)
	GetExecutionByDedup(ctx context.Context, arg GetExecutionByDedupParams) (Execution, error)
	GetImportBatch(ctx context.Context, arg GetImportBatchParams) (ImportBatch, error)
	GetInstrumentSpec(ctx context.Context, arg GetInstrumentSpecParams) (InstrumentSpec, error)
	GetJournalNote(ctx context.Context, arg GetJournalNoteParams) (JournalNote, error)
	GetMarketBarsCache(ctx context.Context, cacheKey string) (MarketBarsCache, error)
	GetMediaFile(ctx context.Context, arg GetMediaFileParams) (MediaFile, error)
	GetOcrSettings(ctx context.Context) (GetOcrSettingsRow, error)
	GetRiskRules(ctx context.Context, userID string) (RiskRule, error)
	GetSetup(ctx context.Context, arg GetSetupParams) (Setup, error)
	GetTrade(ctx context.Context, arg GetTradeParams) (Trade, error)
	GetTradeIDForExecution(ctx context.Context, executionID string) (string, error)
	GetTradeJournal(ctx context.Context, arg GetTradeJournalParams) (TradeJournal, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (TradeAttachment, error)
	InsertCashTransaction(ctx context.Context, arg InsertCashTransactionParams) (CashTransaction, error)
	InsertExecution(ctx context.Context, arg InsertExecutionParams) (Execution, error)
	InsertMediaFile(ctx context.Context, arg InsertMediaFileParams) (MediaFile, error)
	InsertTrade(ctx context.Context, arg InsertTradeParams) (Trade, error)
	LinkTradeExecution(ctx context.Context, arg LinkTradeExecutionParams) error
	ListAccessTokensByUser(ctx context.Context, userID string) ([]AccessToken, error)
	ListAccounts(ctx context.Context, userID string) ([]Account, error)
	ListAttachmentsForAccount(ctx context.Context, arg ListAttachmentsForAccountParams) ([]TradeAttachment, error)
	ListAttachmentsForTrade(ctx context.Context, arg ListAttachmentsForTradeParams) ([]TradeAttachment, error)
	ListCashForTrade(ctx context.Context, arg ListCashForTradeParams) ([]CashTransaction, error)
	ListCashTransactions(ctx context.Context, arg ListCashTransactionsParams) ([]CashTransaction, error)
	ListClosedTrades(ctx context.Context, arg ListClosedTradesParams) ([]Trade, error)
	ListExecutionsForAccount(ctx context.Context, arg ListExecutionsForAccountParams) ([]Execution, error)
	ListExecutionsForTrade(ctx context.Context, tradeID string) ([]Execution, error)
	ListImportBatches(ctx context.Context, userID string) ([]ImportBatch, error)
	ListJournalNotes(ctx context.Context, arg ListJournalNotesParams) ([]JournalNote, error)
	ListJournalRisks(ctx context.Context, userID string) ([]ListJournalRisksRow, error)
	ListMediaFilesForUser(ctx context.Context, userID string) ([]MediaFile, error)
	ListSetups(ctx context.Context, userID string) ([]Setup, error)
	ListSetupsForTrade(ctx context.Context, tradeID string) ([]Setup, error)
	ListTags(ctx context.Context, userID string) ([]Tag, error)
	ListTagsForTrade(ctx context.Context, tradeID string) ([]Tag, error)
	ListTradeJournalsForUser(ctx context.Context, userID string) ([]TradeJournal, error)
	ListTradeTagsForUser(ctx context.Context, userID string) ([]ListTradeTagsForUserRow, error)
	ListTrades(ctx context.Context, arg ListTradesParams) ([]Trade, error)
	RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) (int64, error)
	SetImportBatchStatus(ctx context.Context, arg SetImportBatchStatusParams) error
	SetTradeSetup(ctx context.Context, arg SetTradeSetupParams) error
	SetTradeTags(ctx context.Context, arg SetTradeTagsParams) error
	TouchAccessTokenLastUsed(ctx context.Context, id string) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateCashTransaction(ctx context.Context, arg UpdateCashTransactionParams) (CashTransaction, error)
	UpdateExecution(ctx context.Context, arg UpdateExecutionParams) (int64, error)
	UpdateJournalNote(ctx context.Context, arg UpdateJournalNoteParams) (JournalNote, error)
	UpdateSetup(ctx context.Context, arg UpdateSetupParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) (int64, error)
	UpdateTradeNotes(ctx context.Context, arg UpdateTradeNotesParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpsertAnnualGoal(ctx context.Context, arg UpsertAnnualGoalParams) (AnnualGoal, error)
	UpsertChecklistTemplate(ctx context.Context, arg UpsertChecklistTemplateParams) (ChecklistTemplate, error)
	UpsertCoachSettings(ctx context.Context, arg UpsertCoachSettingsParams) (CoachSetting, error)
	UpsertInstrumentSpec(ctx context.Context, arg UpsertInstrumentSpecParams) error
	UpsertMarketBarsCache(ctx context.Context, arg UpsertMarketBarsCacheParams) error
	UpsertOcrSettings(ctx context.Context, arg UpsertOcrSettingsParams) (OcrSetting, error)
	UpsertRiskRules(ctx context.Context, arg UpsertRiskRulesParams) (RiskRule, error)
	UpsertTrade(ctx context.Context, arg UpsertTradeParams) error
	UpsertTradeJournal(ctx context.Context, arg UpsertTradeJournalParams) error
}

var _ Querier = (*Queries)(nil)
