// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routines.sql

package store

import (
	"context"
	"database/sql"
)

const archiveRoutineItem = `-- name: ArchiveRoutineItem :execrows
UPDATE routine_items SET end_day = ?
WHERE id = ? AND user_id = ? AND end_day IS NULL
`

type ArchiveRoutineItemParams struct {
	EndDay sql.NullString `json:"end_day"`
	ID     string         `json:"id"`
	UserID string         `json:"user_id"`
}

func (q *Queries) ArchiveRoutineItem(ctx context.Context, arg ArchiveRoutineItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveRoutineItem, arg.EndDay, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createRoutineItem = `-- name: CreateRoutineItem :one
INSERT INTO routine_items (id, user_id, title, stage, weekdays, position, start_day)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, title, stage, weekdays, position, start_day, end_day, created_at
`

type CreateRoutineItemParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	Title    string `json:"title"`
	Stage    string `json:"stage"`
	Weekdays int64  `json:"weekdays"`
	Position int64  `json:"position"`
	StartDay string `json:"start_day"`
}

func (q *Queries) CreateRoutineItem(ctx context.Context, arg CreateRoutineItemParams) (RoutineItem, error) {
	row := q.db.QueryRowContext(ctx, createRoutineItem,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Stage,
		arg.Weekdays,
		arg.Position,
		arg.StartDay,
	)
	var i RoutineItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Stage,
		&i.Weekdays,
		&i.Position,
		&i.StartDay,
		&i.EndDay,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoutineCheck = `-- name: DeleteRoutineCheck :execrows
DELETE FROM routine_checks WHERE item_id = ? AND day = ? AND user_id = ?
`

type DeleteRoutineCheckParams struct {
	ItemID string `json:"item_id"`
	Day    string `json:"day"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteRoutineCheck(ctx context.Context, arg DeleteRoutineCheckParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRoutineCheck, arg.ItemID, arg.Day, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRoutineItem = `-- name: GetRoutineItem :one
SELECT id, user_id, title, stage, weekdays, position, start_day, end_day, created_at FROM routine_items WHERE id = ? AND user_id = ?
`

type GetRoutineItemParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetRoutineItem(ctx context.Context, arg GetRoutineItemParams) (RoutineItem, error) {
	row := q.db.QueryRowContext(ctx, getRoutineItem, arg.ID, arg.UserID)
	var i RoutineItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Stage,
		&i.Weekdays,
		&i.Position,
		&i.StartDay,
		&i.EndDay,
		&i.CreatedAt,
	)
	return i, err
}

const insertRoutineCheck = `-- name: InsertRoutineCheck :exec
INSERT INTO routine_checks (user_id, item_id, day)
VALUES (?, ?, ?)
ON CONFLICT (item_id, day) DO NOTHING
`

type InsertRoutineCheckParams struct {
	UserID string `json:"user_id"`
	ItemID string `json:"item_id"`
	Day    string `json:"day"`
}

func (q *Queries) InsertRoutineCheck(ctx context.Context, arg InsertRoutineCheckParams) error {
	_, err := q.db.ExecContext(ctx, insertRoutineCheck, arg.UserID, arg.ItemID, arg.Day)
	return err
}

const listRoutineChecks = `-- name: ListRoutineChecks :many
SELECT user_id, item_id, day, checked_at FROM routine_checks
WHERE user_id = ? AND day >= ? AND day <= ?
ORDER BY day, item_id
`

type ListRoutineChecksParams struct {
	UserID string `json:"user_id"`
	Day    string `json:"day"`
	Day_2  string `json:"day_2"`
}

func (q *Queries) ListRoutineChecks(ctx context.Context, arg ListRoutineChecksParams) ([]RoutineCheck, error) {
	rows, err := q.db.QueryContext(ctx, listRoutineChecks, arg.UserID, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoutineCheck
	for rows.Next() {
		var i RoutineCheck
		if err := rows.Scan(
			&i.UserID,
			&i.ItemID,
			&i.Day,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutineItems = `-- name: ListRoutineItems :many
SELECT id, user_id, title, stage, weekdays, position, start_day, end_day, created_at FROM routine_items
WHERE user_id = ?
ORDER BY position, created_at, id
`

func (q *Queries) ListRoutineItems(ctx context.Context, userID string) ([]RoutineItem, error) {
	rows, err := q.db.QueryContext(ctx, listRoutineItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoutineItem
	for rows.Next() {
		var i RoutineItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Stage,
			&i.Weekdays,
			&i.Position,
			&i.StartDay,
			&i.EndDay,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveRoutineChecks = `-- name: MoveRoutineChecks :exec
UPDATE routine_checks SET item_id = ?
WHERE item_id = ? AND user_id = ? AND day >= ?
`

type MoveRoutineChecksParams struct {
	ItemID   string `json:"item_id"`
	ItemID_2 string `json:"item_id_2"`
	UserID   string `json:"user_id"`
	Day      string `json:"day"`
}

func (q *Queries) MoveRoutineChecks(ctx context.Context, arg MoveRoutineChecksParams) error {
	_, err := q.db.ExecContext(ctx, moveRoutineChecks,
		arg.ItemID,
		arg.ItemID_2,
		arg.UserID,
		arg.Day,
	)
	return err
}

const seedRoutineItem = `-- name: SeedRoutineItem :exec
INSERT INTO routine_items (id, user_id, title, stage, weekdays, position, start_day)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type SeedRoutineItemParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	Title    string `json:"title"`
	Stage    string `json:"stage"`
	Weekdays int64  `json:"weekdays"`
	Position int64  `json:"position"`
	StartDay string `json:"start_day"`
}

func (q *Queries) SeedRoutineItem(ctx context.Context, arg SeedRoutineItemParams) error {
	_, err := q.db.ExecContext(ctx, seedRoutineItem,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Stage,
		arg.Weekdays,
		arg.Position,
		arg.StartDay,
	)
	return err
}

const setRoutineItemPosition = `-- name: SetRoutineItemPosition :execrows
UPDATE routine_items SET position = ? WHERE id = ? AND user_id = ?
`

type SetRoutineItemPositionParams struct {
	Position int64  `json:"position"`
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) SetRoutineItemPosition(ctx context.Context, arg SetRoutineItemPositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRoutineItemPosition, arg.Position, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRoutineItem = `-- name: UpdateRoutineItem :one
UPDATE routine_items
SET title = ?, stage = ?, weekdays = ?
WHERE id = ? AND user_id = ? AND end_day IS NULL
RETURNING id, user_id, title, stage, weekdays, position, start_day, end_day, created_at
`

type UpdateRoutineItemParams struct {
	Title    string `json:"title"`
	Stage    string `json:"stage"`
	Weekdays int64  `json:"weekdays"`
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) UpdateRoutineItem(ctx context.Context, arg UpdateRoutineItemParams) (RoutineItem, error) {
	row := q.db.QueryRowContext(ctx, updateRoutineItem,
		arg.Title,
		arg.Stage,
		arg.Weekdays,
		arg.ID,
		arg.UserID,
	)
	var i RoutineItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Stage,
		&i.Weekdays,
		&i.Position,
		&i.StartDay,
		&i.EndDay,
		&i.CreatedAt,
	)
	return i, err
}
