// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setups.sql

package store

import (
	"context"
)

const createSetup = `-- name: CreateSetup :one
INSERT INTO setups (id, user_id, name, description) VALUES (?, ?, ?, ?) RETURNING id, user_id, name, description, created_at
`

type CreateSetupParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateSetup(ctx context.Context, arg CreateSetupParams) (Setup, error) {
	row := q.db.QueryRowContext(ctx, createSetup,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
	)
	var i Setup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSetup = `-- name: DeleteSetup :execrows
DELETE FROM setups WHERE id = ? AND user_id = ?
`

type DeleteSetupParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteSetup(ctx context.Context, arg DeleteSetupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSetup, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSetup = `-- name: GetSetup :one
SELECT id, user_id, name, description, created_at FROM setups WHERE id = ? AND user_id = ?
`

type GetSetupParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetSetup(ctx context.Context, arg GetSetupParams) (Setup, error) {
	row := q.db.QueryRowContext(ctx, getSetup, arg.ID, arg.UserID)
	var i Setup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listSetups = `-- name: ListSetups :many
SELECT id, user_id, name, description, created_at FROM setups WHERE user_id = ? ORDER BY name
`

func (q *Queries) ListSetups(ctx context.Context, userID string) ([]Setup, error) {
	rows, err := q.db.QueryContext(ctx, listSetups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setup
	for rows.Next() {
		var i Setup
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSetup = `-- name: UpdateSetup :exec
UPDATE setups SET name = ?, description = ? WHERE id = ? AND user_id = ?
`

type UpdateSetupParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) UpdateSetup(ctx context.Context, arg UpdateSetupParams) error {
	_, err := q.db.ExecContext(ctx, updateSetup,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.UserID,
	)
	return err
}
