// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_plans.sql

package store

import (
	"context"
	"database/sql"
)

const createSystemPlan = `-- name: CreateSystemPlan :one
INSERT INTO system_plans (id, user_id, version_id, symbol, direction, status, source)
VALUES (?, ?, ?, ?, ?, 'planned', ?)
RETURNING id, user_id, version_id, symbol, direction, status, source, trade_id, created_at, updated_at
`

type CreateSystemPlanParams struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	VersionID sql.NullString `json:"version_id"`
	Symbol    string         `json:"symbol"`
	Direction string         `json:"direction"`
	Source    string         `json:"source"`
}

func (q *Queries) CreateSystemPlan(ctx context.Context, arg CreateSystemPlanParams) (SystemPlan, error) {
	row := q.db.QueryRowContext(ctx, createSystemPlan,
		arg.ID,
		arg.UserID,
		arg.VersionID,
		arg.Symbol,
		arg.Direction,
		arg.Source,
	)
	var i SystemPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VersionID,
		&i.Symbol,
		&i.Direction,
		&i.Status,
		&i.Source,
		&i.TradeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSystemPlanEvent = `-- name: CreateSystemPlanEvent :one
INSERT INTO system_plan_events (id, plan_id, user_id, kind, from_status, to_status, trade_id, reason)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, plan_id, user_id, kind, from_status, to_status, trade_id, reason, created_at
`

type CreateSystemPlanEventParams struct {
	ID         string `json:"id"`
	PlanID     string `json:"plan_id"`
	UserID     string `json:"user_id"`
	Kind       string `json:"kind"`
	FromStatus string `json:"from_status"`
	ToStatus   string `json:"to_status"`
	TradeID    string `json:"trade_id"`
	Reason     string `json:"reason"`
}

func (q *Queries) CreateSystemPlanEvent(ctx context.Context, arg CreateSystemPlanEventParams) (SystemPlanEvent, error) {
	row := q.db.QueryRowContext(ctx, createSystemPlanEvent,
		arg.ID,
		arg.PlanID,
		arg.UserID,
		arg.Kind,
		arg.FromStatus,
		arg.ToStatus,
		arg.TradeID,
		arg.Reason,
	)
	var i SystemPlanEvent
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.UserID,
		&i.Kind,
		&i.FromStatus,
		&i.ToStatus,
		&i.TradeID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createSystemPlanRevision = `-- name: CreateSystemPlanRevision :one
INSERT INTO system_plan_revisions (
    id, plan_id, user_id, seq, stage, setup, thesis, trigger_text, invalidation,
    entry_price, stop_price, target_price, conditions, occurred_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, plan_id, user_id, seq, stage, setup, thesis, trigger_text, invalidation, entry_price, stop_price, target_price, conditions, occurred_at, recorded_at
`

type CreateSystemPlanRevisionParams struct {
	ID           string          `json:"id"`
	PlanID       string          `json:"plan_id"`
	UserID       string          `json:"user_id"`
	Seq          int64           `json:"seq"`
	Stage        string          `json:"stage"`
	Setup        string          `json:"setup"`
	Thesis       string          `json:"thesis"`
	TriggerText  string          `json:"trigger_text"`
	Invalidation string          `json:"invalidation"`
	EntryPrice   sql.NullFloat64 `json:"entry_price"`
	StopPrice    sql.NullFloat64 `json:"stop_price"`
	TargetPrice  sql.NullFloat64 `json:"target_price"`
	Conditions   string          `json:"conditions"`
	OccurredAt   sql.NullTime    `json:"occurred_at"`
}

func (q *Queries) CreateSystemPlanRevision(ctx context.Context, arg CreateSystemPlanRevisionParams) (SystemPlanRevision, error) {
	row := q.db.QueryRowContext(ctx, createSystemPlanRevision,
		arg.ID,
		arg.PlanID,
		arg.UserID,
		arg.Seq,
		arg.Stage,
		arg.Setup,
		arg.Thesis,
		arg.TriggerText,
		arg.Invalidation,
		arg.EntryPrice,
		arg.StopPrice,
		arg.TargetPrice,
		arg.Conditions,
		arg.OccurredAt,
	)
	var i SystemPlanRevision
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.UserID,
		&i.Seq,
		&i.Stage,
		&i.Setup,
		&i.Thesis,
		&i.TriggerText,
		&i.Invalidation,
		&i.EntryPrice,
		&i.StopPrice,
		&i.TargetPrice,
		&i.Conditions,
		&i.OccurredAt,
		&i.RecordedAt,
	)
	return i, err
}

const getSystemPlan = `-- name: GetSystemPlan :one
SELECT id, user_id, version_id, symbol, direction, status, source, trade_id, created_at, updated_at FROM system_plans WHERE id = ? AND user_id = ?
`

type GetSystemPlanParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetSystemPlan(ctx context.Context, arg GetSystemPlanParams) (SystemPlan, error) {
	row := q.db.QueryRowContext(ctx, getSystemPlan, arg.ID, arg.UserID)
	var i SystemPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VersionID,
		&i.Symbol,
		&i.Direction,
		&i.Status,
		&i.Source,
		&i.TradeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemPlanByTrade = `-- name: GetSystemPlanByTrade :one
SELECT id, user_id, version_id, symbol, direction, status, source, trade_id, created_at, updated_at FROM system_plans WHERE trade_id = ? AND user_id = ? LIMIT 1
`

type GetSystemPlanByTradeParams struct {
	TradeID sql.NullString `json:"trade_id"`
	UserID  string         `json:"user_id"`
}

func (q *Queries) GetSystemPlanByTrade(ctx context.Context, arg GetSystemPlanByTradeParams) (SystemPlan, error) {
	row := q.db.QueryRowContext(ctx, getSystemPlanByTrade, arg.TradeID, arg.UserID)
	var i SystemPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VersionID,
		&i.Symbol,
		&i.Direction,
		&i.Status,
		&i.Source,
		&i.TradeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLatestSystemPlanRevisions = `-- name: ListLatestSystemPlanRevisions :many
SELECT r.id, r.plan_id, r.user_id, r.seq, r.stage, r.setup, r.thesis, r.trigger_text, r.invalidation, r.entry_price, r.stop_price, r.target_price, r.conditions, r.occurred_at, r.recorded_at FROM system_plan_revisions r
WHERE r.user_id = ? AND r.seq = (
    SELECT MAX(s.seq) FROM system_plan_revisions s WHERE s.plan_id = r.plan_id
)
`

func (q *Queries) ListLatestSystemPlanRevisions(ctx context.Context, userID string) ([]SystemPlanRevision, error) {
	rows, err := q.db.QueryContext(ctx, listLatestSystemPlanRevisions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemPlanRevision
	for rows.Next() {
		var i SystemPlanRevision
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.UserID,
			&i.Seq,
			&i.Stage,
			&i.Setup,
			&i.Thesis,
			&i.TriggerText,
			&i.Invalidation,
			&i.EntryPrice,
			&i.StopPrice,
			&i.TargetPrice,
			&i.Conditions,
			&i.OccurredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemPlanEvents = `-- name: ListSystemPlanEvents :many
SELECT id, plan_id, user_id, kind, from_status, to_status, trade_id, reason, created_at FROM system_plan_events
WHERE plan_id = ? AND user_id = ?
ORDER BY created_at ASC, id ASC
`

type ListSystemPlanEventsParams struct {
	PlanID string `json:"plan_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ListSystemPlanEvents(ctx context.Context, arg ListSystemPlanEventsParams) ([]SystemPlanEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSystemPlanEvents, arg.PlanID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemPlanEvent
	for rows.Next() {
		var i SystemPlanEvent
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.UserID,
			&i.Kind,
			&i.FromStatus,
			&i.ToStatus,
			&i.TradeID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemPlanRevisions = `-- name: ListSystemPlanRevisions :many
SELECT id, plan_id, user_id, seq, stage, setup, thesis, trigger_text, invalidation, entry_price, stop_price, target_price, conditions, occurred_at, recorded_at FROM system_plan_revisions
WHERE plan_id = ? AND user_id = ?
ORDER BY seq ASC
`

type ListSystemPlanRevisionsParams struct {
	PlanID string `json:"plan_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ListSystemPlanRevisions(ctx context.Context, arg ListSystemPlanRevisionsParams) ([]SystemPlanRevision, error) {
	rows, err := q.db.QueryContext(ctx, listSystemPlanRevisions, arg.PlanID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemPlanRevision
	for rows.Next() {
		var i SystemPlanRevision
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.UserID,
			&i.Seq,
			&i.Stage,
			&i.Setup,
			&i.Thesis,
			&i.TriggerText,
			&i.Invalidation,
			&i.EntryPrice,
			&i.StopPrice,
			&i.TargetPrice,
			&i.Conditions,
			&i.OccurredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemPlans = `-- name: ListSystemPlans :many
SELECT id, user_id, version_id, symbol, direction, status, source, trade_id, created_at, updated_at FROM system_plans
WHERE user_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListSystemPlans(ctx context.Context, userID string) ([]SystemPlan, error) {
	rows, err := q.db.QueryContext(ctx, listSystemPlans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemPlan
	for rows.Next() {
		var i SystemPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VersionID,
			&i.Symbol,
			&i.Direction,
			&i.Status,
			&i.Source,
			&i.TradeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradesBySymbol = `-- name: ListTradesBySymbol :many
SELECT id, user_id, account_id, symbol, instrument_type, direction, status, opened_at, closed_at, qty_opened, avg_entry_price, avg_exit_price, gross_pnl, fees_total, net_pnl, pnl_currency, return_pct, r_multiple, time_in_trade_secs, notes, created_at, updated_at, qty_remaining FROM trades
WHERE user_id = ? AND symbol = ?
ORDER BY opened_at DESC
LIMIT 50
`

type ListTradesBySymbolParams struct {
	UserID string `json:"user_id"`
	Symbol string `json:"symbol"`
}

func (q *Queries) ListTradesBySymbol(ctx context.Context, arg ListTradesBySymbolParams) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, listTradesBySymbol, arg.UserID, arg.Symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Symbol,
			&i.InstrumentType,
			&i.Direction,
			&i.Status,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.QtyOpened,
			&i.AvgEntryPrice,
			&i.AvgExitPrice,
			&i.GrossPnl,
			&i.FeesTotal,
			&i.NetPnl,
			&i.PnlCurrency,
			&i.ReturnPct,
			&i.RMultiple,
			&i.TimeInTradeSecs,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QtyRemaining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxSystemPlanRevisionSeq = `-- name: MaxSystemPlanRevisionSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) AS INTEGER) FROM system_plan_revisions WHERE plan_id = ? AND user_id = ?
`

type MaxSystemPlanRevisionSeqParams struct {
	PlanID string `json:"plan_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) MaxSystemPlanRevisionSeq(ctx context.Context, arg MaxSystemPlanRevisionSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxSystemPlanRevisionSeq, arg.PlanID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setSystemPlanTrade = `-- name: SetSystemPlanTrade :one
UPDATE system_plans
SET trade_id = ?, status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, version_id, symbol, direction, status, source, trade_id, created_at, updated_at
`

type SetSystemPlanTradeParams struct {
	TradeID sql.NullString `json:"trade_id"`
	Status  string         `json:"status"`
	ID      string         `json:"id"`
	UserID  string         `json:"user_id"`
}

func (q *Queries) SetSystemPlanTrade(ctx context.Context, arg SetSystemPlanTradeParams) (SystemPlan, error) {
	row := q.db.QueryRowContext(ctx, setSystemPlanTrade,
		arg.TradeID,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	var i SystemPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VersionID,
		&i.Symbol,
		&i.Direction,
		&i.Status,
		&i.Source,
		&i.TradeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSystemPlan = `-- name: TouchSystemPlan :exec
UPDATE system_plans SET updated_at = CURRENT_TIMESTAMP WHERE id = ? AND user_id = ?
`

type TouchSystemPlanParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) TouchSystemPlan(ctx context.Context, arg TouchSystemPlanParams) error {
	_, err := q.db.ExecContext(ctx, touchSystemPlan, arg.ID, arg.UserID)
	return err
}

const updateSystemPlanStatus = `-- name: UpdateSystemPlanStatus :one
UPDATE system_plans
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, version_id, symbol, direction, status, source, trade_id, created_at, updated_at
`

type UpdateSystemPlanStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateSystemPlanStatus(ctx context.Context, arg UpdateSystemPlanStatusParams) (SystemPlan, error) {
	row := q.db.QueryRowContext(ctx, updateSystemPlanStatus, arg.Status, arg.ID, arg.UserID)
	var i SystemPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VersionID,
		&i.Symbol,
		&i.Direction,
		&i.Status,
		&i.Source,
		&i.TradeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
