// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_plan_evidence.sql

package store

import (
	"context"
	"database/sql"
)

const createSystemPlanEvidence = `-- name: CreateSystemPlanEvidence :one
INSERT INTO system_plan_evidence (id, plan_id, user_id)
VALUES (?, ?, ?)
RETURNING id, plan_id, user_id, withdrawn_at, withdraw_reason, created_at
`

type CreateSystemPlanEvidenceParams struct {
	ID     string `json:"id"`
	PlanID string `json:"plan_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) CreateSystemPlanEvidence(ctx context.Context, arg CreateSystemPlanEvidenceParams) (SystemPlanEvidence, error) {
	row := q.db.QueryRowContext(ctx, createSystemPlanEvidence, arg.ID, arg.PlanID, arg.UserID)
	var i SystemPlanEvidence
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.UserID,
		&i.WithdrawnAt,
		&i.WithdrawReason,
		&i.CreatedAt,
	)
	return i, err
}

const createSystemPlanEvidenceRevision = `-- name: CreateSystemPlanEvidenceRevision :one
INSERT INTO system_plan_evidence_revisions (
    id, evidence_id, user_id, seq, decision_id, stance, body, state, action, source, occurred_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, evidence_id, user_id, seq, decision_id, stance, body, state, "action", source, occurred_at, recorded_at
`

type CreateSystemPlanEvidenceRevisionParams struct {
	ID         string       `json:"id"`
	EvidenceID string       `json:"evidence_id"`
	UserID     string       `json:"user_id"`
	Seq        int64        `json:"seq"`
	DecisionID string       `json:"decision_id"`
	Stance     string       `json:"stance"`
	Body       string       `json:"body"`
	State      string       `json:"state"`
	Action     string       `json:"action"`
	Source     string       `json:"source"`
	OccurredAt sql.NullTime `json:"occurred_at"`
}

func (q *Queries) CreateSystemPlanEvidenceRevision(ctx context.Context, arg CreateSystemPlanEvidenceRevisionParams) (SystemPlanEvidenceRevision, error) {
	row := q.db.QueryRowContext(ctx, createSystemPlanEvidenceRevision,
		arg.ID,
		arg.EvidenceID,
		arg.UserID,
		arg.Seq,
		arg.DecisionID,
		arg.Stance,
		arg.Body,
		arg.State,
		arg.Action,
		arg.Source,
		arg.OccurredAt,
	)
	var i SystemPlanEvidenceRevision
	err := row.Scan(
		&i.ID,
		&i.EvidenceID,
		&i.UserID,
		&i.Seq,
		&i.DecisionID,
		&i.Stance,
		&i.Body,
		&i.State,
		&i.Action,
		&i.Source,
		&i.OccurredAt,
		&i.RecordedAt,
	)
	return i, err
}

const getSystemPlanEvidence = `-- name: GetSystemPlanEvidence :one
SELECT id, plan_id, user_id, withdrawn_at, withdraw_reason, created_at FROM system_plan_evidence WHERE id = ? AND user_id = ?
`

type GetSystemPlanEvidenceParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetSystemPlanEvidence(ctx context.Context, arg GetSystemPlanEvidenceParams) (SystemPlanEvidence, error) {
	row := q.db.QueryRowContext(ctx, getSystemPlanEvidence, arg.ID, arg.UserID)
	var i SystemPlanEvidence
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.UserID,
		&i.WithdrawnAt,
		&i.WithdrawReason,
		&i.CreatedAt,
	)
	return i, err
}

const listSystemPlanEvidence = `-- name: ListSystemPlanEvidence :many
SELECT id, plan_id, user_id, withdrawn_at, withdraw_reason, created_at FROM system_plan_evidence
WHERE plan_id = ? AND user_id = ?
ORDER BY created_at DESC, id DESC
`

type ListSystemPlanEvidenceParams struct {
	PlanID string `json:"plan_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ListSystemPlanEvidence(ctx context.Context, arg ListSystemPlanEvidenceParams) ([]SystemPlanEvidence, error) {
	rows, err := q.db.QueryContext(ctx, listSystemPlanEvidence, arg.PlanID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemPlanEvidence
	for rows.Next() {
		var i SystemPlanEvidence
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.UserID,
			&i.WithdrawnAt,
			&i.WithdrawReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemPlanEvidenceRevisions = `-- name: ListSystemPlanEvidenceRevisions :many
SELECT r.id, r.evidence_id, r.user_id, r.seq, r.decision_id, r.stance, r.body, r.state, r.action, r.source, r.occurred_at, r.recorded_at
FROM system_plan_evidence_revisions r
INNER JOIN system_plan_evidence e ON e.id = r.evidence_id
WHERE e.plan_id = ? AND e.user_id = ?
ORDER BY r.seq ASC, r.recorded_at ASC
`

type ListSystemPlanEvidenceRevisionsParams struct {
	PlanID string `json:"plan_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ListSystemPlanEvidenceRevisions(ctx context.Context, arg ListSystemPlanEvidenceRevisionsParams) ([]SystemPlanEvidenceRevision, error) {
	rows, err := q.db.QueryContext(ctx, listSystemPlanEvidenceRevisions, arg.PlanID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemPlanEvidenceRevision
	for rows.Next() {
		var i SystemPlanEvidenceRevision
		if err := rows.Scan(
			&i.ID,
			&i.EvidenceID,
			&i.UserID,
			&i.Seq,
			&i.DecisionID,
			&i.Stance,
			&i.Body,
			&i.State,
			&i.Action,
			&i.Source,
			&i.OccurredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxSystemPlanEvidenceRevisionSeq = `-- name: MaxSystemPlanEvidenceRevisionSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) AS INTEGER)
FROM system_plan_evidence_revisions
WHERE evidence_id = ? AND user_id = ?
`

type MaxSystemPlanEvidenceRevisionSeqParams struct {
	EvidenceID string `json:"evidence_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) MaxSystemPlanEvidenceRevisionSeq(ctx context.Context, arg MaxSystemPlanEvidenceRevisionSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxSystemPlanEvidenceRevisionSeq, arg.EvidenceID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const withdrawSystemPlanEvidence = `-- name: WithdrawSystemPlanEvidence :one
UPDATE system_plan_evidence
SET withdrawn_at = CURRENT_TIMESTAMP, withdraw_reason = ?
WHERE id = ? AND user_id = ? AND withdrawn_at IS NULL
RETURNING id, plan_id, user_id, withdrawn_at, withdraw_reason, created_at
`

type WithdrawSystemPlanEvidenceParams struct {
	WithdrawReason string `json:"withdraw_reason"`
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) WithdrawSystemPlanEvidence(ctx context.Context, arg WithdrawSystemPlanEvidenceParams) (SystemPlanEvidence, error) {
	row := q.db.QueryRowContext(ctx, withdrawSystemPlanEvidence, arg.WithdrawReason, arg.ID, arg.UserID)
	var i SystemPlanEvidence
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.UserID,
		&i.WithdrawnAt,
		&i.WithdrawReason,
		&i.CreatedAt,
	)
	return i, err
}
