// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package store

import (
	"context"
)

const clearTradeTags = `-- name: ClearTradeTags :exec
DELETE FROM trade_tags WHERE trade_id = ?
`

func (q *Queries) ClearTradeTags(ctx context.Context, tradeID string) error {
	_, err := q.db.ExecContext(ctx, clearTradeTags, tradeID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, user_id, name, color, description) VALUES (?, ?, ?, ?, ?) RETURNING id, user_id, name, color, description
`

type CreateTagParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	Name        string `json:"name"`
	Color       string `json:"color"`
	Description string `json:"description"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Description,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Description,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ? AND user_id = ?
`

type DeleteTagParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteTag, arg.ID, arg.UserID)
	return err
}

const listTags = `-- name: ListTags :many
SELECT id, user_id, name, color, description FROM tags WHERE user_id = ? ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context, userID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTrade = `-- name: ListTagsForTrade :many
SELECT t.id, t.user_id, t.name, t.color, t.description FROM tags t JOIN trade_tags tt ON tt.tag_id = t.id WHERE tt.trade_id = ?
`

func (q *Queries) ListTagsForTrade(ctx context.Context, tradeID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForTrade, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTradeTags = `-- name: SetTradeTags :exec
INSERT OR IGNORE INTO trade_tags (trade_id, tag_id) VALUES (?, ?)
`

type SetTradeTagsParams struct {
	TradeID string `json:"trade_id"`
	TagID   string `json:"tag_id"`
}

func (q *Queries) SetTradeTags(ctx context.Context, arg SetTradeTagsParams) error {
	_, err := q.db.ExecContext(ctx, setTradeTags, arg.TradeID, arg.TagID)
	return err
}
