// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trade_setups.sql

package store

import (
	"context"
)

const clearTradeSetups = `-- name: ClearTradeSetups :exec
DELETE FROM trade_setups WHERE trade_id = ?
`

func (q *Queries) ClearTradeSetups(ctx context.Context, tradeID string) error {
	_, err := q.db.ExecContext(ctx, clearTradeSetups, tradeID)
	return err
}

const listSetupsForTrade = `-- name: ListSetupsForTrade :many
SELECT s.id, s.user_id, s.name, s.description, s.created_at, s.thesis, s.symbol, s.direction, s.target_price, s.stop_price, s.checklist FROM setups s
JOIN trade_setups ts ON ts.setup_id = s.id
WHERE ts.trade_id = ?
ORDER BY s.name
`

func (q *Queries) ListSetupsForTrade(ctx context.Context, tradeID string) ([]Setup, error) {
	rows, err := q.db.QueryContext(ctx, listSetupsForTrade, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setup
	for rows.Next() {
		var i Setup
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.Thesis,
			&i.Symbol,
			&i.Direction,
			&i.TargetPrice,
			&i.StopPrice,
			&i.Checklist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTradeSetup = `-- name: SetTradeSetup :exec
INSERT OR IGNORE INTO trade_setups (trade_id, setup_id) VALUES (?, ?)
`

type SetTradeSetupParams struct {
	TradeID string `json:"trade_id"`
	SetupID string `json:"setup_id"`
}

func (q *Queries) SetTradeSetup(ctx context.Context, arg SetTradeSetupParams) error {
	_, err := q.db.ExecContext(ctx, setTradeSetup, arg.TradeID, arg.SetupID)
	return err
}
