// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trading_system.sql

package store

import (
	"context"
	"database/sql"
)

const activateSystemVersion = `-- name: ActivateSystemVersion :one
UPDATE system_versions
SET status = 'active', activated_at = ?, retired_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, system_id, user_id, label, status, rules, open_questions, regimes, trade_types, activated_at, retired_at, created_at, updated_at, name
`

type ActivateSystemVersionParams struct {
	ActivatedAt sql.NullTime `json:"activated_at"`
	ID          string       `json:"id"`
	UserID      string       `json:"user_id"`
}

func (q *Queries) ActivateSystemVersion(ctx context.Context, arg ActivateSystemVersionParams) (SystemVersion, error) {
	row := q.db.QueryRowContext(ctx, activateSystemVersion, arg.ActivatedAt, arg.ID, arg.UserID)
	var i SystemVersion
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.UserID,
		&i.Label,
		&i.Status,
		&i.Rules,
		&i.OpenQuestions,
		&i.Regimes,
		&i.TradeTypes,
		&i.ActivatedAt,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const createSystemChange = `-- name: CreateSystemChange :one
INSERT INTO system_changes (id, version_id, user_id, decision, reason, note, evidence_trade_ids)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, version_id, user_id, decision, reason, note, evidence_trade_ids, created_at
`

type CreateSystemChangeParams struct {
	ID               string `json:"id"`
	VersionID        string `json:"version_id"`
	UserID           string `json:"user_id"`
	Decision         string `json:"decision"`
	Reason           string `json:"reason"`
	Note             string `json:"note"`
	EvidenceTradeIds string `json:"evidence_trade_ids"`
}

func (q *Queries) CreateSystemChange(ctx context.Context, arg CreateSystemChangeParams) (SystemChange, error) {
	row := q.db.QueryRowContext(ctx, createSystemChange,
		arg.ID,
		arg.VersionID,
		arg.UserID,
		arg.Decision,
		arg.Reason,
		arg.Note,
		arg.EvidenceTradeIds,
	)
	var i SystemChange
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.UserID,
		&i.Decision,
		&i.Reason,
		&i.Note,
		&i.EvidenceTradeIds,
		&i.CreatedAt,
	)
	return i, err
}

const createSystemVersion = `-- name: CreateSystemVersion :one
INSERT INTO system_versions (
    id, system_id, user_id, label, status, rules, open_questions, regimes, trade_types
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, system_id, user_id, label, status, rules, open_questions, regimes, trade_types, activated_at, retired_at, created_at, updated_at, name
`

type CreateSystemVersionParams struct {
	ID            string `json:"id"`
	SystemID      string `json:"system_id"`
	UserID        string `json:"user_id"`
	Label         string `json:"label"`
	Status        string `json:"status"`
	Rules         string `json:"rules"`
	OpenQuestions string `json:"open_questions"`
	Regimes       string `json:"regimes"`
	TradeTypes    string `json:"trade_types"`
}

func (q *Queries) CreateSystemVersion(ctx context.Context, arg CreateSystemVersionParams) (SystemVersion, error) {
	row := q.db.QueryRowContext(ctx, createSystemVersion,
		arg.ID,
		arg.SystemID,
		arg.UserID,
		arg.Label,
		arg.Status,
		arg.Rules,
		arg.OpenQuestions,
		arg.Regimes,
		arg.TradeTypes,
	)
	var i SystemVersion
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.UserID,
		&i.Label,
		&i.Status,
		&i.Rules,
		&i.OpenQuestions,
		&i.Regimes,
		&i.TradeTypes,
		&i.ActivatedAt,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const createTradingSystem = `-- name: CreateTradingSystem :one
INSERT INTO trading_systems (id, user_id, name)
VALUES (?, ?, ?)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateTradingSystemParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateTradingSystem(ctx context.Context, arg CreateTradingSystemParams) (TradingSystem, error) {
	row := q.db.QueryRowContext(ctx, createTradingSystem, arg.ID, arg.UserID, arg.Name)
	var i TradingSystem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMarketRegimeDay = `-- name: DeleteMarketRegimeDay :execrows
DELETE FROM market_regime_days WHERE user_id = ? AND day = ?
`

type DeleteMarketRegimeDayParams struct {
	UserID string `json:"user_id"`
	Day    string `json:"day"`
}

func (q *Queries) DeleteMarketRegimeDay(ctx context.Context, arg DeleteMarketRegimeDayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMarketRegimeDay, arg.UserID, arg.Day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSystemVersion = `-- name: DeleteSystemVersion :execrows
DELETE FROM system_versions WHERE id = ? AND user_id = ? AND status = 'draft'
`

type DeleteSystemVersionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteSystemVersion(ctx context.Context, arg DeleteSystemVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSystemVersion, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveSystemVersion = `-- name: GetActiveSystemVersion :one
SELECT id, system_id, user_id, label, status, rules, open_questions, regimes, trade_types, activated_at, retired_at, created_at, updated_at, name FROM system_versions
WHERE user_id = ? AND status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveSystemVersion(ctx context.Context, userID string) (SystemVersion, error) {
	row := q.db.QueryRowContext(ctx, getActiveSystemVersion, userID)
	var i SystemVersion
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.UserID,
		&i.Label,
		&i.Status,
		&i.Rules,
		&i.OpenQuestions,
		&i.Regimes,
		&i.TradeTypes,
		&i.ActivatedAt,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getDraftSystemVersion = `-- name: GetDraftSystemVersion :one
SELECT id, system_id, user_id, label, status, rules, open_questions, regimes, trade_types, activated_at, retired_at, created_at, updated_at, name FROM system_versions
WHERE user_id = ? AND status = 'draft'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetDraftSystemVersion(ctx context.Context, userID string) (SystemVersion, error) {
	row := q.db.QueryRowContext(ctx, getDraftSystemVersion, userID)
	var i SystemVersion
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.UserID,
		&i.Label,
		&i.Status,
		&i.Rules,
		&i.OpenQuestions,
		&i.Regimes,
		&i.TradeTypes,
		&i.ActivatedAt,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getMarketRegimeDay = `-- name: GetMarketRegimeDay :one
SELECT user_id, day, regime, note FROM market_regime_days WHERE user_id = ? AND day = ?
`

type GetMarketRegimeDayParams struct {
	UserID string `json:"user_id"`
	Day    string `json:"day"`
}

func (q *Queries) GetMarketRegimeDay(ctx context.Context, arg GetMarketRegimeDayParams) (MarketRegimeDay, error) {
	row := q.db.QueryRowContext(ctx, getMarketRegimeDay, arg.UserID, arg.Day)
	var i MarketRegimeDay
	err := row.Scan(
		&i.UserID,
		&i.Day,
		&i.Regime,
		&i.Note,
	)
	return i, err
}

const getSystemVersion = `-- name: GetSystemVersion :one
SELECT id, system_id, user_id, label, status, rules, open_questions, regimes, trade_types, activated_at, retired_at, created_at, updated_at, name FROM system_versions WHERE id = ? AND user_id = ?
`

type GetSystemVersionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetSystemVersion(ctx context.Context, arg GetSystemVersionParams) (SystemVersion, error) {
	row := q.db.QueryRowContext(ctx, getSystemVersion, arg.ID, arg.UserID)
	var i SystemVersion
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.UserID,
		&i.Label,
		&i.Status,
		&i.Rules,
		&i.OpenQuestions,
		&i.Regimes,
		&i.TradeTypes,
		&i.ActivatedAt,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getTradeSystemCard = `-- name: GetTradeSystemCard :one
SELECT trade_id, user_id, version_id, regime, trigger_met, trade_type, thesis, planned_hold_days, time_stop_days, exit_state, adherence, checklist, lesson, rule_change, planned_at, created_at, updated_at FROM trade_system_cards WHERE trade_id = ? AND user_id = ?
`

type GetTradeSystemCardParams struct {
	TradeID string `json:"trade_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) GetTradeSystemCard(ctx context.Context, arg GetTradeSystemCardParams) (TradeSystemCard, error) {
	row := q.db.QueryRowContext(ctx, getTradeSystemCard, arg.TradeID, arg.UserID)
	var i TradeSystemCard
	err := row.Scan(
		&i.TradeID,
		&i.UserID,
		&i.VersionID,
		&i.Regime,
		&i.TriggerMet,
		&i.TradeType,
		&i.Thesis,
		&i.PlannedHoldDays,
		&i.TimeStopDays,
		&i.ExitState,
		&i.Adherence,
		&i.Checklist,
		&i.Lesson,
		&i.RuleChange,
		&i.PlannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTradingSystemByUser = `-- name: GetTradingSystemByUser :one
SELECT id, user_id, name, created_at, updated_at FROM trading_systems WHERE user_id = ?
`

func (q *Queries) GetTradingSystemByUser(ctx context.Context, userID string) (TradingSystem, error) {
	row := q.db.QueryRowContext(ctx, getTradingSystemByUser, userID)
	var i TradingSystem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllMarketRegimeDays = `-- name: ListAllMarketRegimeDays :many
SELECT user_id, day, regime, note FROM market_regime_days WHERE user_id = ? ORDER BY day DESC
`

func (q *Queries) ListAllMarketRegimeDays(ctx context.Context, userID string) ([]MarketRegimeDay, error) {
	rows, err := q.db.QueryContext(ctx, listAllMarketRegimeDays, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketRegimeDay
	for rows.Next() {
		var i MarketRegimeDay
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.Regime,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemChanges = `-- name: ListSystemChanges :many
SELECT id, version_id, user_id, decision, reason, note, evidence_trade_ids, created_at FROM system_changes
WHERE user_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListSystemChanges(ctx context.Context, userID string) ([]SystemChange, error) {
	rows, err := q.db.QueryContext(ctx, listSystemChanges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemChange
	for rows.Next() {
		var i SystemChange
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.UserID,
			&i.Decision,
			&i.Reason,
			&i.Note,
			&i.EvidenceTradeIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemChangesForVersion = `-- name: ListSystemChangesForVersion :many
SELECT id, version_id, user_id, decision, reason, note, evidence_trade_ids, created_at FROM system_changes
WHERE version_id = ? AND user_id = ?
ORDER BY created_at ASC, id ASC
`

type ListSystemChangesForVersionParams struct {
	VersionID string `json:"version_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ListSystemChangesForVersion(ctx context.Context, arg ListSystemChangesForVersionParams) ([]SystemChange, error) {
	rows, err := q.db.QueryContext(ctx, listSystemChangesForVersion, arg.VersionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemChange
	for rows.Next() {
		var i SystemChange
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.UserID,
			&i.Decision,
			&i.Reason,
			&i.Note,
			&i.EvidenceTradeIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemVersions = `-- name: ListSystemVersions :many
SELECT id, system_id, user_id, label, status, rules, open_questions, regimes, trade_types, activated_at, retired_at, created_at, updated_at, name FROM system_versions
WHERE user_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListSystemVersions(ctx context.Context, userID string) ([]SystemVersion, error) {
	rows, err := q.db.QueryContext(ctx, listSystemVersions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemVersion
	for rows.Next() {
		var i SystemVersion
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.UserID,
			&i.Label,
			&i.Status,
			&i.Rules,
			&i.OpenQuestions,
			&i.Regimes,
			&i.TradeTypes,
			&i.ActivatedAt,
			&i.RetiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradeSystemCards = `-- name: ListTradeSystemCards :many
SELECT trade_id, user_id, version_id, regime, trigger_met, trade_type, thesis, planned_hold_days, time_stop_days, exit_state, adherence, checklist, lesson, rule_change, planned_at, created_at, updated_at FROM trade_system_cards WHERE user_id = ?
`

func (q *Queries) ListTradeSystemCards(ctx context.Context, userID string) ([]TradeSystemCard, error) {
	rows, err := q.db.QueryContext(ctx, listTradeSystemCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradeSystemCard
	for rows.Next() {
		var i TradeSystemCard
		if err := rows.Scan(
			&i.TradeID,
			&i.UserID,
			&i.VersionID,
			&i.Regime,
			&i.TriggerMet,
			&i.TradeType,
			&i.Thesis,
			&i.PlannedHoldDays,
			&i.TimeStopDays,
			&i.ExitState,
			&i.Adherence,
			&i.Checklist,
			&i.Lesson,
			&i.RuleChange,
			&i.PlannedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameSystemVersion = `-- name: RenameSystemVersion :one
UPDATE system_versions
SET name = ?
WHERE id = ? AND user_id = ?
RETURNING id, system_id, user_id, label, status, rules, open_questions, regimes, trade_types, activated_at, retired_at, created_at, updated_at, name
`

type RenameSystemVersionParams struct {
	Name   string `json:"name"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RenameSystemVersion(ctx context.Context, arg RenameSystemVersionParams) (SystemVersion, error) {
	row := q.db.QueryRowContext(ctx, renameSystemVersion, arg.Name, arg.ID, arg.UserID)
	var i SystemVersion
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.UserID,
		&i.Label,
		&i.Status,
		&i.Rules,
		&i.OpenQuestions,
		&i.Regimes,
		&i.TradeTypes,
		&i.ActivatedAt,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const retireSystemVersion = `-- name: RetireSystemVersion :execrows
UPDATE system_versions
SET status = 'retired', retired_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ? AND status = 'active'
`

type RetireSystemVersionParams struct {
	RetiredAt sql.NullTime `json:"retired_at"`
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
}

func (q *Queries) RetireSystemVersion(ctx context.Context, arg RetireSystemVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retireSystemVersion, arg.RetiredAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSystemVersion = `-- name: UpdateSystemVersion :one
UPDATE system_versions
SET label = ?, rules = ?, open_questions = ?, regimes = ?, trade_types = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ? AND status = 'draft'
RETURNING id, system_id, user_id, label, status, rules, open_questions, regimes, trade_types, activated_at, retired_at, created_at, updated_at, name
`

type UpdateSystemVersionParams struct {
	Label         string `json:"label"`
	Rules         string `json:"rules"`
	OpenQuestions string `json:"open_questions"`
	Regimes       string `json:"regimes"`
	TradeTypes    string `json:"trade_types"`
	ID            string `json:"id"`
	UserID        string `json:"user_id"`
}

func (q *Queries) UpdateSystemVersion(ctx context.Context, arg UpdateSystemVersionParams) (SystemVersion, error) {
	row := q.db.QueryRowContext(ctx, updateSystemVersion,
		arg.Label,
		arg.Rules,
		arg.OpenQuestions,
		arg.Regimes,
		arg.TradeTypes,
		arg.ID,
		arg.UserID,
	)
	var i SystemVersion
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.UserID,
		&i.Label,
		&i.Status,
		&i.Rules,
		&i.OpenQuestions,
		&i.Regimes,
		&i.TradeTypes,
		&i.ActivatedAt,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const upsertMarketRegimeDay = `-- name: UpsertMarketRegimeDay :one
INSERT INTO market_regime_days (user_id, day, regime, note)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, day) DO UPDATE SET
    regime = excluded.regime,
    note = excluded.note
RETURNING user_id, day, regime, note
`

type UpsertMarketRegimeDayParams struct {
	UserID string `json:"user_id"`
	Day    string `json:"day"`
	Regime string `json:"regime"`
	Note   string `json:"note"`
}

func (q *Queries) UpsertMarketRegimeDay(ctx context.Context, arg UpsertMarketRegimeDayParams) (MarketRegimeDay, error) {
	row := q.db.QueryRowContext(ctx, upsertMarketRegimeDay,
		arg.UserID,
		arg.Day,
		arg.Regime,
		arg.Note,
	)
	var i MarketRegimeDay
	err := row.Scan(
		&i.UserID,
		&i.Day,
		&i.Regime,
		&i.Note,
	)
	return i, err
}

const upsertTradeSystemCard = `-- name: UpsertTradeSystemCard :one
INSERT INTO trade_system_cards (
    trade_id, user_id, version_id, regime, trigger_met, trade_type, thesis,
    planned_hold_days, time_stop_days, exit_state, adherence, checklist,
    lesson, rule_change, planned_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (trade_id) DO UPDATE SET
    version_id = excluded.version_id,
    regime = excluded.regime,
    trigger_met = excluded.trigger_met,
    trade_type = excluded.trade_type,
    thesis = excluded.thesis,
    planned_hold_days = excluded.planned_hold_days,
    time_stop_days = excluded.time_stop_days,
    exit_state = excluded.exit_state,
    adherence = excluded.adherence,
    checklist = excluded.checklist,
    lesson = excluded.lesson,
    rule_change = excluded.rule_change,
    planned_at = excluded.planned_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING trade_id, user_id, version_id, regime, trigger_met, trade_type, thesis, planned_hold_days, time_stop_days, exit_state, adherence, checklist, lesson, rule_change, planned_at, created_at, updated_at
`

type UpsertTradeSystemCardParams struct {
	TradeID         string         `json:"trade_id"`
	UserID          string         `json:"user_id"`
	VersionID       sql.NullString `json:"version_id"`
	Regime          string         `json:"regime"`
	TriggerMet      string         `json:"trigger_met"`
	TradeType       string         `json:"trade_type"`
	Thesis          string         `json:"thesis"`
	PlannedHoldDays sql.NullInt64  `json:"planned_hold_days"`
	TimeStopDays    sql.NullInt64  `json:"time_stop_days"`
	ExitState       string         `json:"exit_state"`
	Adherence       string         `json:"adherence"`
	Checklist       string         `json:"checklist"`
	Lesson          string         `json:"lesson"`
	RuleChange      int64          `json:"rule_change"`
	PlannedAt       sql.NullTime   `json:"planned_at"`
}

func (q *Queries) UpsertTradeSystemCard(ctx context.Context, arg UpsertTradeSystemCardParams) (TradeSystemCard, error) {
	row := q.db.QueryRowContext(ctx, upsertTradeSystemCard,
		arg.TradeID,
		arg.UserID,
		arg.VersionID,
		arg.Regime,
		arg.TriggerMet,
		arg.TradeType,
		arg.Thesis,
		arg.PlannedHoldDays,
		arg.TimeStopDays,
		arg.ExitState,
		arg.Adherence,
		arg.Checklist,
		arg.Lesson,
		arg.RuleChange,
		arg.PlannedAt,
	)
	var i TradeSystemCard
	err := row.Scan(
		&i.TradeID,
		&i.UserID,
		&i.VersionID,
		&i.Regime,
		&i.TriggerMet,
		&i.TradeType,
		&i.Thesis,
		&i.PlannedHoldDays,
		&i.TimeStopDays,
		&i.ExitState,
		&i.Adherence,
		&i.Checklist,
		&i.Lesson,
		&i.RuleChange,
		&i.PlannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
