// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trade_journal.sql

package store

import (
	"context"
	"database/sql"
)

const getTradeJournal = `-- name: GetTradeJournal :one
SELECT trade_id, user_id, notes, setup_id, initial_risk, updated_at FROM trade_journal WHERE trade_id = ? AND user_id = ?
`

type GetTradeJournalParams struct {
	TradeID string `json:"trade_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) GetTradeJournal(ctx context.Context, arg GetTradeJournalParams) (TradeJournal, error) {
	row := q.db.QueryRowContext(ctx, getTradeJournal, arg.TradeID, arg.UserID)
	var i TradeJournal
	err := row.Scan(
		&i.TradeID,
		&i.UserID,
		&i.Notes,
		&i.SetupID,
		&i.InitialRisk,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTradeJournal = `-- name: UpsertTradeJournal :exec
INSERT INTO trade_journal (trade_id, user_id, notes, setup_id, initial_risk, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(trade_id) DO UPDATE SET
    notes = excluded.notes, setup_id = excluded.setup_id,
    initial_risk = excluded.initial_risk, updated_at = CURRENT_TIMESTAMP
`

type UpsertTradeJournalParams struct {
	TradeID     string          `json:"trade_id"`
	UserID      string          `json:"user_id"`
	Notes       string          `json:"notes"`
	SetupID     sql.NullString  `json:"setup_id"`
	InitialRisk sql.NullFloat64 `json:"initial_risk"`
}

func (q *Queries) UpsertTradeJournal(ctx context.Context, arg UpsertTradeJournalParams) error {
	_, err := q.db.ExecContext(ctx, upsertTradeJournal,
		arg.TradeID,
		arg.UserID,
		arg.Notes,
		arg.SetupID,
		arg.InitialRisk,
	)
	return err
}
