// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trade_executions.sql

package store

import (
	"context"
)

const getTradeIDForExecution = `-- name: GetTradeIDForExecution :one
SELECT trade_id FROM trade_executions WHERE execution_id = ? LIMIT 1
`

func (q *Queries) GetTradeIDForExecution(ctx context.Context, executionID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTradeIDForExecution, executionID)
	var trade_id string
	err := row.Scan(&trade_id)
	return trade_id, err
}
