// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

/**
 * The formatters that read display prefs at call time. React Compiler caches
 * their results on the arguments alone, so a component that imports them
 * renders amounts that never re-mask when privacy mode flips — see the note in
 * src/lib/format.ts. Screens and components take them from `useFormatters()`.
 */
const PREFS_BOUND_FORMATTERS = [
  'formatPnl',
  'formatPnlCompact',
  'formatCurrency',
  'formatDate',
  'formatDayKey',
  'formatTime',
];

module.exports = defineConfig([
  expoConfig,
  {
    // src/i18n/locales/**/messages.ts are generated by `pnpm i18n:compile`.
    ignores: ["dist/*", "src/i18n/locales/**/messages.ts"],
  },
  {
    files: ['src/app/**/*.tsx', 'src/components/**/*.tsx'],
    rules: {
      'no-restricted-imports': ['error', {
        paths: [
          {
            name: '@/lib/format',
            importNames: PREFS_BOUND_FORMATTERS,
            message:
              'Use useFormatters() — these read display prefs at call time and React Compiler caches their results past a privacy/timezone change (see src/lib/format.ts).',
          },
          {
            name: '@/lib/prefs',
            importNames: ['formatHourKeyLabel'],
            message:
              'Use useFormatters().formatHourKeyLabel — the ambient default is cached past a clock-format change (see src/lib/format.ts).',
          },
        ],
      }],
    },
  },
]);
