// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // src/i18n/locales/**/messages.ts are generated by `pnpm i18n:compile`.
    ignores: ["dist/*", "src/i18n/locales/**/messages.ts"],
  }
]);
