#!/usr/bin/env python3
"""Generate internal/store/pg_adapter.go from store.Querier + storepg."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
querier = (ROOT / "internal/store/querier.go").read_text()
inside = False
sigs = []
for line in querier.splitlines():
    if line.startswith("type Querier interface"):
        inside = True
        continue
    if inside:
        if line.startswith("}"):
            break
        line = line.strip()
        # sqlc copies each query's leading SQL comment above its method.
        if not line or line.startswith("//"):
            continue
        m = re.match(r"^(\w+)\((.*)\) (.+)$", line)
        if not m:
            raise SystemExit(f"bad line: {line}")
        sigs.append((m.group(1), m.group(2), m.group(3)))

store_types = set()
for p in (ROOT / "internal/store").glob("*.go"):
    if p.name.endswith("_test.go") or p.name == "pg_adapter.go":
        continue
    for m in re.finditer(r"^type ([A-Z]\w+) struct", p.read_text(), flags=re.M):
        store_types.add(m.group(1))

# Params where Postgres sqlc emits Null* while SQLite keeps interface{}.
PARAM_CONVERTERS = {
    "ListTradesParams": (
        "storepg.ListTradesParams{\n"
        "\t\tUserID: arg.UserID,\n"
        "\t\tAccountID: ifaceToNullString(arg.AccountID),\n"
        "\t\tStatus: ifaceToNullString(arg.Status),\n"
        "\t}"
    ),
    "ListCashTransactionsParams": (
        "storepg.ListCashTransactionsParams{\n"
        "\t\tUserID: arg.UserID,\n"
        "\t\tAccountID: ifaceToNullString(arg.AccountID),\n"
        "\t}"
    ),
    "ListClosedTradesParams": (
        "storepg.ListClosedTradesParams{\n"
        "\t\tUserID: arg.UserID,\n"
        "\t\tAccountID: ifaceToNullString(arg.AccountID),\n"
        "\t\tFrom: ifaceToNullTime(arg.From),\n"
        "\t\tTo: ifaceToNullTime(arg.To),\n"
        "\t}"
    ),
    "ListJournalNotesParams": (
        "storepg.ListJournalNotesParams{\n"
        "\t\tUserID: arg.UserID,\n"
        "\t\tFromDate: ifaceToNullString(arg.FromDate),\n"
        "\t\tToDate: ifaceToNullString(arg.ToDate),\n"
        "\t}"
    ),
    # LIMIT params: Postgres sqlc types them int32, SQLite int64.
    "ListAccessTokenUsesParams": (
        "storepg.ListAccessTokenUsesParams{\n"
        "\t\tTokenID: arg.TokenID,\n"
        "\t\tUserID: arg.UserID,\n"
        "\t\tLimit: int32(arg.Limit),\n"
        "\t}"
    ),
    "PruneAccessTokenUsesParams": (
        "storepg.PruneAccessTokenUsesParams{\n"
        "\t\tTokenID: arg.TokenID,\n"
        "\t\tTokenID_2: arg.TokenID_2,\n"
        "\t\tLimit: int32(arg.Limit),\n"
        "\t}"
    ),
    "ListTradesMissingExcursionParams": (
        "storepg.ListTradesMissingExcursionParams{\n"
        "\t\tPostCutoff: arg.PostCutoff,\n"
        "\t\tPostFloor: arg.PostFloor,\n"
        "\t\tRowLimit: int32(arg.RowLimit),\n"
        "\t}"
    ),
    "ListAlertEventsParams": (
        "storepg.ListAlertEventsParams{\n"
        "\t\tUserID: arg.UserID,\n"
        "\t\tLimit: int32(arg.Limit),\n"
        "\t}"
    ),
}
def convert_value(expr: str, typ: str, to_pg: bool) -> str:
    typ = typ.strip()
    if to_pg and typ in PARAM_CONVERTERS and expr == "arg":
        return PARAM_CONVERTERS[typ]
    if typ.startswith("[]"):
        inner = typ[2:]
        if inner in store_types:
            if to_pg:
                return (
                    f"func() []storepg.{inner} {{ in := {expr}; out := make([]storepg.{inner}, len(in)); "
                    f"for i := range in {{ out[i] = storepg.{inner}(in[i]) }}; return out }}()"
                )
            return (
                f"func() []{inner} {{ in := {expr}; out := make([]{inner}, len(in)); "
                f"for i := range in {{ out[i] = {inner}(in[i]) }}; return out }}()"
            )
        return expr
    if typ in store_types:
        return f"storepg.{typ}({expr})" if to_pg else f"{typ}({expr})"
    return expr

out = [
    "// Code generated by scripts/gen_pg_adapter.py; DO NOT EDIT.",
    "package store",
    "",
    "import (",
    '\t"context"',
    '\t"database/sql"',
    "",
    '\t"github.com/tradermemos/api/internal/storepg"',
    ")",
    "",
    "// PG adapts storepg.Queries to the store.Querier interface.",
    "// db is the same handle storepg holds, kept for the hand-written set-at-a-time",
    "// statements in bulk.go that sqlc cannot express.",
    "type PG struct {",
    "\tq  *storepg.Queries",
    "\tdb DBTX",
    "}",
    "",
    "// NewPG wraps a Postgres sqlc Queries as store.Querier.",
    "func NewPG(conn *sql.DB) *PG {",
    "\treturn NewPGFromDBTX(conn)",
    "}",
    "",
    "// NewPGFromDBTX wraps any Postgres handle — a *sql.DB or an open *sql.Tx.",
    "func NewPGFromDBTX(db DBTX) *PG {",
    "\treturn &PG{q: storepg.New(db), db: db}",
    "}",
    "",
    "var _ Querier = (*PG)(nil)",
    "",
]

for name, params, ret in sigs:
    param_list = []
    if params.strip():
        for part in params.split(","):
            part = part.strip()
            bits = part.rsplit(" ", 1)
            param_list.append((bits[0], bits[1]))
    out.append(f"func (p *PG) {name}({params}) {ret} {{")
    call_args = []
    for pname, ptype in param_list:
        if pname == "ctx":
            call_args.append("ctx")
        elif ptype in store_types:
            call_args.append(convert_value(pname, ptype, True))
        else:
            call_args.append(pname)
    call = f"p.q.{name}({', '.join(call_args)})"
    ret = ret.strip()
    if ret == "error":
        out.append(f"\treturn {call}")
    elif ret.startswith("(") and ret.endswith(")"):
        parts = [x.strip() for x in ret[1:-1].split(",")]
        if len(parts) == 2 and parts[1] == "error":
            r0 = parts[0]
            if r0 in store_types or r0.startswith("[]"):
                out.append(f"\tv, err := {call}")
                out.append("\tif err != nil {")
                zero = "nil" if r0.startswith("[]") else f"{r0}{{}}"
                out.append(f"\t\treturn {zero}, err")
                out.append("\t}")
                out.append(f"\treturn {convert_value('v', r0, False)}, nil")
            else:
                out.append(f"\treturn {call}")
        else:
            out.append(f"\treturn {call}")
    else:
        out.append(f"\treturn {call}")
    out.append("}")
    out.append("")

path = ROOT / "internal/store/pg_adapter.go"
path.write_text("\n".join(out))
print(f"wrote {path} ({len(sigs)} methods)")

