/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EventsRouteImport } from './routes/events'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as DayDateRouteImport } from './routes/day.$date'
import { Route as TradesIndexRouteImport } from './routes/trades.index'
import { Route as TradesIdRouteImport } from './routes/trades.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDateRoute = DayDateRouteImport.update({
  id: '/day/$date',
  path: '/day/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TradesRoute,
} as any)
const TradesIdRoute = TradesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TradesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/calendar': typeof CalendarRoute
  '/chart': typeof ChartRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/heatmap': typeof HeatmapRoute
  '/home': typeof HomeRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/playbook': typeof PlaybookRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/trades': typeof TradesRouteWithChildren
  '/wrapped': typeof WrappedRoute
  '/day/$date': typeof DayDateRoute
  '/trades/$id': typeof TradesIdRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/calendar': typeof CalendarRoute
  '/chart': typeof ChartRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/heatmap': typeof HeatmapRoute
  '/home': typeof HomeRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/playbook': typeof PlaybookRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/wrapped': typeof WrappedRoute
  '/day/$date': typeof DayDateRoute
  '/trades/$id': typeof TradesIdRoute
  '/trades': typeof TradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/calendar': typeof CalendarRoute
  '/chart': typeof ChartRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/heatmap': typeof HeatmapRoute
  '/home': typeof HomeRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/playbook': typeof PlaybookRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/trades': typeof TradesRouteWithChildren
  '/wrapped': typeof WrappedRoute
  '/day/$date': typeof DayDateRoute
  '/trades/$id': typeof TradesIdRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/calendar'
    | '/chart'
    | '/dashboard'
    | '/events'
    | '/heatmap'
    | '/home'
    | '/import'
    | '/login'
    | '/notes'
    | '/playbook'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/trades'
    | '/wrapped'
    | '/day/$date'
    | '/trades/$id'
    | '/trades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/calendar'
    | '/chart'
    | '/dashboard'
    | '/events'
    | '/heatmap'
    | '/home'
    | '/import'
    | '/login'
    | '/notes'
    | '/playbook'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/wrapped'
    | '/day/$date'
    | '/trades/$id'
    | '/trades'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/calendar'
    | '/chart'
    | '/dashboard'
    | '/events'
    | '/heatmap'
    | '/home'
    | '/import'
    | '/login'
    | '/notes'
    | '/playbook'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/trades'
    | '/wrapped'
    | '/day/$date'
    | '/trades/$id'
    | '/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  CalendarRoute: typeof CalendarRoute
  ChartRoute: typeof ChartRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  HeatmapRoute: typeof HeatmapRoute
  HomeRoute: typeof HomeRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  PlaybookRoute: typeof PlaybookRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TradesRoute: typeof TradesRouteWithChildren
  WrappedRoute: typeof WrappedRoute
  DayDateRoute: typeof DayDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$date': {
      id: '/day/$date'
      path: '/day/$date'
      fullPath: '/day/$date'
      preLoaderRoute: typeof DayDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/'
      fullPath: '/trades/'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof TradesRoute
    }
    '/trades/$id': {
      id: '/trades/$id'
      path: '/$id'
      fullPath: '/trades/$id'
      preLoaderRoute: typeof TradesIdRouteImport
      parentRoute: typeof TradesRoute
    }
  }
}

interface TradesRouteChildren {
  TradesIdRoute: typeof TradesIdRoute
  TradesIndexRoute: typeof TradesIndexRoute
}

const TradesRouteChildren: TradesRouteChildren = {
  TradesIdRoute: TradesIdRoute,
  TradesIndexRoute: TradesIndexRoute,
}

const TradesRouteWithChildren =
  TradesRoute._addFileChildren(TradesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  CalendarRoute: CalendarRoute,
  ChartRoute: ChartRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  HeatmapRoute: HeatmapRoute,
  HomeRoute: HomeRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  PlaybookRoute: PlaybookRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TradesRoute: TradesRouteWithChildren,
  WrappedRoute: WrappedRoute,
  DayDateRoute: DayDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
