ALTER TABLE setups ADD COLUMN thesis TEXT NOT NULL DEFAULT '';
ALTER TABLE setups ADD COLUMN symbol TEXT NOT NULL DEFAULT '';
ALTER TABLE setups ADD COLUMN direction TEXT NOT NULL DEFAULT '';
ALTER TABLE setups ADD COLUMN target_price REAL;
ALTER TABLE setups ADD COLUMN stop_price REAL;
ALTER TABLE setups ADD COLUMN checklist TEXT NOT NULL DEFAULT '[]';
