// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_tokens.sql

package storepg

import (
	"context"
	"database/sql"
)

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO access_tokens (
    id, user_id, name, token_prefix, token_hash, expires_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP
) RETURNING id, user_id, name, token_prefix, token_hash, expires_at, last_used_at, created_at, revoked_at
`

type CreateAccessTokenParams struct {
	ID          string       `json:"id"`
	UserID      string       `json:"user_id"`
	Name        string       `json:"name"`
	TokenPrefix string       `json:"token_prefix"`
	TokenHash   string       `json:"token_hash"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error) {
	row := q.db.QueryRowContext(ctx, createAccessToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAccessTokenByHash = `-- name: GetAccessTokenByHash :one
SELECT id, user_id, name, token_prefix, token_hash, expires_at, last_used_at, created_at, revoked_at
FROM access_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAccessTokenByHash(ctx context.Context, tokenHash string) (AccessToken, error) {
	row := q.db.QueryRowContext(ctx, getAccessTokenByHash, tokenHash)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAccessTokensByUser = `-- name: ListAccessTokensByUser :many
SELECT id, user_id, name, token_prefix, token_hash, expires_at, last_used_at, created_at, revoked_at
FROM access_tokens
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAccessTokensByUser(ctx context.Context, userID string) ([]AccessToken, error) {
	rows, err := q.db.QueryContext(ctx, listAccessTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessToken
	for rows.Next() {
		var i AccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenPrefix,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessToken = `-- name: RevokeAccessToken :execrows
UPDATE access_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAccessTokenParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAccessToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAccessTokenLastUsed = `-- name: TouchAccessTokenLastUsed :exec
UPDATE access_tokens
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) TouchAccessTokenLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchAccessTokenLastUsed, id)
	return err
}
