// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package storepg

import (
	"context"
)

const deleteAttachment = `-- name: DeleteAttachment :execrows
DELETE FROM trade_attachments WHERE id = $1 AND user_id = $2
`

type DeleteAttachmentParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAttachment, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMediaFile = `-- name: DeleteMediaFile :execrows
DELETE FROM media_files WHERE id = $1 AND user_id = $2
`

type DeleteMediaFileParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteMediaFile(ctx context.Context, arg DeleteMediaFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMediaFile, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, user_id, trade_id, filename, content_type, size_bytes, storage_key, created_at FROM trade_attachments WHERE id = $1 AND user_id = $2
`

type GetAttachmentParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (TradeAttachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachment, arg.ID, arg.UserID)
	var i TradeAttachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TradeID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaFile = `-- name: GetMediaFile :one
SELECT id, user_id, filename, content_type, size_bytes, storage_key, created_at FROM media_files WHERE id = $1 AND user_id = $2
`

type GetMediaFileParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetMediaFile(ctx context.Context, arg GetMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRowContext(ctx, getMediaFile, arg.ID, arg.UserID)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO trade_attachments (id, user_id, trade_id, filename, content_type, size_bytes, storage_key)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, trade_id, filename, content_type, size_bytes, storage_key, created_at
`

type InsertAttachmentParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	TradeID     string `json:"trade_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
	StorageKey  string `json:"storage_key"`
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (TradeAttachment, error) {
	row := q.db.QueryRowContext(ctx, insertAttachment,
		arg.ID,
		arg.UserID,
		arg.TradeID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i TradeAttachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TradeID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertMediaFile = `-- name: InsertMediaFile :one
INSERT INTO media_files (id, user_id, filename, content_type, size_bytes, storage_key)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, filename, content_type, size_bytes, storage_key, created_at
`

type InsertMediaFileParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
	StorageKey  string `json:"storage_key"`
}

func (q *Queries) InsertMediaFile(ctx context.Context, arg InsertMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRowContext(ctx, insertMediaFile,
		arg.ID,
		arg.UserID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsForAccount = `-- name: ListAttachmentsForAccount :many
SELECT a.id, a.user_id, a.trade_id, a.filename, a.content_type, a.size_bytes, a.storage_key, a.created_at FROM trade_attachments a
INNER JOIN trades t ON t.id = a.trade_id
WHERE a.user_id = $1 AND t.account_id = $2
ORDER BY a.created_at
`

type ListAttachmentsForAccountParams struct {
	UserID    string `json:"user_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) ListAttachmentsForAccount(ctx context.Context, arg ListAttachmentsForAccountParams) ([]TradeAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsForAccount, arg.UserID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradeAttachment
	for rows.Next() {
		var i TradeAttachment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TradeID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsForTrade = `-- name: ListAttachmentsForTrade :many
SELECT id, user_id, trade_id, filename, content_type, size_bytes, storage_key, created_at FROM trade_attachments WHERE trade_id = $1 AND user_id = $2 ORDER BY created_at
`

type ListAttachmentsForTradeParams struct {
	TradeID string `json:"trade_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) ListAttachmentsForTrade(ctx context.Context, arg ListAttachmentsForTradeParams) ([]TradeAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsForTrade, arg.TradeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradeAttachment
	for rows.Next() {
		var i TradeAttachment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TradeID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaFilesForUser = `-- name: ListMediaFilesForUser :many
SELECT id, user_id, filename, content_type, size_bytes, storage_key, created_at FROM media_files WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListMediaFilesForUser(ctx context.Context, userID string) ([]MediaFile, error) {
	rows, err := q.db.QueryContext(ctx, listMediaFilesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
