// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coach_reviews.sql

package storepg

import (
	"context"
)

const createCoachReview = `-- name: CreateCoachReview :one
INSERT INTO coach_reviews (id, user_id, trade_id, model, notes, next_action)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, trade_id, model, notes, next_action, created_at
`

type CreateCoachReviewParams struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	TradeID    string `json:"trade_id"`
	Model      string `json:"model"`
	Notes      string `json:"notes"`
	NextAction string `json:"next_action"`
}

func (q *Queries) CreateCoachReview(ctx context.Context, arg CreateCoachReviewParams) (CoachReview, error) {
	row := q.db.QueryRowContext(ctx, createCoachReview,
		arg.ID,
		arg.UserID,
		arg.TradeID,
		arg.Model,
		arg.Notes,
		arg.NextAction,
	)
	var i CoachReview
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TradeID,
		&i.Model,
		&i.Notes,
		&i.NextAction,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCoachReview = `-- name: DeleteCoachReview :execrows
DELETE FROM coach_reviews WHERE id = $1 AND user_id = $2
`

type DeleteCoachReviewParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteCoachReview(ctx context.Context, arg DeleteCoachReviewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCoachReview, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listCoachReviews = `-- name: ListCoachReviews :many
SELECT id, user_id, trade_id, model, notes, next_action, created_at FROM coach_reviews
WHERE user_id = $1 AND trade_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListCoachReviewsParams struct {
	UserID  string `json:"user_id"`
	TradeID string `json:"trade_id"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListCoachReviews(ctx context.Context, arg ListCoachReviewsParams) ([]CoachReview, error) {
	rows, err := q.db.QueryContext(ctx, listCoachReviews, arg.UserID, arg.TradeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachReview
	for rows.Next() {
		var i CoachReview
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TradeID,
			&i.Model,
			&i.Notes,
			&i.NextAction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
