// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: imports.sql

package storepg

import (
	"context"
	"database/sql"
)

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batches (id, user_id, account_id, source, filename, column_mapping, row_count, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, user_id, account_id, source, filename, column_mapping, row_count, status, created_at
`

type CreateImportBatchParams struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	AccountID     string         `json:"account_id"`
	Source        string         `json:"source"`
	Filename      sql.NullString `json:"filename"`
	ColumnMapping sql.NullString `json:"column_mapping"`
	RowCount      int64          `json:"row_count"`
	Status        string         `json:"status"`
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRowContext(ctx, createImportBatch,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.Source,
		arg.Filename,
		arg.ColumnMapping,
		arg.RowCount,
		arg.Status,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Source,
		&i.Filename,
		&i.ColumnMapping,
		&i.RowCount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getImportBatch = `-- name: GetImportBatch :one
SELECT id, user_id, account_id, source, filename, column_mapping, row_count, status, created_at FROM import_batches WHERE id = $1 AND user_id = $2
`

type GetImportBatchParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetImportBatch(ctx context.Context, arg GetImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRowContext(ctx, getImportBatch, arg.ID, arg.UserID)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Source,
		&i.Filename,
		&i.ColumnMapping,
		&i.RowCount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listImportBatches = `-- name: ListImportBatches :many
SELECT id, user_id, account_id, source, filename, column_mapping, row_count, status, created_at FROM import_batches WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListImportBatches(ctx context.Context, userID string) ([]ImportBatch, error) {
	rows, err := q.db.QueryContext(ctx, listImportBatches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportBatch
	for rows.Next() {
		var i ImportBatch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Source,
			&i.Filename,
			&i.ColumnMapping,
			&i.RowCount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setImportBatchStatus = `-- name: SetImportBatchStatus :exec
UPDATE import_batches SET status = $1 WHERE id = $2 AND user_id = $3
`

type SetImportBatchStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SetImportBatchStatus(ctx context.Context, arg SetImportBatchStatusParams) error {
	_, err := q.db.ExecContext(ctx, setImportBatchStatus, arg.Status, arg.ID, arg.UserID)
	return err
}
