// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package storepg

import (
	"context"
)

const listTradesMissingExcursion = `-- name: ListTradesMissingExcursion :many
SELECT t.id, t.user_id, t.account_id, t.symbol, t.instrument_type, t.direction, t.status, t.opened_at, t.closed_at, t.qty_opened, t.avg_entry_price, t.avg_exit_price, t.gross_pnl, t.fees_total, t.net_pnl, t.pnl_currency, t.return_pct, t.r_multiple, t.time_in_trade_secs, t.notes, t.created_at, t.updated_at, t.qty_remaining FROM trades t
LEFT JOIN trade_journal j ON j.trade_id = t.id
WHERE t.status = 'closed' AND t.instrument_type != 'option'
  AND (j.trade_id IS NULL OR j.mfe IS NULL)
ORDER BY t.closed_at DESC
LIMIT $1
`

// Closed, chart-eligible trades with no recorded MFE, newest first. Options
// are excluded up front: bars for OCC symbols chart the underlying, so auto
// excursion would mislead (same rule as the excursion endpoint).
func (q *Queries) ListTradesMissingExcursion(ctx context.Context, limit int32) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, listTradesMissingExcursion, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Symbol,
			&i.InstrumentType,
			&i.Direction,
			&i.Status,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.QtyOpened,
			&i.AvgEntryPrice,
			&i.AvgExitPrice,
			&i.GrossPnl,
			&i.FeesTotal,
			&i.NetPnl,
			&i.PnlCurrency,
			&i.ReturnPct,
			&i.RMultiple,
			&i.TimeInTradeSecs,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QtyRemaining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
