// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_notes.sql

package storepg

import (
	"context"
	"database/sql"
)

const createJournalNote = `-- name: CreateJournalNote :one
INSERT INTO journal_notes (id, user_id, occurred_at, title, body, symbols, note_type, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, occurred_at, title, body, created_at, updated_at, symbols, note_type
`

type CreateJournalNoteParams struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	OccurredAt string `json:"occurred_at"`
	Title      string `json:"title"`
	Body       string `json:"body"`
	Symbols    string `json:"symbols"`
	NoteType   string `json:"note_type"`
}

func (q *Queries) CreateJournalNote(ctx context.Context, arg CreateJournalNoteParams) (JournalNote, error) {
	row := q.db.QueryRowContext(ctx, createJournalNote,
		arg.ID,
		arg.UserID,
		arg.OccurredAt,
		arg.Title,
		arg.Body,
		arg.Symbols,
		arg.NoteType,
	)
	var i JournalNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OccurredAt,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Symbols,
		&i.NoteType,
	)
	return i, err
}

const deleteJournalNote = `-- name: DeleteJournalNote :execrows
DELETE FROM journal_notes WHERE id = $1 AND user_id = $2
`

type DeleteJournalNoteParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteJournalNote(ctx context.Context, arg DeleteJournalNoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteJournalNote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChecklistTemplate = `-- name: GetChecklistTemplate :one
SELECT user_id, items, updated_at, content FROM checklist_templates WHERE user_id = $1
`

func (q *Queries) GetChecklistTemplate(ctx context.Context, userID string) (ChecklistTemplate, error) {
	row := q.db.QueryRowContext(ctx, getChecklistTemplate, userID)
	var i ChecklistTemplate
	err := row.Scan(
		&i.UserID,
		&i.Items,
		&i.UpdatedAt,
		&i.Content,
	)
	return i, err
}

const getJournalNote = `-- name: GetJournalNote :one
SELECT id, user_id, occurred_at, title, body, created_at, updated_at, symbols, note_type FROM journal_notes WHERE id = $1 AND user_id = $2
`

type GetJournalNoteParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetJournalNote(ctx context.Context, arg GetJournalNoteParams) (JournalNote, error) {
	row := q.db.QueryRowContext(ctx, getJournalNote, arg.ID, arg.UserID)
	var i JournalNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OccurredAt,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Symbols,
		&i.NoteType,
	)
	return i, err
}

const listJournalNotes = `-- name: ListJournalNotes :many
SELECT id, user_id, occurred_at, title, body, created_at, updated_at, symbols, note_type FROM journal_notes
WHERE user_id = $1
  AND (occurred_at >= COALESCE($2::text, occurred_at))
  AND (occurred_at <= COALESCE($3::text, occurred_at))
ORDER BY occurred_at DESC, created_at DESC
`

type ListJournalNotesParams struct {
	UserID   string         `json:"user_id"`
	FromDate sql.NullString `json:"from_date"`
	ToDate   sql.NullString `json:"to_date"`
}

func (q *Queries) ListJournalNotes(ctx context.Context, arg ListJournalNotesParams) ([]JournalNote, error) {
	rows, err := q.db.QueryContext(ctx, listJournalNotes, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalNote
	for rows.Next() {
		var i JournalNote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OccurredAt,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Symbols,
			&i.NoteType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJournalNote = `-- name: UpdateJournalNote :one
UPDATE journal_notes
SET occurred_at = $1, title = $2, body = $3, symbols = $4, note_type = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, occurred_at, title, body, created_at, updated_at, symbols, note_type
`

type UpdateJournalNoteParams struct {
	OccurredAt string `json:"occurred_at"`
	Title      string `json:"title"`
	Body       string `json:"body"`
	Symbols    string `json:"symbols"`
	NoteType   string `json:"note_type"`
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) UpdateJournalNote(ctx context.Context, arg UpdateJournalNoteParams) (JournalNote, error) {
	row := q.db.QueryRowContext(ctx, updateJournalNote,
		arg.OccurredAt,
		arg.Title,
		arg.Body,
		arg.Symbols,
		arg.NoteType,
		arg.ID,
		arg.UserID,
	)
	var i JournalNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OccurredAt,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Symbols,
		&i.NoteType,
	)
	return i, err
}

const upsertChecklistTemplate = `-- name: UpsertChecklistTemplate :one
INSERT INTO checklist_templates (user_id, items, content, updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
    items = excluded.items,
    content = excluded.content,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, items, updated_at, content
`

type UpsertChecklistTemplateParams struct {
	UserID  string `json:"user_id"`
	Items   string `json:"items"`
	Content string `json:"content"`
}

func (q *Queries) UpsertChecklistTemplate(ctx context.Context, arg UpsertChecklistTemplateParams) (ChecklistTemplate, error) {
	row := q.db.QueryRowContext(ctx, upsertChecklistTemplate, arg.UserID, arg.Items, arg.Content)
	var i ChecklistTemplate
	err := row.Scan(
		&i.UserID,
		&i.Items,
		&i.UpdatedAt,
		&i.Content,
	)
	return i, err
}
