// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: market_bars.sql

package storepg

import (
	"context"
	"database/sql"
)

const getMarketBarsCache = `-- name: GetMarketBarsCache :one
SELECT cache_key, symbol, interval, from_ts, to_ts, bars_json, provider, fetched_at, expires_at
FROM market_bars_cache
WHERE cache_key = $1
`

func (q *Queries) GetMarketBarsCache(ctx context.Context, cacheKey string) (MarketBarsCache, error) {
	row := q.db.QueryRowContext(ctx, getMarketBarsCache, cacheKey)
	var i MarketBarsCache
	err := row.Scan(
		&i.CacheKey,
		&i.Symbol,
		&i.Interval,
		&i.FromTs,
		&i.ToTs,
		&i.BarsJson,
		&i.Provider,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertMarketBarsCache = `-- name: UpsertMarketBarsCache :exec
INSERT INTO market_bars_cache (
    cache_key, symbol, interval, from_ts, to_ts, bars_json, provider, fetched_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT(cache_key) DO UPDATE SET
    bars_json = excluded.bars_json,
    provider = excluded.provider,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at
`

type UpsertMarketBarsCacheParams struct {
	CacheKey  string         `json:"cache_key"`
	Symbol    string         `json:"symbol"`
	Interval  string         `json:"interval"`
	FromTs    string         `json:"from_ts"`
	ToTs      string         `json:"to_ts"`
	BarsJson  []byte         `json:"bars_json"`
	Provider  string         `json:"provider"`
	FetchedAt string         `json:"fetched_at"`
	ExpiresAt sql.NullString `json:"expires_at"`
}

func (q *Queries) UpsertMarketBarsCache(ctx context.Context, arg UpsertMarketBarsCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketBarsCache,
		arg.CacheKey,
		arg.Symbol,
		arg.Interval,
		arg.FromTs,
		arg.ToTs,
		arg.BarsJson,
		arg.Provider,
		arg.FetchedAt,
		arg.ExpiresAt,
	)
	return err
}
