// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: missed_trades.sql

package storepg

import (
	"context"
	"database/sql"
	"time"
)

const createMissedTrade = `-- name: CreateMissedTrade :one
INSERT INTO missed_trades (
    id, user_id, account_id, setup_id, symbol, direction, observed_at,
    entry, stop, target, reason, outcome, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, account_id, setup_id, symbol, direction, observed_at, entry, stop, target, reason, outcome, notes, created_at, updated_at
`

type CreateMissedTradeParams struct {
	ID         string          `json:"id"`
	UserID     string          `json:"user_id"`
	AccountID  sql.NullString  `json:"account_id"`
	SetupID    sql.NullString  `json:"setup_id"`
	Symbol     string          `json:"symbol"`
	Direction  string          `json:"direction"`
	ObservedAt time.Time       `json:"observed_at"`
	Entry      sql.NullFloat64 `json:"entry"`
	Stop       sql.NullFloat64 `json:"stop"`
	Target     sql.NullFloat64 `json:"target"`
	Reason     string          `json:"reason"`
	Outcome    string          `json:"outcome"`
	Notes      string          `json:"notes"`
}

func (q *Queries) CreateMissedTrade(ctx context.Context, arg CreateMissedTradeParams) (MissedTrade, error) {
	row := q.db.QueryRowContext(ctx, createMissedTrade,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.SetupID,
		arg.Symbol,
		arg.Direction,
		arg.ObservedAt,
		arg.Entry,
		arg.Stop,
		arg.Target,
		arg.Reason,
		arg.Outcome,
		arg.Notes,
	)
	var i MissedTrade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.SetupID,
		&i.Symbol,
		&i.Direction,
		&i.ObservedAt,
		&i.Entry,
		&i.Stop,
		&i.Target,
		&i.Reason,
		&i.Outcome,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMissedTrade = `-- name: DeleteMissedTrade :execrows
DELETE FROM missed_trades WHERE id = $1 AND user_id = $2
`

type DeleteMissedTradeParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteMissedTrade(ctx context.Context, arg DeleteMissedTradeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMissedTrade, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMissedTrade = `-- name: GetMissedTrade :one
SELECT id, user_id, account_id, setup_id, symbol, direction, observed_at, entry, stop, target, reason, outcome, notes, created_at, updated_at FROM missed_trades WHERE id = $1 AND user_id = $2
`

type GetMissedTradeParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetMissedTrade(ctx context.Context, arg GetMissedTradeParams) (MissedTrade, error) {
	row := q.db.QueryRowContext(ctx, getMissedTrade, arg.ID, arg.UserID)
	var i MissedTrade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.SetupID,
		&i.Symbol,
		&i.Direction,
		&i.ObservedAt,
		&i.Entry,
		&i.Stop,
		&i.Target,
		&i.Reason,
		&i.Outcome,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMissedTrades = `-- name: ListMissedTrades :many
SELECT id, user_id, account_id, setup_id, symbol, direction, observed_at, entry, stop, target, reason, outcome, notes, created_at, updated_at FROM missed_trades
WHERE user_id = $1
ORDER BY observed_at DESC, created_at DESC, id
`

func (q *Queries) ListMissedTrades(ctx context.Context, userID string) ([]MissedTrade, error) {
	rows, err := q.db.QueryContext(ctx, listMissedTrades, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MissedTrade
	for rows.Next() {
		var i MissedTrade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.SetupID,
			&i.Symbol,
			&i.Direction,
			&i.ObservedAt,
			&i.Entry,
			&i.Stop,
			&i.Target,
			&i.Reason,
			&i.Outcome,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMissedTrade = `-- name: UpdateMissedTrade :one
UPDATE missed_trades
SET account_id = $1, setup_id = $2, symbol = $3, direction = $4, observed_at = $5,
    entry = $6, stop = $7, target = $8, reason = $9, outcome = $10, notes = $11,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $12 AND user_id = $13
RETURNING id, user_id, account_id, setup_id, symbol, direction, observed_at, entry, stop, target, reason, outcome, notes, created_at, updated_at
`

type UpdateMissedTradeParams struct {
	AccountID  sql.NullString  `json:"account_id"`
	SetupID    sql.NullString  `json:"setup_id"`
	Symbol     string          `json:"symbol"`
	Direction  string          `json:"direction"`
	ObservedAt time.Time       `json:"observed_at"`
	Entry      sql.NullFloat64 `json:"entry"`
	Stop       sql.NullFloat64 `json:"stop"`
	Target     sql.NullFloat64 `json:"target"`
	Reason     string          `json:"reason"`
	Outcome    string          `json:"outcome"`
	Notes      string          `json:"notes"`
	ID         string          `json:"id"`
	UserID     string          `json:"user_id"`
}

func (q *Queries) UpdateMissedTrade(ctx context.Context, arg UpdateMissedTradeParams) (MissedTrade, error) {
	row := q.db.QueryRowContext(ctx, updateMissedTrade,
		arg.AccountID,
		arg.SetupID,
		arg.Symbol,
		arg.Direction,
		arg.ObservedAt,
		arg.Entry,
		arg.Stop,
		arg.Target,
		arg.Reason,
		arg.Outcome,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i MissedTrade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.SetupID,
		&i.Symbol,
		&i.Direction,
		&i.ObservedAt,
		&i.Entry,
		&i.Stop,
		&i.Target,
		&i.Reason,
		&i.Outcome,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
