// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storepg

import (
	"database/sql"
	"time"
)

type AccessToken struct {
	ID          string       `json:"id"`
	UserID      string       `json:"user_id"`
	Name        string       `json:"name"`
	TokenPrefix string       `json:"token_prefix"`
	TokenHash   string       `json:"token_hash"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
	LastUsedAt  sql.NullTime `json:"last_used_at"`
	CreatedAt   time.Time    `json:"created_at"`
	RevokedAt   sql.NullTime `json:"revoked_at"`
}

type AccessTokenUse struct {
	ID        string    `json:"id"`
	TokenID   string    `json:"token_id"`
	UsedAt    time.Time `json:"used_at"`
	Ip        string    `json:"ip"`
	UserAgent string    `json:"user_agent"`
}

type Account struct {
	ID              string    `json:"id"`
	UserID          string    `json:"user_id"`
	Name            string    `json:"name"`
	Broker          string    `json:"broker"`
	AccountType     string    `json:"account_type"`
	BaseCurrency    string    `json:"base_currency"`
	StartingBalance float64   `json:"starting_balance"`
	CreatedAt       time.Time `json:"created_at"`
}

type AlertChannel struct {
	ID         string       `json:"id"`
	UserID     string       `json:"user_id"`
	Kind       string       `json:"kind"`
	Target     string       `json:"target"`
	Label      string       `json:"label"`
	Enabled    int64        `json:"enabled"`
	LastSentAt sql.NullTime `json:"last_sent_at"`
	LastStatus string       `json:"last_status"`
	LastError  string       `json:"last_error"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

type AlertEvent struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Rule      string    `json:"rule"`
	DedupeKey string    `json:"dedupe_key"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	FiredAt   time.Time `json:"fired_at"`
}

type AlertSetting struct {
	UserID           string    `json:"user_id"`
	Enabled          int64     `json:"enabled"`
	Timezone         string    `json:"timezone"`
	RuleRisk         int64     `json:"rule_risk"`
	RuleDailyLoss    int64     `json:"rule_daily_loss"`
	RuleLossStreak   int64     `json:"rule_loss_streak"`
	LossStreakN      int64     `json:"loss_streak_n"`
	RulePropDrawdown int64     `json:"rule_prop_drawdown"`
	PropWarnPct      float64   `json:"prop_warn_pct"`
	RuleUnreviewed   int64     `json:"rule_unreviewed"`
	UnreviewedDays   int64     `json:"unreviewed_days"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type AnnualGoal struct {
	UserID    string    `json:"user_id"`
	Year      int64     `json:"year"`
	Amount    float64   `json:"amount"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CashTransaction struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	AccountID     string         `json:"account_id"`
	Type          string         `json:"type"`
	Amount        float64        `json:"amount"`
	Currency      string         `json:"currency"`
	OccurredAt    time.Time      `json:"occurred_at"`
	Note          string         `json:"note"`
	ImportBatchID sql.NullString `json:"import_batch_id"`
	CreatedAt     time.Time      `json:"created_at"`
	TradeID       sql.NullString `json:"trade_id"`
}

type ChecklistTemplate struct {
	UserID    string    `json:"user_id"`
	Items     string    `json:"items"`
	UpdatedAt time.Time `json:"updated_at"`
	Content   string    `json:"content"`
}

type CoachSetting struct {
	ID           int64     `json:"id"`
	Enabled      int64     `json:"enabled"`
	BaseUrl      string    `json:"base_url"`
	ApiKey       string    `json:"api_key"`
	Model        string    `json:"model"`
	CustomPrompt string    `json:"custom_prompt"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type EconomicEvent struct {
	ID        int64  `json:"id"`
	Provider  string `json:"provider"`
	Title     string `json:"title"`
	Country   string `json:"country"`
	Impact    string `json:"impact"`
	EventTs   string `json:"event_ts"`
	Forecast  string `json:"forecast"`
	Previous  string `json:"previous"`
	Actual    string `json:"actual"`
	FetchedAt string `json:"fetched_at"`
}

type Execution struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	AccountID      string         `json:"account_id"`
	ExternalID     sql.NullString `json:"external_id"`
	Symbol         string         `json:"symbol"`
	InstrumentType string         `json:"instrument_type"`
	Side           string         `json:"side"`
	Quantity       float64        `json:"quantity"`
	Price          float64        `json:"price"`
	Fees           float64        `json:"fees"`
	Commission     float64        `json:"commission"`
	ExecutedAt     time.Time      `json:"executed_at"`
	Multiplier     float64        `json:"multiplier"`
	Details        sql.NullString `json:"details"`
	ImportBatchID  sql.NullString `json:"import_batch_id"`
	DedupHash      string         `json:"dedup_hash"`
	CreatedAt      time.Time      `json:"created_at"`
}

type FlexSyncSetting struct {
	AccountID    string       `json:"account_id"`
	UserID       string       `json:"user_id"`
	Token        string       `json:"token"`
	QueryID      string       `json:"query_id"`
	Enabled      int64        `json:"enabled"`
	LastSyncedAt sql.NullTime `json:"last_synced_at"`
	LastStatus   string       `json:"last_status"`
	LastError    string       `json:"last_error"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type ImportBatch struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	AccountID     string         `json:"account_id"`
	Source        string         `json:"source"`
	Filename      sql.NullString `json:"filename"`
	ColumnMapping sql.NullString `json:"column_mapping"`
	RowCount      int64          `json:"row_count"`
	Status        string         `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
}

type InstrumentSpec struct {
	ID             string  `json:"id"`
	SymbolRoot     string  `json:"symbol_root"`
	InstrumentType string  `json:"instrument_type"`
	TickSize       float64 `json:"tick_size"`
	TickValue      float64 `json:"tick_value"`
	Multiplier     float64 `json:"multiplier"`
	Currency       string  `json:"currency"`
}

type JournalNote struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	OccurredAt string    `json:"occurred_at"`
	Title      string    `json:"title"`
	Body       string    `json:"body"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	Symbols    string    `json:"symbols"`
	NoteType   string    `json:"note_type"`
}

type MarketBarsCache struct {
	CacheKey  string         `json:"cache_key"`
	Symbol    string         `json:"symbol"`
	Interval  string         `json:"interval"`
	FromTs    string         `json:"from_ts"`
	ToTs      string         `json:"to_ts"`
	BarsJson  []byte         `json:"bars_json"`
	Provider  string         `json:"provider"`
	FetchedAt string         `json:"fetched_at"`
	ExpiresAt sql.NullString `json:"expires_at"`
}

type MediaFile struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageKey  string    `json:"storage_key"`
	CreatedAt   time.Time `json:"created_at"`
}

type OcrSetting struct {
	ID           int64     `json:"id"`
	Enabled      int64     `json:"enabled"`
	BaseUrl      string    `json:"base_url"`
	ApiKey       string    `json:"api_key"`
	Model        string    `json:"model"`
	UpdatedAt    time.Time `json:"updated_at"`
	CustomPrompt string    `json:"custom_prompt"`
}

type PropSetting struct {
	AccountID      string          `json:"account_id"`
	UserID         string          `json:"user_id"`
	ProfitTarget   sql.NullFloat64 `json:"profit_target"`
	MaxDrawdown    sql.NullFloat64 `json:"max_drawdown"`
	DrawdownMode   string          `json:"drawdown_mode"`
	DailyLossLimit sql.NullFloat64 `json:"daily_loss_limit"`
	ConsistencyPct sql.NullFloat64 `json:"consistency_pct"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type RiskRule struct {
	UserID                string          `json:"user_id"`
	MaxRiskPerTrade       sql.NullFloat64 `json:"max_risk_per_trade"`
	MaxDailyLoss          sql.NullFloat64 `json:"max_daily_loss"`
	MaxOpenRisk           sql.NullFloat64 `json:"max_open_risk"`
	DefaultAccountRiskPct sql.NullFloat64 `json:"default_account_risk_pct"`
	UpdatedAt             time.Time       `json:"updated_at"`
	MaxTradesPerDay       sql.NullInt64   `json:"max_trades_per_day"`
	MaxConsecutiveLosses  sql.NullInt64   `json:"max_consecutive_losses"`
}

type Setup struct {
	ID          string          `json:"id"`
	UserID      string          `json:"user_id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	CreatedAt   time.Time       `json:"created_at"`
	Thesis      string          `json:"thesis"`
	Symbol      string          `json:"symbol"`
	Direction   string          `json:"direction"`
	TargetPrice sql.NullFloat64 `json:"target_price"`
	StopPrice   sql.NullFloat64 `json:"stop_price"`
	Checklist   string          `json:"checklist"`
}

type ShareLink struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Token     string       `json:"token"`
	ScopeJson string       `json:"scope_json"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	ViewCount int64        `json:"view_count"`
}

type Tag struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	Name        string `json:"name"`
	Color       string `json:"color"`
	Description string `json:"description"`
	Kind        string `json:"kind"`
}

type Trade struct {
	ID              string          `json:"id"`
	UserID          string          `json:"user_id"`
	AccountID       string          `json:"account_id"`
	Symbol          string          `json:"symbol"`
	InstrumentType  string          `json:"instrument_type"`
	Direction       string          `json:"direction"`
	Status          string          `json:"status"`
	OpenedAt        time.Time       `json:"opened_at"`
	ClosedAt        sql.NullTime    `json:"closed_at"`
	QtyOpened       float64         `json:"qty_opened"`
	AvgEntryPrice   float64         `json:"avg_entry_price"`
	AvgExitPrice    sql.NullFloat64 `json:"avg_exit_price"`
	GrossPnl        sql.NullFloat64 `json:"gross_pnl"`
	FeesTotal       float64         `json:"fees_total"`
	NetPnl          sql.NullFloat64 `json:"net_pnl"`
	PnlCurrency     string          `json:"pnl_currency"`
	ReturnPct       sql.NullFloat64 `json:"return_pct"`
	RMultiple       sql.NullFloat64 `json:"r_multiple"`
	TimeInTradeSecs sql.NullInt64   `json:"time_in_trade_secs"`
	Notes           string          `json:"notes"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	QtyRemaining    float64         `json:"qty_remaining"`
}

type TradeAttachment struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	TradeID     string    `json:"trade_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageKey  string    `json:"storage_key"`
	CreatedAt   time.Time `json:"created_at"`
}

type TradeExecution struct {
	TradeID     string `json:"trade_id"`
	ExecutionID string `json:"execution_id"`
}

type TradeJournal struct {
	TradeID        string          `json:"trade_id"`
	UserID         string          `json:"user_id"`
	Notes          string          `json:"notes"`
	SetupID        sql.NullString  `json:"setup_id"`
	InitialRisk    sql.NullFloat64 `json:"initial_risk"`
	UpdatedAt      time.Time       `json:"updated_at"`
	TargetPrice    sql.NullFloat64 `json:"target_price"`
	StopPrice      sql.NullFloat64 `json:"stop_price"`
	EmotionalState string          `json:"emotional_state"`
	Confidence     sql.NullInt64   `json:"confidence"`
	TradeQuality   sql.NullInt64   `json:"trade_quality"`
	Mae            sql.NullFloat64 `json:"mae"`
	Mfe            sql.NullFloat64 `json:"mfe"`
	PostExitMae    sql.NullFloat64 `json:"post_exit_mae"`
	PostExitMfe    sql.NullFloat64 `json:"post_exit_mfe"`
}

type TradeSetup struct {
	TradeID string `json:"trade_id"`
	SetupID string `json:"setup_id"`
}

type TradeTag struct {
	TradeID string `json:"trade_id"`
	TagID   string `json:"tag_id"`
}

type User struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	TotpSecret   sql.NullString `json:"totp_secret"`
	CreatedAt    time.Time      `json:"created_at"`
	IsAdmin      int64          `json:"is_admin"`
}

type UserPreference struct {
	UserID    string    `json:"user_id"`
	Prefs     string    `json:"prefs"`
	UpdatedAt time.Time `json:"updated_at"`
}
