// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ocr_settings.sql

package storepg

import (
	"context"
	"time"
)

const getOcrSettings = `-- name: GetOcrSettings :one
SELECT id, enabled, base_url, api_key, model, custom_prompt, updated_at
FROM ocr_settings
WHERE id = 1
`

type GetOcrSettingsRow struct {
	ID           int64     `json:"id"`
	Enabled      int64     `json:"enabled"`
	BaseUrl      string    `json:"base_url"`
	ApiKey       string    `json:"api_key"`
	Model        string    `json:"model"`
	CustomPrompt string    `json:"custom_prompt"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetOcrSettings(ctx context.Context) (GetOcrSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getOcrSettings)
	var i GetOcrSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Model,
		&i.CustomPrompt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOcrSettings = `-- name: UpsertOcrSettings :one
INSERT INTO ocr_settings (id, enabled, base_url, api_key, model, custom_prompt, updated_at)
VALUES (1, $1, $2, $3, $4, $5, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    enabled = excluded.enabled,
    base_url = excluded.base_url,
    api_key = excluded.api_key,
    model = excluded.model,
    custom_prompt = excluded.custom_prompt,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, enabled, base_url, api_key, model, updated_at, custom_prompt
`

type UpsertOcrSettingsParams struct {
	Enabled      int64  `json:"enabled"`
	BaseUrl      string `json:"base_url"`
	ApiKey       string `json:"api_key"`
	Model        string `json:"model"`
	CustomPrompt string `json:"custom_prompt"`
}

func (q *Queries) UpsertOcrSettings(ctx context.Context, arg UpsertOcrSettingsParams) (OcrSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertOcrSettings,
		arg.Enabled,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Model,
		arg.CustomPrompt,
	)
	var i OcrSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Model,
		&i.UpdatedAt,
		&i.CustomPrompt,
	)
	return i, err
}
