// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prop_settings.sql

package storepg

import (
	"context"
	"database/sql"
)

const deletePropSettings = `-- name: DeletePropSettings :exec
DELETE FROM prop_settings WHERE account_id = $1 AND user_id = $2
`

type DeletePropSettingsParams struct {
	AccountID string `json:"account_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) DeletePropSettings(ctx context.Context, arg DeletePropSettingsParams) error {
	_, err := q.db.ExecContext(ctx, deletePropSettings, arg.AccountID, arg.UserID)
	return err
}

const getPropSettings = `-- name: GetPropSettings :one
SELECT account_id, user_id, profit_target, max_drawdown, drawdown_mode, daily_loss_limit, consistency_pct, updated_at
FROM prop_settings WHERE account_id = $1 AND user_id = $2
`

type GetPropSettingsParams struct {
	AccountID string `json:"account_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetPropSettings(ctx context.Context, arg GetPropSettingsParams) (PropSetting, error) {
	row := q.db.QueryRowContext(ctx, getPropSettings, arg.AccountID, arg.UserID)
	var i PropSetting
	err := row.Scan(
		&i.AccountID,
		&i.UserID,
		&i.ProfitTarget,
		&i.MaxDrawdown,
		&i.DrawdownMode,
		&i.DailyLossLimit,
		&i.ConsistencyPct,
		&i.UpdatedAt,
	)
	return i, err
}

const listPropSettingsForUser = `-- name: ListPropSettingsForUser :many
SELECT account_id, user_id, profit_target, max_drawdown, drawdown_mode, daily_loss_limit, consistency_pct, updated_at
FROM prop_settings WHERE user_id = $1 ORDER BY account_id
`

func (q *Queries) ListPropSettingsForUser(ctx context.Context, userID string) ([]PropSetting, error) {
	rows, err := q.db.QueryContext(ctx, listPropSettingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PropSetting
	for rows.Next() {
		var i PropSetting
		if err := rows.Scan(
			&i.AccountID,
			&i.UserID,
			&i.ProfitTarget,
			&i.MaxDrawdown,
			&i.DrawdownMode,
			&i.DailyLossLimit,
			&i.ConsistencyPct,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPropSettings = `-- name: UpsertPropSettings :one
INSERT INTO prop_settings (account_id, user_id, profit_target, max_drawdown, drawdown_mode, daily_loss_limit, consistency_pct, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, CURRENT_TIMESTAMP)
ON CONFLICT(account_id) DO UPDATE SET
    profit_target = excluded.profit_target,
    max_drawdown = excluded.max_drawdown,
    drawdown_mode = excluded.drawdown_mode,
    daily_loss_limit = excluded.daily_loss_limit,
    consistency_pct = excluded.consistency_pct,
    updated_at = CURRENT_TIMESTAMP
RETURNING account_id, user_id, profit_target, max_drawdown, drawdown_mode, daily_loss_limit, consistency_pct, updated_at
`

type UpsertPropSettingsParams struct {
	AccountID      string          `json:"account_id"`
	UserID         string          `json:"user_id"`
	ProfitTarget   sql.NullFloat64 `json:"profit_target"`
	MaxDrawdown    sql.NullFloat64 `json:"max_drawdown"`
	DrawdownMode   string          `json:"drawdown_mode"`
	DailyLossLimit sql.NullFloat64 `json:"daily_loss_limit"`
	ConsistencyPct sql.NullFloat64 `json:"consistency_pct"`
}

func (q *Queries) UpsertPropSettings(ctx context.Context, arg UpsertPropSettingsParams) (PropSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertPropSettings,
		arg.AccountID,
		arg.UserID,
		arg.ProfitTarget,
		arg.MaxDrawdown,
		arg.DrawdownMode,
		arg.DailyLossLimit,
		arg.ConsistencyPct,
	)
	var i PropSetting
	err := row.Scan(
		&i.AccountID,
		&i.UserID,
		&i.ProfitTarget,
		&i.MaxDrawdown,
		&i.DrawdownMode,
		&i.DailyLossLimit,
		&i.ConsistencyPct,
		&i.UpdatedAt,
	)
	return i, err
}
