// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: risk_rules.sql

package storepg

import (
	"context"
	"database/sql"
)

const getRiskRules = `-- name: GetRiskRules :one
SELECT user_id, max_risk_per_trade, max_daily_loss, max_open_risk, default_account_risk_pct, updated_at, max_trades_per_day, max_consecutive_losses
FROM risk_rules WHERE user_id = $1
`

func (q *Queries) GetRiskRules(ctx context.Context, userID string) (RiskRule, error) {
	row := q.db.QueryRowContext(ctx, getRiskRules, userID)
	var i RiskRule
	err := row.Scan(
		&i.UserID,
		&i.MaxRiskPerTrade,
		&i.MaxDailyLoss,
		&i.MaxOpenRisk,
		&i.DefaultAccountRiskPct,
		&i.UpdatedAt,
		&i.MaxTradesPerDay,
		&i.MaxConsecutiveLosses,
	)
	return i, err
}

const listJournalRisks = `-- name: ListJournalRisks :many
SELECT trade_id, initial_risk FROM trade_journal
WHERE user_id = $1 AND initial_risk IS NOT NULL AND initial_risk > 0
`

type ListJournalRisksRow struct {
	TradeID     string          `json:"trade_id"`
	InitialRisk sql.NullFloat64 `json:"initial_risk"`
}

func (q *Queries) ListJournalRisks(ctx context.Context, userID string) ([]ListJournalRisksRow, error) {
	rows, err := q.db.QueryContext(ctx, listJournalRisks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJournalRisksRow
	for rows.Next() {
		var i ListJournalRisksRow
		if err := rows.Scan(&i.TradeID, &i.InitialRisk); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRiskRules = `-- name: UpsertRiskRules :one
INSERT INTO risk_rules (user_id, max_risk_per_trade, max_daily_loss, max_open_risk, default_account_risk_pct, max_trades_per_day, max_consecutive_losses, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
    max_risk_per_trade = excluded.max_risk_per_trade,
    max_daily_loss = excluded.max_daily_loss,
    max_open_risk = excluded.max_open_risk,
    default_account_risk_pct = excluded.default_account_risk_pct,
    max_trades_per_day = excluded.max_trades_per_day,
    max_consecutive_losses = excluded.max_consecutive_losses,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, max_risk_per_trade, max_daily_loss, max_open_risk, default_account_risk_pct, updated_at, max_trades_per_day, max_consecutive_losses
`

type UpsertRiskRulesParams struct {
	UserID                string          `json:"user_id"`
	MaxRiskPerTrade       sql.NullFloat64 `json:"max_risk_per_trade"`
	MaxDailyLoss          sql.NullFloat64 `json:"max_daily_loss"`
	MaxOpenRisk           sql.NullFloat64 `json:"max_open_risk"`
	DefaultAccountRiskPct sql.NullFloat64 `json:"default_account_risk_pct"`
	MaxTradesPerDay       sql.NullInt64   `json:"max_trades_per_day"`
	MaxConsecutiveLosses  sql.NullInt64   `json:"max_consecutive_losses"`
}

func (q *Queries) UpsertRiskRules(ctx context.Context, arg UpsertRiskRulesParams) (RiskRule, error) {
	row := q.db.QueryRowContext(ctx, upsertRiskRules,
		arg.UserID,
		arg.MaxRiskPerTrade,
		arg.MaxDailyLoss,
		arg.MaxOpenRisk,
		arg.DefaultAccountRiskPct,
		arg.MaxTradesPerDay,
		arg.MaxConsecutiveLosses,
	)
	var i RiskRule
	err := row.Scan(
		&i.UserID,
		&i.MaxRiskPerTrade,
		&i.MaxDailyLoss,
		&i.MaxOpenRisk,
		&i.DefaultAccountRiskPct,
		&i.UpdatedAt,
		&i.MaxTradesPerDay,
		&i.MaxConsecutiveLosses,
	)
	return i, err
}
