// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setups.sql

package storepg

import (
	"context"
	"database/sql"
)

const createSetup = `-- name: CreateSetup :one
INSERT INTO setups (id, user_id, name, description, thesis, symbol, direction, target_price, stop_price, checklist)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, name, description, created_at, thesis, symbol, direction, target_price, stop_price, checklist
`

type CreateSetupParams struct {
	ID          string          `json:"id"`
	UserID      string          `json:"user_id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Thesis      string          `json:"thesis"`
	Symbol      string          `json:"symbol"`
	Direction   string          `json:"direction"`
	TargetPrice sql.NullFloat64 `json:"target_price"`
	StopPrice   sql.NullFloat64 `json:"stop_price"`
	Checklist   string          `json:"checklist"`
}

func (q *Queries) CreateSetup(ctx context.Context, arg CreateSetupParams) (Setup, error) {
	row := q.db.QueryRowContext(ctx, createSetup,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Thesis,
		arg.Symbol,
		arg.Direction,
		arg.TargetPrice,
		arg.StopPrice,
		arg.Checklist,
	)
	var i Setup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.Thesis,
		&i.Symbol,
		&i.Direction,
		&i.TargetPrice,
		&i.StopPrice,
		&i.Checklist,
	)
	return i, err
}

const deleteSetup = `-- name: DeleteSetup :execrows
DELETE FROM setups WHERE id = $1 AND user_id = $2
`

type DeleteSetupParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteSetup(ctx context.Context, arg DeleteSetupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSetup, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSetup = `-- name: GetSetup :one
SELECT id, user_id, name, description, created_at, thesis, symbol, direction, target_price, stop_price, checklist FROM setups WHERE id = $1 AND user_id = $2
`

type GetSetupParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetSetup(ctx context.Context, arg GetSetupParams) (Setup, error) {
	row := q.db.QueryRowContext(ctx, getSetup, arg.ID, arg.UserID)
	var i Setup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.Thesis,
		&i.Symbol,
		&i.Direction,
		&i.TargetPrice,
		&i.StopPrice,
		&i.Checklist,
	)
	return i, err
}

const listSetups = `-- name: ListSetups :many
SELECT id, user_id, name, description, created_at, thesis, symbol, direction, target_price, stop_price, checklist FROM setups WHERE user_id = $1 ORDER BY name
`

func (q *Queries) ListSetups(ctx context.Context, userID string) ([]Setup, error) {
	rows, err := q.db.QueryContext(ctx, listSetups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setup
	for rows.Next() {
		var i Setup
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.Thesis,
			&i.Symbol,
			&i.Direction,
			&i.TargetPrice,
			&i.StopPrice,
			&i.Checklist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSetup = `-- name: UpdateSetup :exec
UPDATE setups SET
    name = $1,
    description = $2,
    thesis = $3,
    symbol = $4,
    direction = $5,
    target_price = $6,
    stop_price = $7,
    checklist = $8
WHERE id = $9 AND user_id = $10
`

type UpdateSetupParams struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Thesis      string          `json:"thesis"`
	Symbol      string          `json:"symbol"`
	Direction   string          `json:"direction"`
	TargetPrice sql.NullFloat64 `json:"target_price"`
	StopPrice   sql.NullFloat64 `json:"stop_price"`
	Checklist   string          `json:"checklist"`
	ID          string          `json:"id"`
	UserID      string          `json:"user_id"`
}

func (q *Queries) UpdateSetup(ctx context.Context, arg UpdateSetupParams) error {
	_, err := q.db.ExecContext(ctx, updateSetup,
		arg.Name,
		arg.Description,
		arg.Thesis,
		arg.Symbol,
		arg.Direction,
		arg.TargetPrice,
		arg.StopPrice,
		arg.Checklist,
		arg.ID,
		arg.UserID,
	)
	return err
}
