// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share_links.sql

package storepg

import (
	"context"
	"database/sql"
)

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO share_links (
    id, user_id, token, scope_json, expires_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, CURRENT_TIMESTAMP
) RETURNING id, user_id, token, scope_json, created_at, expires_at, revoked_at, view_count
`

type CreateShareLinkParams struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Token     string       `json:"token"`
	ScopeJson string       `json:"scope_json"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRowContext(ctx, createShareLink,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ScopeJson,
		arg.ExpiresAt,
	)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ScopeJson,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ViewCount,
	)
	return i, err
}

const getShareLinkByToken = `-- name: GetShareLinkByToken :one
SELECT id, user_id, token, scope_json, created_at, expires_at, revoked_at, view_count
FROM share_links
WHERE token = $1 AND revoked_at IS NULL
`

func (q *Queries) GetShareLinkByToken(ctx context.Context, token string) (ShareLink, error) {
	row := q.db.QueryRowContext(ctx, getShareLinkByToken, token)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ScopeJson,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ViewCount,
	)
	return i, err
}

const incrementShareLinkViews = `-- name: IncrementShareLinkViews :exec
UPDATE share_links
SET view_count = view_count + 1
WHERE id = $1
`

func (q *Queries) IncrementShareLinkViews(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementShareLinkViews, id)
	return err
}

const listShareLinksByUser = `-- name: ListShareLinksByUser :many
SELECT id, user_id, token, scope_json, created_at, expires_at, revoked_at, view_count
FROM share_links
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListShareLinksByUser(ctx context.Context, userID string) ([]ShareLink, error) {
	rows, err := q.db.QueryContext(ctx, listShareLinksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareLink
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.ScopeJson,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeShareLink = `-- name: RevokeShareLink :execrows
UPDATE share_links
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeShareLinkParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RevokeShareLink(ctx context.Context, arg RevokeShareLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeShareLink, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
