// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package storepg

import (
	"context"
)

const clearTradeTags = `-- name: ClearTradeTags :exec
DELETE FROM trade_tags WHERE trade_id = $1
`

func (q *Queries) ClearTradeTags(ctx context.Context, tradeID string) error {
	_, err := q.db.ExecContext(ctx, clearTradeTags, tradeID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, user_id, name, color, description, kind) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, name, color, description, kind
`

type CreateTagParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	Name        string `json:"name"`
	Color       string `json:"color"`
	Description string `json:"description"`
	Kind        string `json:"kind"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.Kind,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.Kind,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags WHERE id = $1 AND user_id = $2
`

type DeleteTagParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTag, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTags = `-- name: ListTags :many
SELECT id, user_id, name, color, description, kind FROM tags WHERE user_id = $1 ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context, userID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTrade = `-- name: ListTagsForTrade :many
SELECT t.id, t.user_id, t.name, t.color, t.description, t.kind FROM tags t JOIN trade_tags tt ON tt.tag_id = t.id WHERE tt.trade_id = $1
`

func (q *Queries) ListTagsForTrade(ctx context.Context, tradeID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForTrade, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradeTagsForUser = `-- name: ListTradeTagsForUser :many
SELECT tt.trade_id, t.id, t.user_id, t.name, t.color, t.description, t.kind
FROM trade_tags tt
JOIN tags t ON t.id = tt.tag_id
JOIN trades tr ON tr.id = tt.trade_id
WHERE tr.user_id = $1
ORDER BY t.name
`

type ListTradeTagsForUserRow struct {
	TradeID     string `json:"trade_id"`
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	Name        string `json:"name"`
	Color       string `json:"color"`
	Description string `json:"description"`
	Kind        string `json:"kind"`
}

func (q *Queries) ListTradeTagsForUser(ctx context.Context, userID string) ([]ListTradeTagsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listTradeTagsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTradeTagsForUserRow
	for rows.Next() {
		var i ListTradeTagsForUserRow
		if err := rows.Scan(
			&i.TradeID,
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTradeTags = `-- name: SetTradeTags :exec
INSERT INTO trade_tags (trade_id, tag_id) VALUES ($1, $2)
ON CONFLICT (trade_id, tag_id) DO NOTHING
`

type SetTradeTagsParams struct {
	TradeID string `json:"trade_id"`
	TagID   string `json:"tag_id"`
}

func (q *Queries) SetTradeTags(ctx context.Context, arg SetTradeTagsParams) error {
	_, err := q.db.ExecContext(ctx, setTradeTags, arg.TradeID, arg.TagID)
	return err
}

const updateTag = `-- name: UpdateTag :execrows
UPDATE tags SET name = $1, color = $2, description = $3, kind = $4 WHERE id = $5 AND user_id = $6
`

type UpdateTagParams struct {
	Name        string `json:"name"`
	Color       string `json:"color"`
	Description string `json:"description"`
	Kind        string `json:"kind"`
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTag,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.Kind,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
