// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trades.sql

package storepg

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const clearTradeExecutions = `-- name: ClearTradeExecutions :exec
DELETE FROM trade_executions WHERE trade_id = $1
`

func (q *Queries) ClearTradeExecutions(ctx context.Context, tradeID string) error {
	_, err := q.db.ExecContext(ctx, clearTradeExecutions, tradeID)
	return err
}

const deleteTrade = `-- name: DeleteTrade :execrows
DELETE FROM trades WHERE id = $1 AND user_id = $2
`

type DeleteTradeParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTrade(ctx context.Context, arg DeleteTradeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrade, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTradesForAccount = `-- name: DeleteTradesForAccount :exec
DELETE FROM trades WHERE user_id = $1 AND account_id = $2
`

type DeleteTradesForAccountParams struct {
	UserID    string `json:"user_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) DeleteTradesForAccount(ctx context.Context, arg DeleteTradesForAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteTradesForAccount, arg.UserID, arg.AccountID)
	return err
}

const deleteTradesNotInAccount = `-- name: DeleteTradesNotInAccount :exec
DELETE FROM trades WHERE user_id = $1 AND account_id = $2 AND id NOT IN ($3)
`

type DeleteTradesNotInAccountParams struct {
	UserID    string   `json:"user_id"`
	AccountID string   `json:"account_id"`
	Keep      []string `json:"keep"`
}

// NOTE: sqlc+database/sql emits a broken single-$3 slice expand for Postgres.
// storepg/trades.sql.go implements placeholder expansion manually; re-check after `make sqlc`.
func (q *Queries) DeleteTradesNotInAccount(ctx context.Context, arg DeleteTradesNotInAccountParams) error {
	query := deleteTradesNotInAccount
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	queryParams = append(queryParams, arg.AccountID)
	if len(arg.Keep) > 0 {
		for _, v := range arg.Keep {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keep*/?", strings.Repeat(",?", len(arg.Keep))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keep*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getTrade = `-- name: GetTrade :one
SELECT id, user_id, account_id, symbol, instrument_type, direction, status, opened_at, closed_at, qty_opened, avg_entry_price, avg_exit_price, gross_pnl, fees_total, net_pnl, pnl_currency, return_pct, r_multiple, time_in_trade_secs, notes, created_at, updated_at, qty_remaining FROM trades WHERE id = $1 AND user_id = $2
`

type GetTradeParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetTrade(ctx context.Context, arg GetTradeParams) (Trade, error) {
	row := q.db.QueryRowContext(ctx, getTrade, arg.ID, arg.UserID)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Symbol,
		&i.InstrumentType,
		&i.Direction,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.QtyOpened,
		&i.AvgEntryPrice,
		&i.AvgExitPrice,
		&i.GrossPnl,
		&i.FeesTotal,
		&i.NetPnl,
		&i.PnlCurrency,
		&i.ReturnPct,
		&i.RMultiple,
		&i.TimeInTradeSecs,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QtyRemaining,
	)
	return i, err
}

const insertTrade = `-- name: InsertTrade :one
INSERT INTO trades (id, user_id, account_id, symbol, instrument_type, direction, status,
    opened_at, closed_at, qty_opened, qty_remaining, avg_entry_price, avg_exit_price, gross_pnl, fees_total,
    net_pnl, pnl_currency, return_pct, r_multiple, time_in_trade_secs, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21) RETURNING id, user_id, account_id, symbol, instrument_type, direction, status, opened_at, closed_at, qty_opened, avg_entry_price, avg_exit_price, gross_pnl, fees_total, net_pnl, pnl_currency, return_pct, r_multiple, time_in_trade_secs, notes, created_at, updated_at, qty_remaining
`

type InsertTradeParams struct {
	ID              string          `json:"id"`
	UserID          string          `json:"user_id"`
	AccountID       string          `json:"account_id"`
	Symbol          string          `json:"symbol"`
	InstrumentType  string          `json:"instrument_type"`
	Direction       string          `json:"direction"`
	Status          string          `json:"status"`
	OpenedAt        time.Time       `json:"opened_at"`
	ClosedAt        sql.NullTime    `json:"closed_at"`
	QtyOpened       float64         `json:"qty_opened"`
	QtyRemaining    float64         `json:"qty_remaining"`
	AvgEntryPrice   float64         `json:"avg_entry_price"`
	AvgExitPrice    sql.NullFloat64 `json:"avg_exit_price"`
	GrossPnl        sql.NullFloat64 `json:"gross_pnl"`
	FeesTotal       float64         `json:"fees_total"`
	NetPnl          sql.NullFloat64 `json:"net_pnl"`
	PnlCurrency     string          `json:"pnl_currency"`
	ReturnPct       sql.NullFloat64 `json:"return_pct"`
	RMultiple       sql.NullFloat64 `json:"r_multiple"`
	TimeInTradeSecs sql.NullInt64   `json:"time_in_trade_secs"`
	Notes           string          `json:"notes"`
}

func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) (Trade, error) {
	row := q.db.QueryRowContext(ctx, insertTrade,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.Symbol,
		arg.InstrumentType,
		arg.Direction,
		arg.Status,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.QtyOpened,
		arg.QtyRemaining,
		arg.AvgEntryPrice,
		arg.AvgExitPrice,
		arg.GrossPnl,
		arg.FeesTotal,
		arg.NetPnl,
		arg.PnlCurrency,
		arg.ReturnPct,
		arg.RMultiple,
		arg.TimeInTradeSecs,
		arg.Notes,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Symbol,
		&i.InstrumentType,
		&i.Direction,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.QtyOpened,
		&i.AvgEntryPrice,
		&i.AvgExitPrice,
		&i.GrossPnl,
		&i.FeesTotal,
		&i.NetPnl,
		&i.PnlCurrency,
		&i.ReturnPct,
		&i.RMultiple,
		&i.TimeInTradeSecs,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QtyRemaining,
	)
	return i, err
}

const linkTradeExecution = `-- name: LinkTradeExecution :exec
INSERT INTO trade_executions (trade_id, execution_id) VALUES ($1, $2)
`

type LinkTradeExecutionParams struct {
	TradeID     string `json:"trade_id"`
	ExecutionID string `json:"execution_id"`
}

func (q *Queries) LinkTradeExecution(ctx context.Context, arg LinkTradeExecutionParams) error {
	_, err := q.db.ExecContext(ctx, linkTradeExecution, arg.TradeID, arg.ExecutionID)
	return err
}

const listClosedTrades = `-- name: ListClosedTrades :many
SELECT id, user_id, account_id, symbol, instrument_type, direction, status, opened_at, closed_at, qty_opened, avg_entry_price, avg_exit_price, gross_pnl, fees_total, net_pnl, pnl_currency, return_pct, r_multiple, time_in_trade_secs, notes, created_at, updated_at, qty_remaining FROM trades
WHERE user_id = $1 AND status = 'closed'
  AND (account_id = COALESCE($2, account_id))
  AND (closed_at >= COALESCE($3::timestamp, closed_at))
  AND (closed_at <= COALESCE($4::timestamp, closed_at))
ORDER BY closed_at
`

type ListClosedTradesParams struct {
	UserID    string         `json:"user_id"`
	AccountID sql.NullString `json:"account_id"`
	From      sql.NullTime   `json:"from"`
	To        sql.NullTime   `json:"to"`
}

func (q *Queries) ListClosedTrades(ctx context.Context, arg ListClosedTradesParams) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, listClosedTrades,
		arg.UserID,
		arg.AccountID,
		arg.From,
		arg.To,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Symbol,
			&i.InstrumentType,
			&i.Direction,
			&i.Status,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.QtyOpened,
			&i.AvgEntryPrice,
			&i.AvgExitPrice,
			&i.GrossPnl,
			&i.FeesTotal,
			&i.NetPnl,
			&i.PnlCurrency,
			&i.ReturnPct,
			&i.RMultiple,
			&i.TimeInTradeSecs,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QtyRemaining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionsForTrade = `-- name: ListExecutionsForTrade :many
SELECT e.id, e.user_id, e.account_id, e.external_id, e.symbol, e.instrument_type, e.side, e.quantity, e.price, e.fees, e.commission, e.executed_at, e.multiplier, e.details, e.import_batch_id, e.dedup_hash, e.created_at FROM executions e
JOIN trade_executions te ON te.execution_id = e.id
WHERE te.trade_id = $1 ORDER BY e.executed_at, e.id
`

func (q *Queries) ListExecutionsForTrade(ctx context.Context, tradeID string) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionsForTrade, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.ExternalID,
			&i.Symbol,
			&i.InstrumentType,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.Fees,
			&i.Commission,
			&i.ExecutedAt,
			&i.Multiplier,
			&i.Details,
			&i.ImportBatchID,
			&i.DedupHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrades = `-- name: ListTrades :many
SELECT id, user_id, account_id, symbol, instrument_type, direction, status, opened_at, closed_at, qty_opened, avg_entry_price, avg_exit_price, gross_pnl, fees_total, net_pnl, pnl_currency, return_pct, r_multiple, time_in_trade_secs, notes, created_at, updated_at, qty_remaining FROM trades
WHERE user_id = $1
  AND (account_id = COALESCE($2, account_id))
  AND (status = COALESCE($3, status))
ORDER BY opened_at DESC
`

type ListTradesParams struct {
	UserID    string         `json:"user_id"`
	AccountID sql.NullString `json:"account_id"`
	Status    sql.NullString `json:"status"`
}

func (q *Queries) ListTrades(ctx context.Context, arg ListTradesParams) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, listTrades, arg.UserID, arg.AccountID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Symbol,
			&i.InstrumentType,
			&i.Direction,
			&i.Status,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.QtyOpened,
			&i.AvgEntryPrice,
			&i.AvgExitPrice,
			&i.GrossPnl,
			&i.FeesTotal,
			&i.NetPnl,
			&i.PnlCurrency,
			&i.ReturnPct,
			&i.RMultiple,
			&i.TimeInTradeSecs,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QtyRemaining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTradeNotes = `-- name: UpdateTradeNotes :exec
UPDATE trades SET notes = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2 AND user_id = $3
`

type UpdateTradeNotesParams struct {
	Notes  string `json:"notes"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateTradeNotes(ctx context.Context, arg UpdateTradeNotesParams) error {
	_, err := q.db.ExecContext(ctx, updateTradeNotes, arg.Notes, arg.ID, arg.UserID)
	return err
}

const upsertTrade = `-- name: UpsertTrade :exec
INSERT INTO trades (id, user_id, account_id, symbol, instrument_type, direction, status,
    opened_at, closed_at, qty_opened, qty_remaining, avg_entry_price, avg_exit_price, gross_pnl, fees_total,
    net_pnl, pnl_currency, return_pct, r_multiple, time_in_trade_secs, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, '')
ON CONFLICT(id) DO UPDATE SET
    account_id = excluded.account_id, symbol = excluded.symbol,
    instrument_type = excluded.instrument_type, direction = excluded.direction,
    status = excluded.status, opened_at = excluded.opened_at, closed_at = excluded.closed_at,
    qty_opened = excluded.qty_opened, qty_remaining = excluded.qty_remaining,
    avg_entry_price = excluded.avg_entry_price,
    avg_exit_price = excluded.avg_exit_price, gross_pnl = excluded.gross_pnl,
    fees_total = excluded.fees_total, net_pnl = excluded.net_pnl,
    pnl_currency = excluded.pnl_currency, return_pct = excluded.return_pct,
    time_in_trade_secs = excluded.time_in_trade_secs, updated_at = CURRENT_TIMESTAMP
`

type UpsertTradeParams struct {
	ID              string          `json:"id"`
	UserID          string          `json:"user_id"`
	AccountID       string          `json:"account_id"`
	Symbol          string          `json:"symbol"`
	InstrumentType  string          `json:"instrument_type"`
	Direction       string          `json:"direction"`
	Status          string          `json:"status"`
	OpenedAt        time.Time       `json:"opened_at"`
	ClosedAt        sql.NullTime    `json:"closed_at"`
	QtyOpened       float64         `json:"qty_opened"`
	QtyRemaining    float64         `json:"qty_remaining"`
	AvgEntryPrice   float64         `json:"avg_entry_price"`
	AvgExitPrice    sql.NullFloat64 `json:"avg_exit_price"`
	GrossPnl        sql.NullFloat64 `json:"gross_pnl"`
	FeesTotal       float64         `json:"fees_total"`
	NetPnl          sql.NullFloat64 `json:"net_pnl"`
	PnlCurrency     string          `json:"pnl_currency"`
	ReturnPct       sql.NullFloat64 `json:"return_pct"`
	RMultiple       sql.NullFloat64 `json:"r_multiple"`
	TimeInTradeSecs sql.NullInt64   `json:"time_in_trade_secs"`
}

func (q *Queries) UpsertTrade(ctx context.Context, arg UpsertTradeParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrade,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.Symbol,
		arg.InstrumentType,
		arg.Direction,
		arg.Status,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.QtyOpened,
		arg.QtyRemaining,
		arg.AvgEntryPrice,
		arg.AvgExitPrice,
		arg.GrossPnl,
		arg.FeesTotal,
		arg.NetPnl,
		arg.PnlCurrency,
		arg.ReturnPct,
		arg.RMultiple,
		arg.TimeInTradeSecs,
	)
	return err
}
