// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_preferences.sql

package storepg

import (
	"context"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, prefs, updated_at FROM user_preferences WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(&i.UserID, &i.Prefs, &i.UpdatedAt)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :one
INSERT INTO user_preferences (user_id, prefs, updated_at)
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
    prefs = excluded.prefs,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, prefs, updated_at
`

type UpsertUserPreferencesParams struct {
	UserID string `json:"user_id"`
	Prefs  string `json:"prefs"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, upsertUserPreferences, arg.UserID, arg.Prefs)
	var i UserPreference
	err := row.Scan(&i.UserID, &i.Prefs, &i.UpdatedAt)
	return i, err
}
