// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weekly_reviews.sql

package storepg

import (
	"context"
	"database/sql"
)

const getWeeklyReview = `-- name: GetWeeklyReview :one
SELECT user_id, week_start, note_id, sent_at, created_at FROM weekly_reviews WHERE user_id = $1 AND week_start = $2
`

type GetWeeklyReviewParams struct {
	UserID    string `json:"user_id"`
	WeekStart string `json:"week_start"`
}

func (q *Queries) GetWeeklyReview(ctx context.Context, arg GetWeeklyReviewParams) (WeeklyReview, error) {
	row := q.db.QueryRowContext(ctx, getWeeklyReview, arg.UserID, arg.WeekStart)
	var i WeeklyReview
	err := row.Scan(
		&i.UserID,
		&i.WeekStart,
		&i.NoteID,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const markWeeklyReviewSent = `-- name: MarkWeeklyReviewSent :exec
UPDATE weekly_reviews SET sent_at = $1 WHERE user_id = $2 AND week_start = $3
`

type MarkWeeklyReviewSentParams struct {
	SentAt    sql.NullTime `json:"sent_at"`
	UserID    string       `json:"user_id"`
	WeekStart string       `json:"week_start"`
}

func (q *Queries) MarkWeeklyReviewSent(ctx context.Context, arg MarkWeeklyReviewSentParams) error {
	_, err := q.db.ExecContext(ctx, markWeeklyReviewSent, arg.SentAt, arg.UserID, arg.WeekStart)
	return err
}

const upsertWeeklyReviewNote = `-- name: UpsertWeeklyReviewNote :exec
INSERT INTO weekly_reviews (user_id, week_start, note_id, created_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT(user_id, week_start) DO UPDATE SET note_id = excluded.note_id
`

type UpsertWeeklyReviewNoteParams struct {
	UserID    string `json:"user_id"`
	WeekStart string `json:"week_start"`
	NoteID    string `json:"note_id"`
}

func (q *Queries) UpsertWeeklyReviewNote(ctx context.Context, arg UpsertWeeklyReviewNoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertWeeklyReviewNote, arg.UserID, arg.WeekStart, arg.NoteID)
	return err
}
