packages:
  - "."

catalog:
  vite: "npm:@voidzero-dev/vite-plus-core@0.3.3"
  vite-plus: "0.3.3"
  vitest: "5.0.3"

overrides:
  vite: "catalog:"
  vitest: "catalog:"

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
