packages:
  - "."

catalog:
  vite: "npm:@voidzero-dev/vite-plus-core@0.2.4"
  vite-plus: "0.2.6"
  vitest: "4.1.10"

overrides:
  vite: "catalog:"
  vitest: "catalog:"

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
